### ISSUE TITLE
RFC 0021 - Sender and recipient identifiers used in envelope as DID key references

### ISSUE THREAD

**Issue by tplooker** [hyperledger/aries-rfcs#104]
Currently at the envelope level of did comm messages, when senders and recipients are referred to, public keys are used. For example in [RFC](https://github.com/hyperledger/aries-rfcs/tree/master/features/0019-encryption-envelope) 

Below is the JWE header

```
{
    "enc": "xchacha20poly1305_ietf",
    "typ": "JWM/1.0",
    "alg": "Authcrypt",
    "recipients": [
        {
            "encrypted_key": "L5XDhH15Pm_vHxSeraY8eOTG6RfcE2NQ3ETeVC-7EiDZyzpRJd8FW0a6qe4JfuAz",
            "header": {
                "kid": "GJ1SzoWzavQYfNL9XkaJdrQejfztN4XqdsiV4ct3LXKL",
                "iv": "a8IminstXHi54_J-Je5IWlOcNgSwD9TB",
                "sender": "ftimwiiYRG7rRQbXgJ13C5aTEQIrsWDI_bsxDqiWbTlVSKPmw6418vz3HmMlelM8AuSiKlaLCmRDI4sDFSgZIcAVXo134V8o8lFoV1BdDI7fdKOZzrKbqCixKJk="
            }
        },
        {
            "encrypted_key": "eAMiD6GDmOtzREhI-TV05_Rhippy8jwOAu5D-2IdVOJgI8-N7QNSulYyCoWiE16Y",
            "header": {
                "kid": "HKTAiYM8cE2kKC9KaNMZLYj4GS8uWCYMBxP2i1Y92zum",
                "iv": "D4tNtHd2rs65EG_A4GB-o0-9BgLxDMfH",
                "sender": "sJ7piu4UDuL_o2pXb-J_JApxsaFrxiTmgpZjltWjYFTUir4b8MWmDdtzp0OnTeHLK9mFrhH4GVA1wVtnokUKogCdNWHscarQscQCRPZDKrW6boftwH8_EYGTL0Q="
            }
        }
    ]
}
```

Both the sender and the kid for the recipients are inline public keys.

The same is present in the non-repudiation envelope [RFC](https://github.com/hyperledger/aries-rfcs/tree/master/features/0066-non-repudiable-cryptographic-envelope)

Below is the JWT header

```
{
    "alg":"EdDSA",
    "kid":"FYmoFw55GeQH7SRFa37dkx1d2dZ3zUF8ckg7wmL7ofN4"
}
```

Again the recipient, identified by the kid is an inline public key.

I think all of these references should be converted to did key references as the envelope level of did comms when speaking about senders and recipients of messages should be identified via did's rather than public keys.

This is the path already taken by [did-auth-jose](https://github.com/decentralized-identity/did-auth-jose)

**Comment by tplooker** [comment]
The other option is to make this behaviour non-binding, take the following example of the non-repudiation envelope

The JWT header could be extended

```
{
    "alg":"EdDSA",
    "kid":"FYmoFw55GeQH7SRFa37dkx1d2dZ3zUF8ckg7wmL7ofN4",
"did_ref" : "did:example:12345#key-1"
}
```

This would allow the envelope layer proccessing to validate the key (identified by the kid) signed the message without resolving the did, however the processing can still also optionally resolve the did via the reference and return the assertion that the signer of the message was also a valid did subject.

**Comment by tplooker** [comment]
Another observation with the current approach is that the alg becomes the definer of the cryptographic primitive used with kid. If a did key reference is used, then this information can be found when the public key is resolved from the did doc.

**Comment by peacekeeper** [comment]
Just a quick note that what you call a did key reference is a form of a "DID URL" (see [Generic DID Syntax](https://w3c-ccg.github.io/did-spec/#generic-did-syntax)).

There's also an example similar to yours in the DID Resolution spec: https://w3c-ccg.github.io/did-resolution/#example-3

I think this could also be used directly as the `kid`, instead of introducing a new `did_ref` field, no?

**Comment by tplooker** [comment]
Thanks, yes `kid` as a did url is my preferred option too, I was just pointing out that a separate field for the did url could yield benificial in the event the did url wasnt resolvable.

**Comment by llorllale** [comment]
@tplooker @kdenhartog 

I've been wondering about this myself. What's the status on this? Has it been accepted?

**Comment by llorllale** [comment]
Note: 

* there is at least one DIDComm message that, by design, is sent by one party on behalf of another: [`connection-invitation` of Introduce Protocol](https://github.com/hyperledger/aries-rfcs/tree/master/features/0028-introduce#connection-invitation).
* We want to get support for n-wise DIDs (see #72)

All this to say that it might make sense to specify senders in the plaintext messages as well under some circumstances.

**Comment by tplooker** [comment]
@llorllale my opinion is for us to use did key references or a did url as the identifier. Otherwise we are not leveraging did's as the identifier instead we are just using public keys. 

The only resistance I have heard to this approach is that resolution now becomes a concern at this layer and what happens in the event this resolution fails for whatever reason. My response to this thinking is that, if we accept we want to refer to subjects as did's in the ecosystem (e.g is a relationship/connection between two dids or two sets of keys) then the reconciling of a public key to a did must happen somewhere and not doing it at this layer IMO is essentially kicking the proverbial can down the road for little benefit.

Another point to make is in a messaging protocol that uses public keys instead of dids as the referent for subjects at this layer, it then begs the question whether `didcomm` should really be called `crypto-messaging` or something that more accurately portrays that fact?

@dhh1128 @kdenhartog @TelegramSam @swcurran does any one else have some thoughts or opinions on this topic, it feels like this is a priority for us to discuss at the moment due to the fact @kdenhartog is reviewing the crypto envelope format and @llorllale and team are current building an implementation of this layer in go?

**Comment by tplooker** [comment]
@SmithSamuelM what would prevent you from miss reporting the crypto suite and associated information? In regards to ephemeral did's this is the intention of [did:key](https://github.com/digitalbazaar/did-method-key) I believe, which I am interested in using in the [following ways](https://github.com/hyperledger/aries-rfcs/issues/201)

**Comment by tplooker** [comment]
I agree with some of your assessment, however could you give an example of how this creates a circular dependency? 

I think evidence with [did-auth-jose](https://github.com/decentralized-identity/did-auth-jose) [git-did](https://github.com/decentralized-identity/github-did) [minimal-cipher](https://github.com/digitalbazaar/minimal-cipher) and the [SIOP-interop-project](https://github.com/decentralized-identity/papers/blob/master/did-authn/siop/did-authn-siop-profile.md#non-normative-examples-of-a-siop-request) all of which use JOSE in one form or another and substitute the sender and recipient identifier fields with dids demonstrate that this can be implemented without a circular dependency i'm aware of.

Lets take packing an auth-crypted DIDComm message for example, if the arguments to pack a message instead of being a key were based on did-urls, the sender would resolve the did-url to get the public key and proceed with the message packing, following this in the recipients block,
they would quote the did-url in the kid field and their own reciprocate did for the connection or relationship in the sender field.

The recipient receiving the message would then iterate through the recipients block looking for a did they possessed keys to, if found, fetch that key from their wallet and decrypt the message. If the message was auth-crypted they would resolve the senders identifier and use that in combination with their private key they had already fetched to decrypt the message. In the process of doing this the resulting decryption would yield sender and recipient information in the context of did's rather than public keys.

Further more if we look into the JOSE specs.

To your point to about the encrypted envelope, yes it is a crypto construct but the kid field to quote the [JWE spec](https://tools.ietf.org/html/draft-jones-json-web-encryption-02)

```
    The "kid" (key ID) header parameter is a hint indicating
    which key was used to encrypt the JWE. This allows originators
    to explicitly signal a change of key to recipients. The interpretation
    of the contents the "kid" parameter is unspecified. This header parameter 
    is OPTIONAL. 
```

Nothing precludes using an did-url as the identifier here rather than a public key.

On the sender/signer side observing this spec more shows that having a resolvable identifier in the JOSE headers is encouraged, so that the product of verifying is not a public key but some other identifier to which someone is known by, in this case it is a URI.

```
4.1.2.  "jku" (JWK Set URL) Header Parameter

   The "jku" (JWK Set URL) Header Parameter is a URI [RFC3986] that
   refers to a resource for a set of JSON-encoded public keys, one of
   which corresponds to the key used to digitally sign the JWS.  The
   keys MUST be encoded as a JWK Set [JWK].  The protocol used to
   acquire the resource MUST provide integrity protection; an HTTP GET
   request to retrieve the JWK Set MUST use Transport Layer Security  
```

**Comment by tplooker** [comment]
Thanks @dhh1128, as always your articulation on these issues is second to none :). First i'd like to point out, the field `kid` is an identifier as the name `key identifier` suggests so we do have identifiers at this level and further more the JOSE spec does leave it free to elect what identifier to use here. The purpose of this identifier is for the sender to indicate as a reference what the recipient needs to use to decrypt the message. Its often convenient for this to be a public key, but it is important to note this is still acting as a reference to the private key in the same way a did key reference would be. If the kid was a did key reference, there is no resolution required for this step, provided private keys are index/tagged with the DID they are associated to.

For example if I received an anon-crypted message from a party, as the recipient of that message I do not need to perform DID resolution, the kid would be a reference to a DID im in control of and I would simply fetch the private key from my wallet that represents that key reference.

I understand the other points you raise, however none of the above explanations answers the simple and original question that @llorllale re-referenced, `how do we identify the sender of a DIDComm message?` And when I say identify to be explicit I'm talking about reconciling a subject to the main identifier I will know them by aka their did.

Granted if we decide no-identification should happen at this crypto layer, we should still expose sufficient information to be able to reliably identify and reconcile the did-key link at the next level and at the moment with out did key references I really don't see how this is possible in a scale-able manner. 

Take the following example.

Say I'm in an n-wise relationship (e.g 50 people) whereby we all know each by DID's constructed for that relationship. I receive a message encrypted to my DID representing me in that n-wise relationship, how do I now know which out of the 49 people possibly sent me that message. Obviously the default answer is to iterate through 49 DID docs looking for a link to a public key I recovered from the decryption, but is that really a feasible and scale-able solution?

Another example, I get a non-repudiable based DIDComm message un-encrypted sent to me via email or text which is an ephemeral proof request, who sent this request, a public key? How do I establish a basis for making a decision on whether to respond? If there was a did key reference here, I can then discover information about that did e.g from public credential registries or a did to domain lookup.

**Comment by tplooker** [comment]
@dhh1128 to the compromise you offer at the end of your previous comment, as I alluded to at the start of this issue I am more than happy to make this behavior non-binding, what I mean by that is include both the public key and the did key reference in the envelope, that way I believe we can achieve the best of both worlds.

**Comment by peacekeeper** [comment]
I think @tplooker is right that per the JOSE specs `kid` is for key references, not for key values. So if a key value rather than a key references should be included in the message, then that's what `jwk` is for. Unfortunately as the name implies that would contain a JWK rather than a multicodec'd key value. So neither of those fields may be entirely correct in JOSE :(

I like @dhh1128's points about having a clean separation between the crypto layer and the DID layer. I have a few more thoughts on that but need to organize them first..

**Comment by OR13** [comment]
https://tools.ietf.org/html/rfc7516#section-4.1.6

There are a couple issues here... 

1. `kid` is used to identify keys (public and private JWK).
2. how can a user resolve a public key, or look up a private key by `kid`
3. how should `kid` be combined with DIDs / DDOs.

By default when importing a JWK in many libraries, if a `kid` is not provided, one will be generated according to https://tools.ietf.org/html/rfc7638.

Here is an example of a DID Document which supports JWK:

https://uniresolver.io/1.0/identifiers/did%3Abtcr%3Axxcl-lzpq-q83a-0d5

```
{
    "id" : "did:btcr:xxcl-lzpq-q83a-0d5#key-JUvpllMEYUZ2joO59UNui_XYDqxVqiFLLAJ8klWuPBw",
    "type" : "EcdsaSecp256k1VerificationKey2019",
    "publicKeyJwk" : {
      "crv" : "secp256k1",
      "kid" : "JUvpllMEYUZ2joO59UNui_XYDqxVqiFLLAJ8klWuPBw",
      "kty" : "EC",
      "x" : "dWCvM4fTdeM0KmloF57zxtBPXTOythHPMm1HCLrdd3A",
      "y" : "36uMVGM7hnw-N6GnjFcihWE3SkrhMLzzLCdPMXPEXlA"
    }
  }
```

Maybe I got this wrong when I created it, but my goals where:

1. to not alter the default JWK that is generated by libraries (notice no did prefix in publicKeyJwk.kid), this supports compatibility with non DID crypto...
2. DID Public Key Id property uses kid (this helps wallets handle decrypting / singing related to a specific DID.

With this part established, you might see JWS/JWE/JWT related to this key of the following formats:


Example 1

```
{
  "alg": "ES256K",
  "typ": "JWT",
  "kid": "JUvpllMEYUZ2joO59UNui_XYDqxVqiFLLAJ8klWuPBw"
}
```

This is what a head would look like for non did related crypto, important to note that the `kid` field could be anything, it is just really helpful if its a proper thumbprint. 

[Example 2](https://jwt.io/#debugger-io?token=eyJhbGciOiJFUzI1NksiLCJ0eXAiOiJKV1QiLCJraWQiOiJkaWQ6YnRjcjp4eGNsLWx6cHEtcTgzYS0wZDUja2V5LUpVdnBsbE1FWVVaMmpvTzU5VU51aV9YWURxeFZxaUZMTEFKOGtsV3VQQncifQ.eyJqdGkiOiJ1cm46dXVpZDpjM2Q2MjRjMi0yZDdmLTRjMDYtYjRhMy1jYTk2OWI0NjY3MzMiLCJpc3MiOiJkaWQ6YnRjcjp4eGNsLWx6cHEtcTgzYS0wZDUiLCJhdWQiOiJkaWQ6ZWxlbTplVVJTRkVFdjZKN3MzVEotamhUX1pTNHVHUnlDRGJ3YzM0N0VXbHFwTmd3IiwiaWF0IjoxNTY3NzkyNzk2LCJuYmYiOjE1Njc3OTI3OTYsImV4cCI6MTkyNzc4OTE5NiwidnAiOnsiQGNvbnRleHQiOlsiaHR0cHM6Ly93d3cudzMub3JnLzIwMTgvY3JlZGVudGlhbHMvdjEiLCJodHRwczovL3d3dy53My5vcmcvMjAxOC9jcmVkZW50aWFscy9leGFtcGxlcy92MSJdLCJ0eXBlIjpbIlZlcmlmaWFibGVQcmVzZW50YXRpb24iLCJDcmVkZW50aWFsTWFuYWdlclByZXNlbnRhdGlvbiJdLCJ2ZXJpZmlhYmxlQ3JlZGVudGlhbCI6WyJleUpoYkdjaU9pSkZVekkxTmtzaUxDSjBlWEFpT2lKS1YxUWlMQ0pyYVdRaU9pSmthV1E2WW5SamNqcDRlR05zTFd4NmNIRXRjVGd6WVMwd1pEVWphMlY1TFVwVmRuQnNiRTFGV1ZWYU1tcHZUelU1VlU1MWFWOVlXVVJ4ZUZaeGFVWk1URUZLT0d0c1YzVlFRbmNpZlEuZXlKemRXSWlPaUprYVdRNlpXeGxiVHBsVlZKVFJrVkZkalpLTjNNelZFb3RhbWhVWDFwVE5IVkhVbmxEUkdKM1l6TTBOMFZYYkhGd1RtZDNJaXdpYW5ScElqb2lkWEp1T25WMWFXUTZPREV6WkdVeE1XRXRPVGd4TXkwME1qRmtMV0UwTlRZdFlqazRaVEUyTnpkalpXSXdJaXdpYVhOeklqb2laR2xrT21KMFkzSTZlSGhqYkMxc2VuQnhMWEU0TTJFdE1HUTFJaXdpYVdGMElqb3hOVFkzTnpreU56UTVMQ0p1WW1ZaU9qRTFOamMzT1RJM05Ea3NJbVY0Y0NJNk1Ua3lOemM0T1RFME9Td2lkbU1pT25zaVFHTnZiblJsZUhRaU9sc2lhSFIwY0hNNkx5OTNkM2N1ZHpNdWIzSm5Mekl3TVRndlkzSmxaR1Z1ZEdsaGJITXZkakVpTENKb2RIUndjem92TDNkM2R5NTNNeTV2Y21jdk1qQXhPQzlqY21Wa1pXNTBhV0ZzY3k5bGVHRnRjR3hsY3k5Mk1TSmRMQ0owZVhCbElqcGJJbFpsY21sbWFXRmliR1ZEY21Wa1pXNTBhV0ZzSWl3aVZXNXBkbVZ5YzJsMGVVUmxaM0psWlVOeVpXUmxiblJwWVd3aVhTd2lZM0psWkdWdWRHbGhiRk4xWW1wbFkzUWlPbnNpWkdWbmNtVmxJanA3SW5SNWNHVWlPaUpDWVdOb1pXeHZja1JsWjNKbFpTSXNJblZ1YVhabGNuTnBkSGtpT2lKTlNWUWlmWDE5ZlEuVmMzdWR4ZkZ1bFcyU2xsYXBCNEl6VUY4cFNoenljcnF1eWNLbnhPdENBMU81dnZXb1lZWW1yT2l6N1JvVm9JZExfR0tBUUNQQnhzQmg3bHZpU2lmeGciXX19.qiCEKLSXI12YHAjJWu6C29LOLI0q6FXonAlTTUrPWEQY4TY2l99YnLcdHRsoRP2jTnXmLsZGVu8YEV9A1MoQdg)

```
{
  "alg": "ES256K",
  "typ": "JWT",
  "kid": "did:btcr:xxcl-lzpq-q83a-0d5#key-JUvpllMEYUZ2joO59UNui_XYDqxVqiFLLAJ8klWuPBw"
}
```

The `kid` field here provides a mechanism for getting the correct public key (or looking up the same private key). 

Per https://tools.ietf.org/html/rfc7515#section-4.1.4

```
   The "kid" (key ID) Header Parameter is a hint indicating which key
   was used to secure the JWS.  This parameter allows originators to
   explicitly signal a change of key to recipients.  The structure of
   the "kid" value is unspecified.  Its value MUST be a case-sensitive
   string.  Use of this Header Parameter is OPTIONAL.

   When used with a JWK, the "kid" value is used to match a JWK "kid"
   parameter value.
```

1. ** The structure of the "kid" value is unspecified. **

2. ** When used with a JWK, the "kid" value is used to match a JWK "kid" parameter value. **

These 2 sentences are the most helpful. My interpretation of 1 + 2 is that "used to match" is not "MUST equal" and my proposed solution is therefore valid.

It is possible to generate a JWK where both the `kid` are equal, and it is possible to verify a JWS when they are not.

These examples are taken from the interop project:

https://github.com/decentralized-identity/interop-project

**Comment by TelegramSam** [comment]
Continue issue here: https://github.com/decentralized-identity/didcomm-messaging/issues/20
