### ISSUE TITLE
Should we adopt RFC 2119 keywords?

### ISSUE THREAD

**Issue by dhh1128** [hyperledger/aries-rfcs#114]
See https://tools.ietf.org/html/rfc2119

**Comment by kdenhartog** [comment]
I would like to see us do this. I already sporadically am using them.

**Comment by swcurran** [comment]
I think there is general agreement that we SHOULD do this, and that RFC writers and reviewers MUST take this into account in their work.

Assuming we want to do this, @dhh1128 do a PR to reflect this in the instructions and then close this issue?  Unless you think there should be more substantive discussion across the community.

I do think we should leave it up to RFC writers and community contributors to retroactively update the existing RFCs.

**Comment by TelegramSam** [comment]
Drummond has suggested: https://tools.ietf.org/html/rfc6919

**Comment by swcurran** [comment]
But Drummond to be clear, he was joking...

**Comment by dhh1128** [comment]
I will close this ticket as soon as I raise a PR updating the instructions.

**Comment by dhh1128** [comment]
Addressed in PR #114

**Comment by dhh1128** [comment]
Since PR #378 is merged, I am closing this ticket.

**Comment by swcurran** [comment]
Thanks, Daniel!
