### ISSUE TITLE
RFC 0067: Service Conventions - inline keys

### ISSUE THREAD

**Issue by mitfik** [hyperledger/aries-rfcs#117]
When DID resolver resolves DID url with service query it provides the block for whole service with keys references. 

Does it make sens that DID resolver can already compile all keys inline so the requester does not  have to resolve each key separately? 

Keep in mind that did resolver does not necessary need to run remotely it could run locally which resolve did document according [DID resolution spec ](https://w3c-ccg.github.io/did-resolution/#binding-architectures)

**Comment by peacekeeper** [comment]
I think this is a great idea, perhaps you also want to raise this as an issue on the DID Resolution spec so we can track it there? I can imagine this to be specified as an option for the resolution/dereferencing algorithm.

There may be features in JSON-LD that support this already. In terms of the underlying RDF graph model, selecting a service from a DID Document comes down to selecting a subgraph.

**Comment by swcurran** [comment]
This question belongs, as @peacekeeper notes, in the DID Resolution spec., with Aries implementing that spec. as appropriate.  Closing this issue as complete from an Aries perspective.

Please reopen if appropriate.
