### ISSUE TITLE
RFC 0116: Should IssuerDID be an optional parameter?

### ISSUE THREAD

**Issue by vinomaster** [hyperledger/aries-rfcs#120]
In order to ensure that the protocol remains flexible, we must consider the use case whereby a `evidence_access_request` is required without a dependency on a `Present Proof` exchange.

Such a situation, is hypothetically conveyed in the [Life Insurance Policy story](https://github.com/vinomaster/aries-rfcs/blob/master/features/0116-evidence-exchange/digital_notary_usecase.md#life-insurance-policy-didcomm-doc-sharing). Under this condition, the Verifier may not know the IssuerDID.

**Comment by vinomaster** [comment]
A subtle implication of the [Life Ins Policy](https://github.com/vinomaster/aries-rfcs/blob/master/features/0116-evidence-exchange/digital_notary_usecase.md#life-insurance-policy-didcomm-doc-sharing) story is that this protocol could be used at any point after a Pair-wise DID Exchange has been successfully established and is therefore in the [complete state](https://github.com/hyperledger/aries-rfcs/tree/master/features/0023-did-exchange#complete). 

However, even under this situation, one of the entities in the Pair-wise relationship would be the Issuer of KYC evidence and therefore the other entity would know the corresponding DID for this private relationship. Therefore, it should be possible for the Evidence Exchange Protocol to be used anytime after a DID Exchange has been completed. 

My suggestion is that no changes to the protocol are required (i.e.: Make IssuerDID optional) but a clarification in the protocol text is warranted.

**Comment by kdenhartog** [comment]
I linked some questions around this protocol in #121

I had some questions regarding this paragraph: 

> However, even under this situation, one of the entities in the Pair-wise relationship would be the Issuer of KYC evidence and therefore the other entity would know the corresponding DID for this private relationship. Therefore, it should be possible for the Evidence Exchange Protocol to be used anytime after a DID Exchange has been completed.

Are you expecting that the verifier, issuer, and holder will setup a n-wise relationship for this protocol? If so, that makes sense in terms of how the verifier would know about the private relationship. However, in the context of two independent (or even 3) pairwise relationship, I don't understand how this would work. As I interpret this the verifier couldn't discover the issuers DID Document and therefore couldn't discover the service endpoints or keys of the issuer. I think I may be misreading what you mean in this case though. Could you provide some clarification around what entity is doing which action?

**Comment by vinomaster** [comment]
@kdenhartog The point of the protocol is to ensure that the Verifier need not have a relationship with the Issuer. The Holder is the clue. The Holder has two private pair-wise relationships, one with  the Issuer and and another with the Verifier. The Holder uses the Request Evidence message flow to gather the needed data from the Issuer. With this in hand, the Holder can satisfy any Evidence Access Message Flow interaction with any Verifier. 

So effectively, if Alice gathers evidence from Issuer A in support of Credential A, then Alice can now satisfy evidence requests from Verifier B and Verifier C independently of any further interaction with Issuer A. 

Please also refer to the Interaction Diagrams as they call out which entity is doing what / when.

**Comment by vinomaster** [comment]
Resolved in PR #127
