### ISSUE TITLE
Should decorators be required?

### ISSUE THREAD

**Issue by kdenhartog** [hyperledger/aries-rfcs#126]
While it seems every mature implementation I can think of is using all of the decorators described, we don't have an explicit requirement for agents to understand them. What are some arguments for or against requiring that full and/or static agents be required to process decorators?

**Comment by dhh1128** [comment]
Agents *are* required to process decorators if the decorators embody a required aspect of a protocol that the agents claim to support. Otherwise, they are not. In other words, I don't think the requirement is tied to a generic rule ("you must support decorators") but to a specific one ("If you are supporting the Issue Credential protocol, you must support the ~attach decorator.")

**Comment by kdenhartog** [comment]
For the use case you suggested this makes sense in terms of how we're using them. What I had in mind was an optional decorator that could be used by any protocol. For example, I was thinking about the privacy ideas you brought up in the past to pad a message and thought, `~pad` may be a useful decorator for protecting against message size analysis.

The other one I had in mind was `~noise` which would be a Boolean off false or true and could be used to notify the receiver that while this message is semantically correct it should be ignored and was only sent to create "noise" to prevent traffic analysis.

Both are privacy enhancing options, but not really required like you originally suggested.  This definitely opens up a can of worms in terms of complexity of processing messages in strongly typed messages though so if we don't feel this is absolutely necessary at this stage I'm alright with that.

**Comment by kdenhartog** [comment]
I feel like this is still a good idea, but in an effort to make the protocol simple it should not be a requirement that all decorators MUST be supported. The two examples I provided might be good extensions that can be considered later. I'm going to close this.
