### ISSUE TITLE
0114: Identity for Protocol Test Suite

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-rfcs#139]
I think the concept of predefined identities provides a potential route for us to get around how we bootstrap communication of the protocol test suite and agents under test. If we had a predefined identity for the protocol test suite, tests can be conducted without first establishing a connection through DID exchange.

Especially looking for comment from @dhh1128 on this one.

**Comment by TelegramSam** [comment]
This helps the agent under test recognize the test suite. Can we use the same concept to help the test suite recognize the agent under test? So a pair of set identities?

**Comment by dhh1128** [comment]
Both of these comments seem reasonable to me.

We might want to use did:aries to create these identities. @llorllale

**Comment by TelegramSam** [comment]
Closed per discussion in Aries WG Call 2019-11-20.

**Comment by dbluhm** [comment]
(Captured in RFC 0270)
