### ISSUE TITLE
RFC 0037: pres req should clarify intent of verifier

### ISSUE THREAD

**Issue by dhh1128** [hyperledger/aries-rfcs#145]
This is somewhat related to terms of use, but may not be identical. Tagging @mikelodder7 , who knows more.

The scenario that triggered this issue was work on OIDC->VC bridging, involving @tplooker and @swcurran and others. The observation was: if an OIDC provider engages in a VC-based proving protocol with the express purpose of relaying info about the prover, from credentials to an OIDC relying party, then the prover ought to know that the information they're supplying is going to flow to the OIDC relying party; they should not assume the verifier they're talking to is going to keep the info to itself.

This is just one example of a broader phenomenon, though.

A presentation request should probably express the intentions of the verifier. How formally it should do so is a question. We could imagine extreme formalism, which is a non-repudiable commitment by the verifier to terms of use. Or we could imagine something very fuzzy, like just a string that says "I need this data just for my own curiosity." Possibly a very formal expression of intent should be a subprotocol, and not bog down this one?

The actual presentation itself could express the intentions (or, in the extremely formal view, the requirements) of the prover.

**Comment by llorllale** [comment]
@dhh1128 I also see this in the context of #142 and the point you raised there - the potential Introducer and Introducee both should be aware of the data flow

**Comment by tplooker** [comment]
I understand the intent here, however I feel its important to note that a lot of time the OP and RP to use the language of the VC-Authn-OIDC work, will in many cases be the same organization. In other cases, this may in fact be another entity where this form of data sharing declaration would be useful.

**Comment by kdenhartog** [comment]
Will this issue lead to changes in the message format? I'm trying to figure out if this is blocking the Status change.

**Comment by dhh1128** [comment]
I think we should merge the current PR #158, and then start working on a new RFC that updates the protocol to include terms of service from the prover.

**Comment by TelegramSam** [comment]
Closed per discussion in Aries WG Call 2019-11-20. Please reopen if this should not have been closed
