### ISSUE TITLE
Broken link: Indy Cloud Agent - Python

### ISSUE THREAD

**Issue by troyronda** [hyperledger/aries-rfcs#169]
In the [Implementations table](https://github.com/hyperledger/aries-rfcs/tree/master/features/0019-encryption-envelope#implementations):

https://github.com/hyperledger/indy-agent/python does not navigate. (If you want master branch then it is here: https://github.com/hyperledger/indy-agent/tree/master/python)

**Comment by kdenhartog** [comment]
Fixed in PR #181. Closing.
