### ISSUE TITLE
RFC 0075 Payment decorator doesn't account for fiat

### ISSUE THREAD

**Issue by mikelodder7** [hyperledger/aries-rfcs#205]
If the goal of this of RFC is to handle various forms of payment then we are missing a lot of information. This works for peer to peer payments like cash but in the real world that is not how payments work. 

There are actually 4 parties when it comes to payments: Payer, payer's issuing bank, payee's acquiring bank, and payee. With credit/debit cards, the payer authorizes the payee to charge his card. The payee passes the consent to charge to his acquiring bank which then passes it to the credit/debit card networks. The networks do some verification like fraud checking then pass it onto the issuing bank. The issuing bank checks the consent and releases the funds over the network back to the acquiring bank. The acquiring bank holds the funds until the payee fulfills his part of the deal. This can be selling something to the payer and must deliver the product to collect payment. Reimbursement is different because payee has already delivered something.

I think this is low priority right now for the spec but wanted to make sure that this portion is noted.

**Comment by dhh1128** [comment]
Since this was modeled on an existing WebPayments standard, I suspect we may be missing that extra data because it doesn't belong in the protocol. The decorator isn't proposing to consummate payment--only to report that it is required (part 1) and has been completed (part 2). It should already work for fiat, since that's what the WebPayments standard supports.

**Comment by swcurran** [comment]
I think the response from @dhh1128's is correct, and the question doesn't apply to the RFC 0075, the decorator. When we actually get to the point that we have a payment protocol, the issues raised will come out.

Closing. Please reopen if appropriate.
