### ISSUE TITLE
What is needed for a 1.0 release?

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-rfcs#207]
We've been adding features to ACA-Py and starting to think about what would be needed for a 1.0 release of the product. Per Hyperledger guidelines, that would mean the 0.8.0 would be API complete, and 0.6.0 would need to be functionally complete. 

What functionality is needed in a release for us to declare it 0.6.0, the first predecessor to 1.0.0?

## Questions and Comments

- At minimum, we think we need to have what we have today, plus the 1.0 version of Credential Exchange operating.

- Logically, you would have proof of interoperability via a run completed with the test suite, but at this point that would not show a lot.  Doable easily, but not particularly useful.

- A non-Indy implementation of credential exchange would seem like a reasonable bar to set, but that is out of our hands.  Note that I think credential exchange is needed, not just DID resolution, because Credential Exchange is the only thing in the application that uses public DIDs. Does the community think this is necessary?

- We could make the completion of functionality dependent on having the implementation of Aries core complete.  That makes sense, but is again out of our control, and seems to be some time away. Does the community think this is necessary?

What do others think about what functionality is needed to be on a path to 1.0?

**Comment by llorllale** [comment]
`aries-framework-go` plans to also have `present-proof` and `introduce` for the initial release. Other things are required that still haven't made their way into RFCs yet.

**Comment by swcurran** [comment]
@llorllale do you mean the initial release, or the 1.0 release (per the Hyperledger definition) or are those the same?  https://wiki.hyperledger.org/display/fabric/Release+Exit+Criteria

How do these impact (or not) `aries-gramework-go`:

- multi-VC Model support; will you support Indy proofs?
- I notice you didn't mention `issue-credential`. Will that be part of the initial release?
- The split of Indy/Aries
- Test suite status

Thanks

**Comment by kdenhartog** [comment]
Last I understood, we needed to meet the requires in the [proposal](https://wiki.hyperledger.org/display/HYP/Hyperledger+Aries+Proposal). I think @nage would be able to answer this question best.

**Comment by swcurran** [comment]
Good thought.  The laundry list is pretty long, but this one is
particularly interesting:

Other functionality that would be in scope for a 1.0 project release would
be a Decentralized Key Management Solution (DKMS) which would add key
recovery, social recovery, and wallet backup and restore functionality.
Much of this work would be based on the DKMS documents outlined in the
Indy-HIPE
dkms design folder.
<https://github.com/hyperledger/indy-hipe/blob/49fcd78883d38babe9c95a4e1d150969797cffa2/design/dkms/README.md>



That wording puts the bar for Aries getting out of "incubating" state
extremely high.  Not sure what it means for getting a product within the
project to the 1.0 level.  If that is the bar, we really need to slow down
our consumption of minor version numbers :-).

**Comment by swcurran** [comment]
Closing this issue.
