### ISSUE TITLE
RFC 0023 Should invitation allow for self-connection?

### ISSUE THREAD

**Issue by sklump** [hyperledger/aries-rfcs#215]
Not all connections have truly distinct endpoints (i.e., distinct data stores): in the degenerate case, a connection can be from an agent to itself; e.g., to allow self-issue of credentials. And it is possible for distinct service endpoints (e.g., distinct ports, distinct IP addresses to the same service) to map to the same data store. It is not possible to know without specification whether two distinct addresses correspond to the same data store for connection and service model records.

In the typical case where both ends of the connection have distinct records in distinct data stores, each step of the interaction can find the right record to reconstitute requisite artifacts from prior steps, add the incoming data to them and process to build out the next artifact (e.g., proposal/offer/request/issue). If both ends' connection records are in the same data store, the agent's lookup for its connection record will find two connection records where it expects exactly one and fail.

Two possible approaches suggest themselves.
(1) In the case where exactly two are found, the connection is a loop (instead of a line) and so the operation should discover which record represents which (nominal) side of the communication, and take info from each one as required and amend the correct record as it transitions service state. The friction here is that every service would have to do it.
(2) Acknowledge that a loop is a qualitatively different geometry than (but equally valid to) a line segment, and create exactly one connection record for such cases. The invitation would have to take a boolean to mark itself as an auto-connection: the friction here would be opening up and amending this standard (RFC 0023) that has implementations in the wild. To avoid breaking any existing implementations, the auto-connection flag should take default semantics of False. Service operation would find and amend the correct record in state transition because there would be only one.

**Comment by dhh1128** [comment]
This is an intriguing question, and my initial reaction is to say "of course, yes."

However, I seem to be missing a subtlety, because I don't see why we need any specialness at all to enable this. It should already be possible for an agent to create an invitation and send it to itself, and to play both parts in the resulting DID Exchange workflow. I can't think of a reason why this would work out of the box.

@sklump Can you explain why my naive assumption is untrue?

**Comment by sklump** [comment]
A Mr. StefanK on the rocket chat had some trouble to this end, and Mr. Nick Rempel addressed it with a filter that assumed the issuer started a credential exchange in the 0.1 protocol. I've also seen discussion about self-presentation re: BC gov indy-catalyst project, where the equivalent filter addresses it. But the 1.0 protocols (Aries#0036/37) allow either end to initiate, so this won't work for credential issue nor proof presentation. I will do some troubleshooting later today and hopefully identify what the problem is in greater detail, but my gut says that if both ends of a connection are in the same database, it breaks uniqueness assumptions about connection records and that is going to be bug factory across any service protocol.

**Comment by sklump** [comment]
Upon further investigation, there is a less invasive fix available. There is enough information, in principle, to get the right service record, even if the same data store hosts both ends of the interaction.
