### ISSUE TITLE
RFC 0020: DID Reference Changes

### ISSUE THREAD

**Issue by TelegramSam** [hyperledger/aries-rfcs#22]
The DID spec is evolving, and the DID deference example used in RFC 20 isn't going to be accurate. Current example:
`did:sov:123456789abcdefghi1234;spec/exampleprotocol/1.0/exampletype`
Likely new syntax:
`did:sov:123456789abcdefghi1234;service=spec/exampleprotocol/1.0/exampletype`

When should we make this change? What considerations are needed for the transition?

**Comment by peacekeeper** [comment]
+1 this ABNF change has been merged into the DID spec here: https://github.com/w3c-ccg/did-spec/pull/189

**Comment by dhh1128** [comment]
+1 to making the change
I say that we rev all Indy protocol versions 1.1 if they were at 1.0 as they move into Aries, and say that acceptance of them in Aries requires the new format at the same time they get the 1.1 version.

**Comment by tplooker** [comment]
I'd like us to make sure we follow [semver](https://semver.org/) conventions around versioning these message families, what would be the rational for bumping to 1.1 if the message type representation was also changing?

**Comment by dhh1128** [comment]
Good point @tplooker; maybe that resets everything to 0.9 with new message family identifier until accepted by the Aries community, then to 1.0?

**Comment by tplooker** [comment]
Yes I would like to be minor version (sub 1.0) until the community agrees as that allows minor version bumps to be breaking changes and stops us from eating through major versions until the protocols are stable

**Comment by tplooker** [comment]
We can proposed the current indy based message protocols as 0.1 or anything sub 1.0 and then iterate with new minor versions until we agree, then we can bump to 1.0

**Comment by dhh1128** [comment]
@tplooker FWIW the semver compliance goal you articulated is also formally written up here: https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0003-protocols/semver.md. So we should be following what we already said. Thanks for holding us to it. :-)

**Comment by llorllale** [comment]
I assume this change will propagate to all message type definitions.

**Comment by TelegramSam** [comment]
what timing should we effect for this? Should we do a blanket update of RFCs with the minor update? Should we wait?

**Comment by dhh1128** [comment]
I suggest that we update all of the version numbers asap, as one PR.

**Comment by TelegramSam** [comment]
Closing this in favor of switching Types away from DIDs
