### ISSUE TITLE
RFC 0104 usage scenario: Historization of the execution state of a business process instance

### ISSUE THREAD

**Issue by mwherman2000** [hyperledger/aries-rfcs#226]
...just sayin'.

Reference: https://github.com/hyperledger/aries-rfcs/tree/master/concepts/0104-delegatable-credentials

**Comment by dhh1128** [comment]
@mwherman2000 What is your recommended action to resolve this ticket? Should we update the text of the RFC to mention this use case? I would be glad of a PR from you so we get new contributors instead of me just updating the doc myself.

**Comment by mwherman2000** [comment]
...or do we start to build a list of use cases for a use case document somewhere?

**Comment by dhh1128** [comment]
That might be even better...

**Comment by swcurran** [comment]
Closing this issue based on inaction. The term in the title is not well-known, so I don't think others will be able to contribute to this.

Please reopen if there is more to do, or better, submit a PR to the RFC as discussed above.
