### ISSUE TITLE
RFC0028 - introduce: states

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-rfcs#227]
Request clarifications around the [states](https://github.com/hyperledger/aries-rfcs/blob/master/features/0028-introduce/README.md#states) for the `introduce` protocol:

**Introducer**
* There is no transition to the `delivering` state. I assume the text `if wait_count = 0, transition to "done" else to "arranging"` should instead read `if wait_count = 0, transition to "delivering" else to "arranging"`
* Is "send confirm" the action sending an `ack` to an introducee to let them know that their invitation was forwarded?
* Should we also allow for the introducer to receive confirmation that the introduction was arranged successfully (ie. the two introducees have completed did-exchange)?

**Introducee**
* `transition to "invited"` should instead read `transition to "deciding"`

**Comment by llorllale** [comment]
@dhh1128 ^

**Comment by dhh1128** [comment]
@llorllale I'm just noting that I've seen this ticket. Looks like most of your suggestions should be accepted without a lot of debate. I will work on updating the RFC as soon as I get some free cycles. If you are blocked by me, let me know.

**Comment by dhh1128** [comment]
I believe this is fixed now, in PR #229 . @llorllale , please confirm.

**Comment by llorllale** [comment]
@dhh1128 thanks!
