### ISSUE TITLE
RFC 0023: request documentation for connection~sig

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-rfcs#228]
@dbluhm @swcurran @TelegramSam @kdenhartog 

The `did-exchange` RFC's [`response`](https://github.com/hyperledger/aries-rfcs/tree/master/features/0023-did-exchange#2-exchange-response) message includes a `connection~sig` object for which I cannot find any proper documentation.

Is this `@type` spec'ed somewhere?

```jsonc
{
  "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/didexchange/1.0/response",
  "@id": "12345678900987654321",
  "~thread": {
    "thid": "<The Thread ID is the Message ID (@id) of the first message in the thread>"
  },
  "connection~sig": {
    "@type":"did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/signature/1.0/ed25519Sha512_single",
    "signature": "<digital signature function output>",
    "sig_data": "<base64URL(64bit_integer_from_unix_epoch||connection_attribute)>",
    "signers": "<signing_verkey>"
  }
}
```

**Comment by dbluhm** [comment]
https://github.com/kdenhartog/indy-hipe/blob/d421fc77bae87c780aad346d15c0c49939adc281/text/digital-signatures/README.md

Somehow this HIPE never made it into an RFC or I'm also not seeing it in the RFCs.

**Comment by llorllale** [comment]
Thanks @dbluhm 

@kdenhartog please advise: are we backing away from this spec? I noticed in the first snippet you posted in an unrelated issue [here](https://github.com/hyperledger/aries-rfcs/issues/133#issuecomment-530976685) that included a JWS as payload.

One thing I like about the `connection~sig` proposal is that it's all contained in the DIDComm msg (application layer). Sending DIDComm msgs within JWTs just starts "spreading" the claims between the JWT headers and the protocol-specific payload, complicating our software architecture.
