### ISSUE TITLE
Is the signers in the exchange response, expect multiple signers or one signer ? 

### ISSUE THREAD

**Issue by talwinder50** [hyperledger/aries-rfcs#240]
"connection~sig": {
    "@type":"did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/signature/1.0/ed25519Sha512_single",
    "signature": "<digital signature function output>",
    "sig_data": "<base64URL(64bit_integer_from_unix_epoch||connection_attribute)>",
    "signers": "<signing_verkey>"
  }

**Comment by llorllale** [comment]
@talwinder50 the `~sig` decorator is defined in [RFC 0234](https://github.com/hyperledger/aries-rfcs/blob/master/features/0234-signature-decorator/README.md). The [`ed25519Sha512_single`](https://github.com/hyperledger/aries-rfcs/blob/master/features/0234-signature-decorator/ed25519sha256_single.md) signature scheme uses only one key.

**Comment by swcurran** [comment]
Discussed on the Aries Working Group call on 2019.11.27 and the community agreed this issue can be closed.

Please reopen if you think this should remain open.
