### ISSUE TITLE
RFC 0036: Some questions/issues when implementing RFC in framework

### ISSUE THREAD

**Issue by tmarkovski** [hyperledger/aries-rfcs#241]
I'm trying to implement this RFC as part of the Aries Framework .NET and I'd like to clarify some of the points that I feel need to be clarified further. Instead opening an issue individually, I'll just list everything here. These are not huge issues, but some points of discussion I didn't have a chance to raise during the protocol discussion.

## Propose Credential should not specify cred_def_id

This seems to me not only unnecessary, but potentially conflicting. An issuer may have multiple definitions for the specific schema, each differentiating by tag. An issuer may use the tag field to track revocation registry state, as some implementations already do, which means the definition changes. It seems the holder should only care about schema_id and ask a credential from the Issuer based on that information only. The issuer can will then follow with an offer that matches the cred_def_id that makes sense.

**Proposed solution:** Remove "cred_def_id" from Credential Propose message or clearly mark as optional.

## Threading should not be optional.

Similar to the DID Exchange, thread decorator must be mandatory for the Credential Request and Credential Issue message. Credential Request must reference the Offer message in the Thread Id, and similarly, the Issue Credential must reference the Credential Request in the thread.
Without threading, there is no way for the Holder and Issuer to uniquely identify which Request and Offer they need to use when working with this flow in cases where multiple offers/requests exist from the same issuer. While this may seem like an edge case, it's very common when developing new systems or testing credential exchange.

**Proposed solution:** Add Threading decorator to (at least) Credential Request and Credential Issue message such that they reference unique thread within this flow.

## Credential request missing attachment id

Seems that the Credential Request message is missing an attachment @id `libindy-cred-request-0`

## Attribute names do not follow a proposed RFC on naming JSON fields

Three different methods are used for field names, I feel we should at least try to be consistent within the same protocol.

**Comment by kdenhartog** [comment]
I spoke with @tmarkovski about this at IIW and when looking back at it didn't feel like I had great responses to the questions he's listed above. I think it would be useful for us to document this better. If I'm remembering correctly too, changing the attribute names to be consistent within the same protocol would cause a breaking change. Would we prefer to create a new protocol for this since it's "Accepted" status?

**Comment by sklump** [comment]
Re: Propose Credential should not specify cred_def_id
"This seems to me not only unnecessary, but potentially conflicting. An issuer may have multiple definitions for the specific schema, each differentiating by tag. An issuer may use the tag field to track revocation registry state, as some implementations already do, which means the definition changes. It seems the holder should only care about schema_id and ask a credential from the Issuer based on that information only. The issuer can will then follow with an offer that matches the cred_def_id that makes sense.

Proposed solution: Remove "cred_def_id" from Credential Propose message or clearly mark as optional."

An issuer should have one cred def for a schema. The issuer should use the revocation registry tag to track distinct revocation registries.

A schema id and issuer DID could suffice, but both parties are using pairwise DIDs with no assurance of identity and so a bait-and-switch is possible if the proposal specifies only schema id. For example, the holder thinks he is getting a transcript from an accredited medical school but it is a fraud.

**Comment by tmarkovski** [comment]
> An issuer should have one cred def for a schema. The issuer should use the revocation registry tag to track distinct revocation registries.

I agree with the schema + issuer combination. Can you clarify why an issuer should have one cred def for a schema? There's so many use cases for multiple cred defs for the same schema - this is why libindy supports it.

**Comment by sklump** [comment]
I suppose I am only commenting from the prejudice of how we've used it and maybe our old assumptions in VON anchor design. The only cases I've thought of for multiple cred defs per schema and issuer are:
* change in revocability (in which case new creds ought to go on the latest capabilities)
* loss of private key (in which case new creds ought to go on the new replacement cred def).

I think I got this impression because the cred def tag came in shortly after revocation became available, allowing migration of existing cred defs to accomodate revocation support.

**Comment by dhh1128** [comment]
I am more or less aligned with @tmarkovski 's thinking here (that we should remove cred_def_id and instead specify schema + issuer). I agree with @sklump that multiple cred defs per issuer is going to be unusual for the foreseeable future. However, I think it's true that the issuer should be requesting a schema from an issuer, not a cred-def. The issuer should be able to change to a new cred def at any time without communicating that fact to potential holders.

**Comment by sklump** [comment]
From an implementation point of view, unless I have missed an update, an issuer cannot know what credential definitions against which it can issue credentials. Given a partial cred def id, there is no way to complete it as indy stands, without crawling the whole ledger for any possible matching cred def -- and the ledger can only grow in time.

A workaround could be to add a non-secret records in the issuer wallet every time it creates and sends a cred def to the ledger. This would invite divergence between implementations. It's a bit of a dilemma until some method to query the ledger like a wallet (à la WQL) comes into being.

**Comment by sklump** [comment]
Coming back to this, I don't think the spec should remove cred def id from credential proposal, but instead should support the "Original Six" indy restrictions:
* schema id
* schema issuer did
* schema name
* schema version
* cred def id
* issuer did.
Specify at least one and let the issuer match.

**Comment by TelegramSam** [comment]
@tmarkovski @sklump Any updates on this issue? Is more action needed? Can it be closed?

**Comment by sklump** [comment]
My opinion: kindly close it. Version 1.1 of the cred proposoal of RFC 36 incorporates all of this input.

**Comment by tmarkovski** [comment]
I'm agreeing with @sklump - this can be closed.
