### ISSUE TITLE
Correlate did-exchange request to invitation?

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-rfcs#242]
@dbluhm @TelegramSam @swcurran @dhh1128 

I wonder if implementations can benefit from having the `request` message include a reference to the `invitation` that it is responding to. This would simplify things a bit I think.

Correlating incoming `request`s to outgoing `invitation`s is useful for several things: logging, checking expiry, counting how many times the invitation was used, etc.

This correlation can currently be done by first having indexed the invitation with the `recipientKeys` included, of which there may be multiple. When receiving the `request` afterwards, the crypto layer would return the keys used to pack this message and the application layer would have to perform a reverse lookup to find the corresponding invitation.

I think an alternative to make this process straightforward is to simply include a reference to the invitation in the `request` message. The `invitation` already has the necessary characteristics to make this possible: it has an `@id` and the Sender's [requirements](https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0008-message-id-and-threading/README.md#message-id-requirements) for generating this ID include that it be "sufficiently unique" (UUID recommended). The `invitation` message should be indexable by its `@id` by its Sender. In the case of [implicit invitations](https://github.com/hyperledger/aries-rfcs/blob/master/features/0023-did-exchange/README.md#implicit-invitation) from public DIDs, the uniqueness of the invitation's ID is derived from the DID itself (see [example](https://github.com/hyperledger/aries-rfcs/tree/master/features/0067-didcomm-diddoc-conventions#service-conventions) in our diddoc conventions RFC).

Having the `request` message include an attribute like `invID` that would reference the invitation's ID would make the correlation more straightforward.

WDYT?

**Comment by dhh1128** [comment]
Isn't that what `~thread` is for? (The `id` of the invitation becomes `~thread.thid` in the request)?

**Comment by llorllale** [comment]
@dhh1128 from #208 I understood that the invitation is not part of any thread.

**Comment by dhh1128** [comment]
l left a comment over there.
