### ISSUE TITLE
Aries RFC 0035: @msg_catalog inconsistencies

### ISSUE THREAD

**Issue by devin-fisher** [hyperledger/aries-rfcs#245]
1. Still seems to use the old decorator tokenizing character '@' I think we currently reserve them for our JSON LD compatibility.
2 @msg_catalog is marked as being required but both the sample messages don't have one. Additionally, the comment field description has language that @msg_catalog is not require (eg. It is highly recommended that code and @msg_catalog are included)

**Comment by devin-fisher** [comment]
Pinging @dhh1128

**Comment by dhh1128** [comment]
@msg_catalog is an error. This has been replaced by ~l10n.catalog. Some of the samples show this; the verbiage does not. Thanks for catching the inconsistency. I will fix this when I get around to it--but if you are faster than I am, feel free to submit a PR.

**Comment by swcurran** [comment]
This was resolved in the recent #326 PR to this RFC.

Please reopen if this is still an issue.
