### ISSUE TITLE
RFC 0036: No negotiation possible in one of the holder cases.

### ISSUE THREAD

**Issue by KitHat** [hyperledger/aries-rfcs#262]
During #188 and #189 choreography diagram has been changed and as far as I see Holder can now begin with the CredentialRequest message. The following flow does not assume any negotiation for Issuer to refuse in credential issuance. It seems to be an error to me or at least not logical.

According to the current state of RFC Holder can start its flow by sending two different messages:
1) CredentialProposal -- and he will go into the negotiation process
2) CredentialRequest -- and Holder will oblige Issuer to issue credential he or she wanted.
And there is no way for Issuer to be transferred from Initial state when he or she receives the CredentialOffer message (in Issuer's flow such transition is present)

**Comment by dhh1128** [comment]
It sounds like the diagram isn't quite a perfect representation of the intent of the protocol, and maybe the diagram should be updated a bit.

**Comment by KitHat** [comment]
We had a conversation with @dhh1128 and I realised that there is no concern about starting with CredentialRequest. It should be enough to support uPort-style model. Maybe we should leave some marks about a protocol inside the attachment, e.g. in `mime-type` field? So we can distinguish different types of credentials and reject them if needed.

**Comment by swcurran** [comment]
Is it OK to start with a CredentialRequest with Indy because a
CredentialOffer is not required, or because the the agent can respond to a
CredentialRequest message with a CredentialOffer?  As I understand it, a
proper Indy CredentialRequest cannot be constructed without a
CredentialOffer.

**Comment by dhh1128** [comment]
Now that I think about it, there was a change introduced (in docs? in Ursa? In Indy?), whereby the issuer in anoncreds had to commit to a schema before the holder makes a request. But I don't know whether the Indy code in its current state embodies that constraint, or whether it's just an intention to introduce it from an idea described lower in the stack. So it's not clear to me whether Indy's ecosystem would require the CredentialOffer to be the starting point, or it could tolerate the CredentialRequest being the starting point.

**Comment by KitHat** [comment]
As far as I am concerned, Indy flow can be modified to start without CredentialOffer, but Holder won't be able to verify that Issuer has the Credential Definition. Right now it is not possible to start right with the credential request.
However, it should not be a constraint for this RFC -- we should make messaging protocol in RFC interoperable for all participants.

**Comment by swcurran** [comment]
Discussed on the Aries Working Group call on 2019.11.27 and the community agreed this issue can be closed.

Please reopen if you think this should remain open.
