### ISSUE TITLE
RFC 0250: will Rich Schemas also define scopes?

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-rfcs#263]
@brentzundel @ken-ebert

Schemas are part of a shared vocabulary between Agents that define the *what*. We also need enough richness in this vocabulary such that Agents can express the *how* (CRUD) - aka. scope. This would enable more complex scenarios where a Resource Owner/Data Subject is not the Holder of the credential/resource being requested but can grant authorization to access.

Will rich schemas include language to define scope?

**Comment by brentzundel** [comment]
I certainly think they could. The rich schema objects we're defining in Aries are being described from a verifiable credential standpoint, rather than a did-comms standpoint, but there is no reason the objects couldn't be used in that context.

**Comment by kdenhartog** [comment]
I've just merged the PR to make this an `Accepted` status and then realized this issue was open but stagnant. If things need to still be resolved then we should make a PR to revert the status back to proposed if they make normative changes.
