### ISSUE TITLE
In [AK]MS implementations, what is in export? / Connection record format and storage

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-rfcs#265]
The BC Gov team is working through some performance challenges in deploying two Aries agents messaging in a high volume scenario (millions of credential issuances in as short a period as possible - e.g. hours).  The addition of the tracking of Aries message protocol state significantly impacts performance. We're working through some tech spikes to understand the issue and potential fixes. In the course of that we have encountered what we think is an RFC issue that should be addressed by the community - the storage, format and portability of connection records and we wanted to get community feedback on how to move forward.

We think that for agent portability reasons, the "secrets" storage entities (ledger objects, DIDs, keys, credentials) **plus** connection records need to be part of the storage export can subsequently be imported into another agent.  We don't think other non-secrets data should be exported - notably, protocol state records.

If that is the case:

* all agent implementations should use the same data format for connection records
* an agent storage export should include connection records
* General non-secrets data should be considered "implementation specific" and should NOT be included in an agent export.

Currently, all implementations of Aries of which we are aware are using non-secrets storage for both connection state (e.g. the state of a connection following the execution of the connection protocol) and protocol state (the state of any messaging protocol).  We think that is going to create problems.

We are thinking:

1. We need to spend some community time defining a connection record data model.
2. We should move connection records into a place easily picked up by the export routine.
    - Perhaps into "secrets" storage
    - Perhaps there should be a third category of storage that is "portable non-secrets" data
3. We should formalize the records that will go into the export.

> Note - we see export/import as only for portability purposes. Backup and restore should be implementation specific, cover all stored data and support restore only to same the agent type.

**Comment by troyronda** [comment]
- connections also seem special to me.
- by “use the same data format for connection records”, did you mean specifically when exported? Of course, many implementations might always use that format but, of course, the most important moment is during export/import.
- i prefer to keep secrets segregated.

**Comment by swcurran** [comment]
It's clear that import/export-related RFCs are needed, and the questions raised in this issue will be addressed when those are created.

Closing this issue.
