### ISSUE TITLE
RFC 0211: routing shouldn't be exclusively key-focused

### ISSUE THREAD

**Issue by dhh1128** [hyperledger/aries-rfcs#274]
The way 0211 is currently written, all routing is specified in terms of keys. I think this is too narrow. It may be reasonable to do intra-domain routing from Alice's cloud agent to her edge agents using keys, but at least inter-domain routing from Alice's agency to her cloud agent will likely use DIDs.

@devin-fisher @TelegramSam

**Comment by kdenhartog** [comment]
Would it be a DID or would it be a DID-url? (DID with key reference) Is this something we want to specify the difference between?

**Comment by dhh1128** [comment]
It would be a DID. I am saying that when Alice wants to send to Bob, she routes to Bob's DID. She may *encrypt* for Bob's edge agent(s), but encryption and routing are not the same (though they are highly related).

I'm going to write some more about this logical difference in the new RFC about routing.

**Comment by llorllale** [comment]
@dhh1128 @devin-fisher @TelegramSam @kdenhartog was this topic discussed elsewhere? We share Daniel's concerns as well.

**Comment by llorllale** [comment]
The `to` field of the [`Forward`](https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0094-cross-domain-messaging/README.md#corerouting10forward) message accepts DIDs with and without key references. The route-coordination RFC seems to be misaligned with this fact.

Any updates on this?

**Comment by TelegramSam** [comment]
We went with keys initially, as allowing either plain DIDs or DID URIs (that point to keys) adds complexity. Now might be the right time to expand to something more expressive. We'll need to consider the solutions to the edge cases that this brings up.

**Comment by TelegramSam** [comment]
One complexity of using DIDs is that the list of keys in routing keys is used for encrypting messages. If we use DIDs, which key do we use during encrypting a message for that step? This is only an issue with Mediators (known to sender) and not an issue with relays (not known to sender).

**Comment by TelegramSam** [comment]
Important question: Should we leave it keys for now, and fix this in the DIF DIDComm WG work, or do we need to fix it faster for the Aries community? @dhh1128 @llorllale

**Comment by dhh1128** [comment]
I'd say let's work on it in the DIDComm WG, and if a specific need arises to do something sooner, we can also work on it in Aries. But let's not work on it in Aries until we know we need to.

**Comment by TelegramSam** [comment]
Continue issue here: https://github.com/decentralized-identity/didcomm-messaging/issues/26
