### ISSUE TITLE
RFC 0289: Trust over IP name seems to lack effective nuance

### ISSUE THREAD

**Issue by kdenhartog** [hyperledger/aries-rfcs#294]
The name Trust over IP always seemed like a poor name to me. It does little to indicate it's differences between things like federated identity systems, traditional PKI systems, or centralized identity systems. This lack of clarity leaves me with the question, are these systems not trusted at all or are we creating a false chasm by saying only our system is trusted?

With this in mind, I'd encourage us to find a different name. This name fails to meet the one thing that matters to me in a name which is that it's meaningful. In my opinion, TOIP lacks effective conveyance of the meaningful differences between the incumbent identity systems of today and the future identity systems of tomorrow. If I were to vote on a name I prefer, I would suggest decentralized identity. At least that aligns with the name "Decentralized Identity Foundation".

**Comment by swcurran** [comment]
Decentralized Identity (and Self-Sovereign Identity) constrain the use cases for the technology to identity. ToIP reflects that it enables authentic data, which helps with identity and covers use cases beyond identity. For use cases limited to identity, I think Decentralized Identity (or even SSI) is fine, but for the broader application, I think ToIP is much better.

You are getting data that you can that you can cryptographically trust, and you have higher level constructs that will let you know if you can trust if from a human perspective.

**Comment by kdenhartog** [comment]
Would the "scopes" in Open ID Connect that are signed with JWTs fall under the TOIP stack then because it's cryptographically "trusted" and RPs can trust the data from a human perspective also?

**Comment by peacekeeper** [comment]
I think it's a great idea to have a term which conveys the vision that this is broader than just identity.

However I also share Kyle's opinion that the differences between "trust" in ToIP and "trust" in traditional PKI etc. are not so clear. This question becomes more significant as we see elements of re-centralization added into the ToIP architecture, e.g.:

> ... governing bodies may outsource the operations and maintenance of a Peer-Net to Identity Utility Administrator, service providers that specialize in the implementation of governance frameworks at Layer One

If IBM hosts an entire Peer-Net or even multiple Peer-Nets, then how are the "trust" characteristics much different between ToIP and a traditional PKI?

**Comment by jljordan42** [comment]
I have "field tested’ this concept in dozens of contexts now and based on my experience thus far is it is very helpful in providing a construct to explain the vision to folks that are unfamiliar with our communities work whether they are technical or not. While I haven conducted analytical studies I can say that for the hundreds of people that I’ve presented to over the last months I’ve had no push back or confusion expressed to me regarding this term. 

The concerns being raised here have to do with choices in implementation and organization that will not be prevented by words but by actions. I am of course very concerned with facilitating the conditions for privacy respecting, personal agency enabling digital technology for our citizens and businesses. It will be the role of all us of us and, I think especially regulators, to strengthen the core concepts that are made possible by this emerging stack.

**Comment by jljordan42** [comment]
> I think it's a great idea to have a term which conveys the vision that this is broader than just identity.
> 
> However I also share Kyle's opinion that the differences between "trust" in ToIP and "trust" in traditional PKI etc. are not so clear. This question becomes more significant as we see elements of re-centralization added into the ToIP architecture, e.g.:
> 
> > ... governing bodies may outsource the operations and maintenance of a Peer-Net to Identity Utility Administrator, service providers that specialize in the implementation of governance frameworks at Layer One
> 
> If IBM hosts an entire Peer-Net or even multiple Peer-Nets, then how are the "trust" characteristics much different between ToIP and a traditional PKI?

Lets examine this concept of "decentralization" .... so far I’ve found discussion around this term to be somewhat unfocused. I think that what we really mean is shifting centralization ... we are shifting centralization to the person/organization/thing. The entity that is at the centre of its relationships. I am the holder of my relationships and they are centred around me. DIDComm is the core enabler of that. To me, that is the disruptor of the "account centric" computing model we’ve perpetuated since the mainframe era.

Of course this doesn’t mean that the rest of the stack is irrelevant and we should just let go of diversity in all the other layers ... but it does mean that the focus is on empowering the entity around which digital relationships are formed.

**Comment by jljordan42** [comment]
> Would the "scopes" in Open ID Connect that are signed with JWTs fall under the TOIP stack then because it's cryptographically "trusted" and RPs can trust the data from a human perspective also?
> 
> Additionally, when reading through the [Public Key Certificate](https://en.wikipedia.org/wiki/Public_key_certificate) Wikipedia page there are many ideas that resonate with ToIP. For example, [Root Certificates](https://en.wikipedia.org/wiki/Public_key_certificate#Root_certificate) are referenced as "trust anchors" a role that has been mapped onto a "web of trust" model in the ToIP ecosystem when they are supposed to mean different things.
> 
> Also worth noting I'm in huge favor of recognizing this goes well past the point of just identity. I focused on identity specifically because it's the paradigm we're familiar with. It's mainly so I don't run off and propose wild ideas outside the scope of what we're focusing on as I've done in the past. I figure once we are delivering tangible value (e.g. a VC ecosystem exists) - then it's worth expanding the scope to the variety of cool capabilities that can be delivered.
> 
> Some other ideas worth considering that I believe head in the right direction:
> 
> * Verifiable Data Ecosystem
> * Verifiable Compute Ecosystem
> * Democratic Data Stack
> * Open Data Stack
> * Decentralized Democratic Data Ecosystem
> 
> These are just a few ideas off the top of my head. I doubt any of them would make it passed a first round straw poll. Even more so, I probably wouldn't even vote for the first 4 of them because they don't convey the differences between the two systems. With the last one I think it starts to convey the meaning better, but it seems rather bland in my opinion. The one other pro I liked about it was the alliteration of it.

It makes sense that there are similar constructs and concepts between systems like PKI and Trust over IP ... we are observing and participating in an architectural innovation (https://www.researchgate.net/publication/200465578_Architectural_Innovation_The_Reconfiguration_of_Existing_Product_Technologies_and_the_Failure_of_Established_Firms). 

Quick reference definition from Oxford — An innovation that creates an improvement in the ways in which components, at least some of which may not in themselves be innovative, are put together.

By in large the technology we are employing has existed for some time. What is novel and powerful is the overall arrangement of the various components that we now can express succinctly as this proposed stack. 

So, seeing familiar concepts and so forth is expected and not a reason in and of itself to be concerned. Again, I believe it will be the actions that are taken going forward that will be the ultimate arbiter of our success in establishing the vision of the citizens of the world being being able to live, work and play in the digital world with the confidence that their relationships are theirs and theirs alone.

**Comment by peacekeeper** [comment]
> Of course this doesn’t mean that the rest of the stack is irrelevant and we should just let go of diversity in all the other layers ... but it does mean that the focus is on empowering the entity around which digital relationships are formed.

We all share that vision to put persons/organizations/things at the center of their relationships, and ToIP is a powerful architecture for enabling that. But if Layer One is not decentralized and diverse, then that vision is at risk, because all the DID resolution, DIDComm, agents, credentials, frameworks etc. you build on top are constrained by a trust model that is still the same as that of traditional centralized or federated systems. Not saying that those trust models are necessarily bad, but they don't REALLY put persons/organizations/things at the center.

Commit https://github.com/hyperledger/aries-rfcs/commit/5bd37aa3bffa27fac06df781d8ca21a114b5e464 - which suggests that a Peer-Net could be operated by a service provider - is the latest of a series of attempts to push into that direction.

One of the powerful aspects of the ToIP (and DID) architecture is that you can choose which DID methods or Peer-Nets you want to use. It has been argued that this is itself a form of decentralization. So for example, I suppose a ToIP Metasystem Governance Framework could define whether or not a Facebook DID method or an IBM-operated Peer-Net should be considered trusted.

**Comment by smagennis** [comment]
I'm super glad this RFC came to my attention. I've been working on something similar as a vehicle for c-level conversations and I like a lot of the content I see here. I strongly feel now is the time to produce material that fills the gap between "Identity can do really cool stuff" and "elliptic curve cryptography."   My working thesis is roughly that the internet has got a decent bead on identity and security as exists between endpoints (IP addresses, certs, etc), what is fundamentally lacking is the ability to adequately and systemically discern who it is the endpoints are working on behalf of. I actually favor the phrase 'Identity over IP.'  The phrase can cover a lot of use-case ground and focuses the attention on the elements necessary to know and trust the entity that is compelling the digital components to do what they do. Honest users, bots and stolen identity all look the same to a network endpoint.

**Comment by talltree** [comment]
@smagennis I too like "Identity over IP" but the reason we named this stack "Trust over IP" (actually, John Jordan came up with the name and the other authors agreed) is that, as you say, it's ultimately not about identity but about achieving digital trust. 

And, to pile on to John's point about how well it works in actual conversations teaching people about this space, so far my results have been stellar. When you take the time to explain the whole stack, people really get it.

And, to address something mentioned in another issue, the governance half of the stack is every bit as important as the technical half. That's what makes it a "whole product" that can succeed at solving a long-recognized Internet-wide problem when all the technology-only solutions have so far failed.

I'd be happy to show how I present the stack on an Aries community call if it would help—I can do the whole thing in <10 mins.

**Comment by smagennis** [comment]
What resonates with an audience and helps gets the point across is what is best and I have to admit "ToIP" flows really nicely. Retail banks, for example often say they are about trust, and they are, but more fundamentally they are about deposits and loans. Same with transacting commerce on the internet; it is all about trust but more fundamentally it's about exchange of value. My point is that this trust stack is more fundamentally about knowing whose bidding the networked digital minions are doing.

WRT governance, you know I'm totally on the same page. I do think it would be good for the concept of reputation to be more prominent in the narrative. I suppose it is implied that a trust anchor, governance body, or for that matter legal system / government needs to have a better than neutral reputation to be, and remain viable. Just a suggestion to bring out the importance of reputation (ok, and the option for meaningful recourse) as the engine that keeps trust going.

**Comment by kdenhartog** [comment]
I understand what you're saying about renaming it seems counterproductive from a marketing perspective. That's definitely an important consideration. What I brought up originally though is does this name differentiate between itself and other solutions, or is it not intended to be? If it's not intended to differentiate then should the stack account for these systems as well? Based on what I know about the stack, I would say the TOIP stack is intended to be different and not include old systems like CA-based PKI, OIDC, PGP systems, and other methods that are considered different systems but still provide "trust over IP" in various different ways. 

Essentially what I'm saying is "Trust over IP" seems like a class of protocol stacks, systems, and other data exchange methods that are trusted today, but can be improved. However, what I gather from this name is that TOIP is the only trusted system on the internet and I don't think that's the claim we're trying to imply.

**Comment by smagennis** [comment]
I think the claim that is being / should be made [ *****keep me honest here*****] is  that there isn't currently any set of standards, protocols, etc for the internet that systemically address the issues of: unequivocally recognizing who is on the other end of the wire causing / invoking / initiating the actions of code AND in some methodical way evaluating the trustworthiness of said entity at the other end of the wire. I believe that DiDs and VCs close that gap and allow digital systems to bring humans, not just network endpoints into design conversations is a standardized and meaningful way. There are lots of other trust perspectives related to the internet, but I think this one is novel and important. 

Also, I believe in an extreme scenario, that one could have a DiD that has no attributes other than a unique id, that could build meaningful trust over time with another party. The downside of having no attributes though is that it kinda limits the ability for recourse if that trust ever fails ( yet another topic I'm passionate about elevating)

**Comment by jljordan42** [comment]
> One of the powerful aspects of the ToIP (and DID) architecture is that you can choose which DID methods or Peer-Nets you want to use.

Yes I think this is an important point. ToIP isn’t prescriptive...just as the OSI 7 layer model for communications was not prescriptive on how it was implemented.  Communities be they societies, governments, book clubs or what have you will decide on their governance models and what they consider “trusted”.  I believe we are laying out a model that can be helpful in communicating, constructing and evaluating digital systems where relationships are the core building block. Ultimately we can’t prevent bad things from being done ... as societies/governments we build roads, we have governance over them (laws, regulations, etc) but bad things still happen on them. If unfortunate things happen hopefully there can be changes to the tech (better asphalt) or changes to the rules (slower speed limits) that can help participants move towards more desirable outcomes.

**Comment by trbouma** [comment]
Perhaps, "Trust Anchor Protocol"? 

Similar in nature to "Trust Anchor Management Protocol" (TAMP) below:

https://tools.ietf.org/html/rfc5934

"TAP" may be a good choice because there are a lot of parallels to Border Gateway Protocol (BGP) that enabled the internet to scale, but is relatively behind the scenes. TAP would be the same thing, that allows two endpoints, or more, to facilitate trust between each other.

**Comment by kdenhartog** [comment]
Does anyone know how we refer to the combination of "TLS protocol + List of Certificate Authorities"? I've always thought this was just called [public key infrastructure](https://en.wikipedia.org/wiki/Public_key_infrastructure). Isn't what we're defining just a new form of PKI? Could we call it VC based PKI, Blockchain based PKI, or dPKI at least in technical forums? Then if people want to market it as TOIP or some other name it allows for accurate discussions in technical communities while still allowing marketing to have a cool new spin to sell. This is similar to how "browser" is the layman's term for "user-agent".

**Comment by kdenhartog** [comment]
While I think we got closer to what I was after with PR #411 I still don't feel satisfied with the usage of TOIP for the reasons stated above. I'm okay with laying this issue to bed though as it hasn't had discussion on it in awhile and those who use it won't be stopped by this and those against it (myself included) will use other language to describe things outlined in this RFC>
