### ISSUE TITLE
RFC 0289 Layer 3 versus Layer 4 concerns.

### ISSUE THREAD

**Issue by trbouma** [hyperledger/aries-rfcs#303]
In Layer 3,  as currently specified, the last sentence: "They can also specify business models, liability frameworks, and insurance models" should be the concern of Layer 4.

Further, "Credential Governance Frameworks" should specifically focus on the "correctness" of the credentials (issuance, verification, etc.). Anything to do with business models, liability frameworks, and insurance models should be dealt with in Layer 4 governance.

Finally, Layer 3 should be primarily concerned with "interoperability", while Layer 4 should be primarily concerned with "recognition" and/or "acceptance".

**Comment by talltree** [comment]
@trbouma I think we may have slightly different understandings of Layer 4 governance frameworks (GFs). The way I would put it is this: Layer 4 GFs specify interoperability at a metasystem level, i.e., interoperability rules that apply to all the Layer 3, 2, and 1 GFs that operate inside that specific metasystem. While this absolutely can (and often should) include business models, liability frameworks, and insurance models for the metasystem as a whole, it doesn't preclude more specific business models, liability frameworks, and insurance models also being defined within lower level GFs.

For example, one Layer 1 DID network could be a permissionless blockchain supported by a cryptoeconomic token, another Layer 1 DID network could be a permissioned ledger with a different cryptoeconomic token, and a third Layer 1 DID network could be a permissioned ledger without a token. All three could have their own Layer 1 GFs, and all three could interoperate inside the same Layer 4 GF.

The same could apply to Layer 2 or Layer 3 GFs—they could all interoperate within the same Layer 4 metasystem GF if it helps provide the overall interoperability they are seeking.

Make sense?

**Comment by trbouma** [comment]
@talltree I believe our different understanding might lie in how the different layers interact in terms of governance. For example, Layer 4 might use, but not necessarily 'govern' (just simply use) one of the lower layers. So I think that each layer can have its own business models, liability frameworks, insurance, etc, that are specific to that layer.

From my perspective, these layers need to be as self-contained as possible. If any one layer fails (the specific GF for that layer), it should be able to be switched out, with minimal or no disruption to the other layers.

**Comment by trbouma** [comment]
s Looking at the diagram again, Layer 4 maybe is not about "Governance Frameworks" but rather about "Acceptance/Recognition". Governance frameworks (ability to make, change, enforce rules) seem to exist at the different layers and specific to each layer.

So, for each layer, the primary concern:

Layer 4: Acceptance/Recognition
Layer 3: Credential Exchange
Layer 2: Communications
Layer 1: Ledger (or State)

(Governance frameworks at all layers)

**Comment by swcurran** [comment]
Over to you @talltree to decide how to resolve this?  

My $0.02CDN.  I like the idea of Layer 4 being something other than "governance framework" since we agree that is the parallel stack and governance applies at all layers.  Not sure of the best term, but I'm OK with what @trbouma has proposed.

**Comment by swcurran** [comment]
Per Aries WG Meeting 20200805 - closing.  Addressed in ToIP.
