### ISSUE TITLE
Nonce usage while signing

### ISSUE THREAD

**Issue by lovesh** [hyperledger/aries-rfcs#304]
As described [here](https://github.com/hyperledger/aries-rfcs/blob/master/features/0234-signature-decorator/ed25519sha256_single.md), `sig_data` should be created by first prepending a 64 bit value to the message, i.e. `64bit_integer_from_unix_epoch`. What is the need of this 64 bit value? It looks like you want indeterministic signatures but why?

**Comment by kdenhartog** [comment]
This RFC was a work in progress that we're opting to deprecate in favor of using JWSs. I just haven't gotten around to updating stuff yet.

**Comment by swcurran** [comment]
@kdenhartog - can this be closed?  Looks like the two of you agree.

**Comment by kdenhartog** [comment]
yup. thanks for checking I'll close it now.
