### ISSUE TITLE
Strategy for Trouble Free string migration

### ISSUE THREAD

**Issue by TelegramSam** [hyperledger/aries-rfcs#318]
We have two issues right now that require replacing string constants. One is the message type URI, and the other is the service type in DID Documents. There are two strategies for this, complex/low coordination or simple/high coordination.

### Complex / Low Coordination
Modify inbound messages / DID Docs to convert the old to the new. 
Remember which format was used.
Send out whatever format was used inbound.
_Sync with community_
After transition period, remove conditional processing and only use and accept new.

### Simple / High Coordination
Modify code to accept old and new.
_Sync with community_
Modify code to send new
_Sync with community_
Remove accepting old.

Both strategies work, with a complexity / community sync tradeoff.

I'm in favor of the simple / community sync approach. We can easily agree on target dates in a meeting, and the work to support each jump is very low.

Thoughts and Opinions?

**Comment by dbluhm** [comment]
Context: #317

**Comment by dhh1128** [comment]
I also prefer your second option.

**Comment by swcurran** [comment]
I prefer the first option for a couple of reasons.

I believe it's going to be a common pattern vs. a one time thing, and so we
should support the pattern, not the event.  The pattern is that each
implementation will have to track at different levels (a connection, a
thread, a message) attributes that will affect interop. Let's get that
implied.

We are already of a size that coordinated updates (e.g. not using
deprecation) is frustrating. It's not sustainable if we add even a more
implementations.  We have to allow builders to upgrade independently. I'm
all for "strongly encouraging" updates, but not forcing/coordinating them.

**Comment by swcurran** [comment]
This was discussed on the Aries Working Group call 2019.11.27. No agreement was reached, and it was agreed that we should discuss this further at the connectathon.  I've proposed a couple of sessions where Aries agent builders would discuss common issues, and this seems like one of the more significant issues for builders.

**Comment by TelegramSam** [comment]
This was discussed at the connectathon with agreement. I will write up an RFC that details the process flow.

**Comment by TelegramSam** [comment]
RFC Created: https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0345-community-coordinated-update/README.md
