### ISSUE TITLE
RFC 0036: Ack on receipt or acceptance?

### ISSUE THREAD

**Issue by sklump** [hyperledger/aries-rfcs#329]
If an issuer includes `~please_ack` in its credential-issue message, the diagram in RFC 0036 implies that the holder sends ack on acceptance (i.e, holder saves credential). But the default semantics of the decorator apply to the credential-issue message itself, not the credential it contains, implying that the holder owes an ack on receipt, whether the prospective holder saves the credential or not.

I'm inclined to think that the picture is closest to the design intent and hence the ack should follow on storage.

Note however that both the text of RFC 0036 and the example of RFC 0317 imply ack-on-receipt, even if the holder ultimately decides not to save the credential. It's a dilemma.

I think a key question is this: are credential-received, credential-saved, and credential-acked truly three distinct states? If not, how many distinct states do they represent?

If we can model them as all distinct states, the issuer ought to ask for acknowledgement on storage; i.e., `{... "on": ["credential_stored"]}`. I don't think it's of interest to the issuer to receive multiple acks for one credential issue (i.e., on receipt and storage both). Just my initial prejudice. If that's correct, then the text of RFCs 36 and 317 ought to reflect the exact semantics and I'm happy make such proposals if I get a nod here.

**Comment by llorllale** [comment]
I believe protocols should adopt `ack` wherever appropriate and should specify how it drives state transitions. `~please-ack` seems an unnecessary complication and protocols should not rely on it.

Reference: #306

**Comment by sklump** [comment]
Regardless, Aries RFC 36 https://github.com/hyperledger/aries-rfcs/tree/master/features/0036-issue-credential#issue-credential calls for please-ack decorator inclusion at present, so although I believe there is something to this argument, it is a separate (broader) topic.

**Comment by sklump** [comment]
A working prototype using issuer explicit please-ack on credential acceptance appears in https://github.com/hyperledger/aries-cloudagent-python/pull/278.

**Comment by swcurran** [comment]
We're planning to have a run through of this issue on the Aries WG call tomorrow - US Afternoon.

On @sklump's original question - I think it is up to the holder to decide if/when to respond to the `~please_ack`, and IMHO, it should be done at the completion of the processing of the credential.

The sender of the `~please_ack` must realize that the responder may not support the decorator, may choose to ignore it and may choose when to respond. That is further complicated by a responder choosing to answer immediately on receipt of the message (e.g. before it is delegated to the message's handler) or within the handler (if the handler has adopted the `ACK` message).

We need to address the difference in the 0036 picture (an explicit `ACK` from the holder at the end of the protocol) and the text, which says "only send an ACK if the issuer asks for it via a `~please_ack`".  In ACA-Py, it's been implemented as the picture shows, but we can update that if necessary. Alternatively, we update the RFC to 1.01 and remove the reference to the `~please_ack`.

**Comment by dhh1128** [comment]
>I think a key question is this: are credential-received, credential-saved, and credential-acked truly three distinct states? If not, how many distinct states do they represent?

There is no guarantee in this protocol that a credential will be saved, ever. The goal of the protocol is to *issue* a credential, not to make sure it gets saved in the holder's wallet. (I know, those are closely related. I'm splitting hairs. But still...) What the holder chooses to do with the credential after it's received is out of scope. Therefore, even if `credential-saved` is a state for a particular holder's impl, it's not a state that the other party in the protocol can reference. The ack has to be associated with the receipt of the message that carries the attached cred; any greater precision (before or after save to disk) is not supported by the protocol. If I were implementing the protocol, I'd probably react to ~please_ack after saving to disk (or at least, after making sure I could parse the attachment and it looked like I expected, so I knew I wasn't going to return an error instead). But  some other impl could make a different choice. The ACK is proof that the credential-bearing message arrived and was seen/processed in some way--nothing more.

**Comment by swcurran** [comment]
We didn't get to talk about this on the Aries WG call last week (ran out of time), but my $0.02CDN after thinking about it a bit:

- I'd like to drop other than `"on": "receipt"` and `"on": "outcome"` from the ~please_ack RFC, and get the RFC accepted.
   - for example, remove the mention in the RFC of every n hours as a possible value of "on"
   - other features can be added in later versions.
- Define that the scope of the ~please_ack is just the current message (e.g. doesn't affect other messages)
- Be explicit about the meanings of what the "on" value:
   - receipt: message has been received, no processing done. Typically used when there is likely to be a delay between the receipt and response to a message - much as chat apps use to indicate received.
   - outcome: at the end of the processing of the current message.  Used when there is no implicit or explicit ACK at the end of a protocol, such as we (we might) have with 0036.
- For 0036 I'd like to drop the explicit ACK from the holder and make it optional at the request of the issuer, as is described in the text.
   - We would need an update to the picture to clarify that.
- Add to the 0005 Ack RFC that all protocols should not error on receipt of an Ack or a Problem Report.

Feedback welcome - that proposal still has some ambiguity to be eliminated.  This discussion shows how we need to be a tighter in defining our RFCs as we transition from proposed to accepted.

**Comment by sklump** [comment]
(edit: 0005 Ack RFC -> 0015 Ack RFC)

**Comment by andrewwhitehead** [comment]
It bothers me having an ACK that only indicates that the message was received, not that it was fully validated and (at least initially) processed. The agent could conceivably crash and lose the message between sending this ACK and processing it. Asking for such an acknowledgement seems like an aspect of the message transport, and having that *exclusive* of further acknowledgements doesn't seem right, because the sender may want both.

**Comment by swcurran** [comment]
Agreed that the sender could want both and as the ~please_ack is currently defined, it supports having both requested.

When the receipt ACK is sent is (I think) up to the implementation. Could be sent in the dispatcher (e.g. the thing that first decrypts the messages) when it sees the ~please_ack:receipt, or by the handler for the message type.  Not sure if that should be defined in the RFC or left to implementations.

The idea of there being a transport level ~please_ack mechanism is (I think) a new idea that could be explored.

**Comment by swcurran** [comment]
Per discussion on Aries WG call 20200108, we're going to close this call. Some clarifying comments maybe added to the RFC to clarify that the implementation can decide when to send the ACK, with the understanding that the ACK tells the issuer that all is well, and the issuer need not track the protocol state any further.  Other topics raised in the discussion are open elsewhere - notably the discussion on `~please_ack` that now is in it's own RFC.

Please reopen if we missed anything that remains open.
