### ISSUE TITLE
Does the requirement of ack in a protocol make it synchronous?

### ISSUE THREAD

**Issue by kdenhartog** [hyperledger/aries-rfcs#331]
This question is intended to align my thinking a bit better. If a protocol requires ack messages are used throughout the entirety of a protocol does that make it fully synchronous or are there other requirements as well? Additionally, would we consider the protocol still async if only the first message sent is acked, but the rest of the messages used in the protocol have no requirement around the usage?

**Comment by swcurran** [comment]
Not sure about the context of this question.  Here are my thoughts.

There are only two ways that a protocol can have an ack messages are used through the entirety of the protocol:

- The protocol is designed to have explicit ACK messages
- The participants in an instance of the protocol adds the `~please_ack` decorator to all of the messages.
   - Even then, the other participant may not support `~please_ack`, may choose to ignore it, and may choose when to send the `ack` - e.g. either on each message or at the end of the protocol.

Regardless of the mechanism, I don't think it changes any protocol to be "synchronous", which to me implies blocking.  The original message and an ack for that message are still separate messages and non-blocking.

Are you thinking of some other context when asking this?

**Comment by kdenhartog** [comment]
For context: this was to align my understanding of the requirements of "synchronous" protocols which I've heard used a lot outside our ecosystem, but very little in our ecosystem because we tend to operate in an async format. I realized that it's possible for us to make "synchronous" protocols on top if a protocol author chose to. 

I didn't have a usage for them at this point, more just exploring the possibility and trying to map language outside the ecosystem with how we may take similar approaches in the ecosystem later. My thinking is that this can be closed next week as I doubt this will end up making a change to an RFC and the discussion will be saved once it's closed for people to search later.

**Comment by llorllale** [comment]
If by "synchronous" you mean "in the same session through which a message was received" then the default answer (so far) is no. (see the [`~transport`](https://github.com/hyperledger/aries-rfcs/blob/527849ec3aa2a8fd47a7bb6c57f918ff8bcb5e8c/features/0092-transport-return-route/README.md) decorator)

**Comment by kdenhartog** [comment]
We discussed this on the 12/12/19 Aries call and came to a conclusion that this is no. It’s been agreed that this doesn’t meet the needs of an “synchronous” protocol. This is because acknowledging a message was received does not provide the guarantees that are typically associated with synchronous, making this question orthogonal.
