### ISSUE TITLE
RFC 0036: How do you start the protocol from a request-credential message?

### ISSUE THREAD

**Issue by DRK3** [hyperledger/aries-rfcs#336]
The [issue-credential protocol](https://github.com/hyperledger/aries-rfcs/tree/master/features/0036-issue-credential) states that credential issuance can begin with the holder sending a request-credential message. However, the details of how this should work are not present in the RFC. It generally seems to assume that Hyperledger Indy is being used, which doesn't support starting from a request-credential message.

My question is: how do you start from a request-credential message if you're not using Indy? My idea for this is as follows:

We could add the fields from the propose-credential schema to the request-credential schema and make them optional. Namely:

* credential_proposal -- an optional JSON-LD object that represents the credential data that Prover wants to receive. It matches the schema of Credential Preview.
* schema_id -- optional filter to request credential based on a particular Schema. This might be helpful when requesting a version 1 passport instead of a version 2 passport, for example.
* cred_def_id -- optional filter to request credential based on a particular Credential Definition. This might be helpful when requesting a commercial driver's license instead of an ordinary driver's license, for example.

The usage of these fields will depend on whether this message is intended to start the issue-credential protocol, or whether it's in response to an offer-credential message, both of which are allowable flows:

* If this message is intended to start the protocol: The credential_proposal, schema_id and cred_def_id fields should be used in the same way as they are for a propose-credential message.
* If this message is in response to an offer-credential message: The credential_proposal, schema_id and cred_def_id fields should not be used.

I look forward to hearing your thoughts on this.

**Comment by swcurran** [comment]
The intention of the RFC was that the verifiable credential specific data would go in the attachment. So if you are not using Indy and you are issuing some other type of credential, you would have enough in the attachment such that the issuer would know the type of credential being requested and how to process the data in the attachment.

Is that sufficient for your use case?

**Comment by DRK3** [comment]
Thanks for the quick response Stephan!

let's say that I'm using verifiable credentials. Does this mean that I could put credential_proposal, schema_id, and cred_def_id into the attachment? If so - what does this mean for interoperability? Since that isn't explicitly in the spec, would other agents know to look there? Assuming that verifiable credentials are being used, how might you expect a request-credential attachment to look like?

**Comment by swcurran** [comment]
Things like schema_id and cred_def_id are specific to certain implementations of verifiable credentials (notably, Indy), and are not used by others.  So even though you are using verifiable credentials, the data and metadata might be different between implementations (e.g. JSON-LD-based, JWT-based and ZKP-based verifiable credentials).

The idea behind using ~attachment in these protocols is because the messages are essentially the same regardless of what verifiable credential implementation you are using, the data (and metadata) is not.  The ~attachment hides the data differences between the implementations, while retaining the message flow.

This is discussed in this section of the attachment RFC: https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0017-attachments/README.md#messages-versus-data

Does that make sense?

**Comment by DRK3** [comment]
Perhaps something that would help clear things up for me is if you could explain why the propose-credential schema has credential_proposal, schema_id, and cred_def_id fields while the request-credential schema does not.

**Comment by swcurran** [comment]
Welllllll.....that's a good question.  I think it's an inconsistency in the RFC.  I think those things are indy specific, and so should not be there.  So I'm not much help on that point.

Perhaps others could weigh in at this point.

**Comment by TelegramSam** [comment]
Discussed in WG Meeting 19 Feb 2020. The 1.1 RFC needs a note that this is a problem and a good target for fixing in the next version.

**Comment by swcurran** [comment]
Resolved in v2.0 of the issue credential protocol.  Closing this issue.
