### ISSUE TITLE
RFC 0270 Interop Test Suite - Pluggable Backchannels

### ISSUE THREAD

**Issue by TelegramSam** [hyperledger/aries-rfcs#337]
The [Backchannel section of the Interop Test Suite RFC 0270](https://github.com/hyperledger/aries-rfcs/tree/master/concepts/0270-interop-test-suite#backchannel) roughly defines the format of a backchannel used during testing.

We (Daniel Bluhm and Sam Curren) propose changing this design to allow for pluggable backends. The test suite will provide an Abstract Base Class. Backends can be built to implement the base class, and communicate with the agent under test. To enable testing, Agents will either need to support the communication of an existing backend or add a custom backend.

I anticipate the creation of a few backends, but not many, as it will often be easier to use an existing backend and corresponding communication than create both.

This adaptation can allow the Aries community to use a common test suite without reaching an agreement on a single backchannel protocol. 

One side effect of this model is that one of the backends can be a _manual_ backend, displaying instructions for a person to complete the test with manual interaction. This manual mode is obviously not helpful for automated testing but can be helpful during the development of both agents and tests.

An attempt to show this approach is contained in [this PR](https://github.com/hyperledger/aries-protocol-test-suite/pull/21).

**Comment by dbluhm** [comment]
Given conversations at the Connectathon, I think it's clear that we have not yet reached a final decision on exactly how the Backchannel should operate. As an intermediate solution to remove blockers on test development, I'd like to propose that we go ahead with hyperledger/aries-protocol-test-suite#21. By merging that PR, we can temporarily postpone the need to make a final decision on Backchannel details and explore potential solutions in code. Meanwhile, the writing of tests can proceed unhindered.

cc @dhh1128

**Comment by dhh1128** [comment]
I really don't like the code moving away from the RFC. I feel like it's a disaster waiting to happen. However, I recognize the pragmatic reality, so I am supportive.

**Comment by swcurran** [comment]
Discussed on Aries WG call on 20200108. We decided for now to just move forward with the merging of the Aries Test Suite PR (FYI @dbluhm ) and that a note will be added by @swcurran to the RFC to say that this is being tested and may result in a further change to the RFC.

Closing this issue for now, trusting the changes to be done. Please reopen if appropriate.
