### ISSUE TITLE
RFC 0334: optimize repeated envelopes

### ISSUE THREAD

**Issue by dhh1128** [hyperledger/aries-rfcs#341]
If I insert a message into envelope 1, and then insert envelope 1+message into envelope 2, and then insert envelope 2 into envelope 3, I don't want to repeatedly re-encrypt. The only thing I need to re-encrypt, after the first envelope wrap, is the metadata from other envelopes. A simple way to do this is to move the originally encrypted payload into a json field that doesn't get re-encrypted with the next envelope; see https://docs.google.com/presentation/d/1zE5YLzU2VUFdRy3lNpv4LOwMy15yJAkZMO_eitfNSOk/edit#slide=id.g4d0fe0a930_0_0.

Naively nested envelopes works, but it's inefficient. The inefficiency may not matter much on servers, but on mobile devices, it's more significant. It causes message bloat, which wastes bandwidth and battery. Most routing scenarios will involve at least 2, often 3 or 4, layers of envelopes, and a 30% expansion per encryption would mean 1.3^4 = nearly 3x message size. That's 3x the transmission time between a phone and the cloud, 3x the burden on mediators and relays, and 3x slower encryption/decryption.

This issue has been raised in other places, but always in a comment stream. I'm now opening it as an issue of its own so we can have a proper discussion about it. I don't consider this feature a must-have, but I think it's a nice-to-have that is worth exploring carefully before we retire it.

If we're about to write a spec to standardize envelope behavior, we can no longer say "we'll solve this later." It's now or never.

@kdenhartog @tplooker @troyronda @Baha-sk @TelegramSam

**Comment by Baha-sk** [comment]
I think the scenarios in [RFC-0046 mediators and relays](https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0046-mediators-and-relays/README.md) are well defined in a sense where envelope wrapping happens in `mediator` agents (which are located on some kind of server platform with more processing power). See [gateKeeper](https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0046-mediators-and-relays/README.md#scenario-2-a-gatekeeper), [herd hosting](https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0046-mediators-and-relays/README.md#scenario-6-herd-hosting), [intra-domain dispatch](https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0046-mediators-and-relays/README.md#scenario-7-intra-domain-dispatch) or [double mediation](https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0046-mediators-and-relays/README.md#scenario-8-double-mediation) scenarios.

I believe it makes sense to keep wrapping the sender envelope on the server (or cloud) side but the last agent to receive a wrapped envelope (in the cloud, ie the one that talks directly to the final `mobile` agent) must `peel` off the envelope and send the inner most one since, in most cases, it's a mobile agent with limited cpu capacity.

**Comment by Moopli** [comment]
Here's an option - define a separate format for a _wrapping envelope_, which wraps an _inner envelope_:

Assuming the inner envelope has a format like:
```
{
  "metadata" : {},
  "content" : encode(encrypt(data))
}
```
Then a wrapping envelope, which wraps an inner envelope `data_envelope`, looks like:
```
{
  "metadata" : {
    "metadata-length" : <length of encrypted, encoded metadata>
  },
  "content" : encode(encrypt(data_envelope.metadata)) + data_envelope.content
}
```
This way, any content only needs to be encrypted and encoded once, with any level of nesting, with encrypted, encoded data concatenated together in some way (We could use a JSON array, or concatenate strings, for example).

The current and suggested envelope formats would have their protected header, recipient data, and content MAC all lumped together in metadata, and the encrypted message is the content. We don't need the JSON to reflect the metadata/content distinction perfectly either, as long as we are clear in our spec that certain fields are to be treated as metadata while one other is content.

**Comment by dhh1128** [comment]
@Baha-sk : It is totally true that mediators can do wrapping. However, it is also the case that sometimes--and I believe the intent and current implementations would say 95% or more of the time--the original sender does *all* of the wrapping. Having a mediator re-wrap is likely to become more significant as we introduce just-in-time routing decisions.

The relevance of this is just that the association between wrapping/unwrapping and server platforms isn't as strong as we might imagine.

**Comment by Baha-sk** [comment]
fair enough, then onion wrapping is not a good solution if end agents are responsible for fully wrapping/unwrapping.

As in the postal service, when an envelope is transported over several postal offices, it gets a stamp on the original envelope. This is somewhat similar to adding a hash in the envelope header to state the envelope has reached `mediator` agent X in the route. The final agent will then get the same unaltered unwrapped envelope with a set of hashes in the header (which can be also used for  route verification by the final recipient). I guess @Moopli's suggestion [above](https://github.com/hyperledger/aries-rfcs/issues/341#issuecomment-562221146) is an example of this hashing mechanism.

**Comment by Moopli** [comment]
I should amend my suggestion - we don't need separate formats for the innermost envelope and for wrapping envelopes.

Our problem is one where we have two types of content in messages (including the envelope, since wrapping means using an envelope as a message) - content to be transmitted in the clear (as authenticated additional data), and content to be encrypted and encoded. We make this distinction because when we treat an envelope as a message, we do not need to re-encrypt and re-encode the encrypted&encoded payload - so that is an example of cleartext content.

If we define in our message specs a specific tag that holds a piece of cleartext content (for example, holding data that's already encrypted), then an envelope spec can define a means to extract that, encrypt the rest of the message, and append these data together for the envelope payload, which is itself treated as cleartext content by further wrapping envelopes.

@Baha-sk this isn't a hashing mechanism at all - it's layered encryption, so any agent passing the message along only knows who sent it to them and who they send it to. One problem right now with what I've suggested is that most encodings would make it quite obvious where one ciphertext ends and the next ciphertext begins, so you can sniff the number of hops the message still has to take.

**Comment by Baha-sk** [comment]
I believe the issue is we want to avoid multiple wrappings to minimize processing in the agents. This is why adding either a hash  or say probably the `timestamp` and `agentID` of the `router` in the envelope header is sufficient.

**Comment by Moopli** [comment]
My understanding is we want multiple wrappings, so, like onion routing, each mediator only knows who sent them the message, and who they send the unwrapped message to.

This isn't about providing some sort of signoff mechanism, where each router asserts that the message passed through their custody, and can see the identity of all past (and possibly future) routers along the chain.

**Comment by Baha-sk** [comment]
This depends on the subtle definition of `optimize` in the issue title.

If the goal is to stick to the scenarios listed in [RFC-0046 mediators and relays](https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0046-mediators-and-relays/README.md), then yes, your solution is plausible and acceptable.

My opinion of optimizing repeated envelopes is `avoid` wrapping altogether. This means `mediator` agents mentioned in RFC-0046 should just be `relay` agents.

If we go back in a real world practical post office scenario, envelopes are not wrapped, they are just routed to the regional office servicing their final destination. Whether adding a hash or timestamp in the JWE envelope header at each hop is up for discussion but the envelope remains intact.

In the end, we want to minimize the workload on mobile agents and repeated envelopes only increases it.

**Comment by Moopli** [comment]
How do you ensure that an envelope reaches its destination without every relay being able to see the full route? The real world postal scenario allows each institution along the trip to see the past route and destination, and either see the planned future route or decide the future route of the message.

To provide route privacy, you could package the envelope with a list of encrypted metadata headers, with each relay being able to decrypt exactly one of those, but then each relay needs to check all of the headers to find theirs. An encrypted message scheme like being discussed here would be almost the same, but with a few marked improvements: 
- Wrapping makes it clear that there's a specific order in which the envelope can be decrypted by one mediator/relay and the next
- Wrapping ensures that each mediator/relay along the way will receive the specific message layer that they can unwrap

**Comment by Baha-sk** [comment]
Regardless of what solution we end up with the, purpose of RFC 0334 is to be JWE compliant.

So no custom headers (I retract my previous comment about adding customer headers) and no changes to the envelope format.

**Comment by dhh1128** [comment]
>My opinion of optimizing repeated envelopes is avoid wrapping altogether.

This is a non-starter. Repeated wrapping will happen. Advocating otherwise calls into question most of DIDComm design, which we can't do at this point.

>Regardless of what solution we end up with, the purpose of RFC 0334 is to be JWE compliant. So no custom headers (I retract my previous comment about adding customer headers) and no changes to the envelope format.

1. It is not out of compliance with the JWE spec to add custom headers to a JWE. So it seems that you are defining "JWE compliant" to mean "behaving in a way that existing JWE libraries will like what we do" instead of "behaving in a way allowed by the JWE spec". Is that summary of your intent accurate?

2. Either or both definitions of "JWE compliant" are desirable, and I strongly hope we can achieve them. However, neither is an absolute requirement accepted by this community, so citing that as a requirement does not automatically mean that other requirements can be ignored.

**Comment by troyronda** [comment]
@dhh1128 
> Repeated wrapping will happen.

Agree.

> "JWE compliant"

I think we should aim for a solution that performs the customization prior to the JWE operations. 

> A simple way to do this is to move the originally encrypted payload into a json field that doesn't get re-encrypted with the next envelope

JWS defines [detached mode](https://tools.ietf.org/html/rfc7515#appendix-F) where the payload can be removed. As stated in IETF RFC7515, this strategy has the following benefit:

> Note that this method needs no support from JWS libraries, as
   applications can use this method by modifying the inputs and outputs
   of standard JWS libraries.

I'm not aware of the equivalent being defined for JWE but the same principle might apply to this situation. I assume a (very rough) starting point for a solution might be:

Sender:
1. creates the "final" JWE intended for the recipient (normal JWE operation).
2. extracts the ciphertext and replace with an empty string.
3. creates the nested envelopes around the "final" JWE (but with the empty string ciphertext).
4. sends the nested envelope (normal JWE) plus the ciphertext from the "final" JWE.

Mediators:
1. Decrypt their layer (normal JWE operation).

Receiver:
1. Inserts the ciphertext field back into the "final" JWE.
2. Decrypts the "final" JWE (normal JWE operation).

This starting point solution has the following characteristics:
- only encrypts the payload once.
- JWE headers are re-encrypted at every nesting level.
- metadata is re-encrypted at every nesting level.
- needs no support from JWE libraries.
- requires a structure for transporting both the nesting JWE and the additional ciphertext.
- requires some minor additional logic prior to invoking the JWE library.

**Comment by dhh1128** [comment]
+100 to @troyronda 's suggestion. That sounds excellent.

**Comment by troyronda** [comment]
I just found an existing utility that has a JWE detached mode option: https://github.com/latchset/jose

Here is sample output (encrypting a file containing "Hello World" using A256GCM):

**Normal Mode**
*JSON Serialization*
```
{
    "ciphertext":"AwmSd5fKKTpc5LR0",
    "encrypted_key":"",
    "header":{"alg":"dir"},
    "iv":"4DmZs6Psda16IFVj",
    "protected":"eyJlbmMiOiJBMjU2R0NNIn0",
    "tag":"Ow2BI9qEzwjNXCCKkZZ8Pw"
}
```

*Compact Serialization*
```
eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..uEb5gRhry1np2mvY.hZ3GNnq9blhEfh1F.lztTxjrPyCUD8-At_DYdhg
```

**Detached Mode**
*JSON Serialization*
```
{
    "encrypted_key":"",
    "header":{"alg":"dir"},
    "iv":"SC6zVom0VEdL-jXs",
    "protected":"eyJlbmMiOiJBMjU2R0NNIn0",
    "tag":"UqKk18gpfuDvlhWcpVLDQg"
}
```
plus a separate output containing the ciphertext.

*Compact Serialization*
```
eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..2GEyZjhqxKlQnXmx..LP2mZAZsgztklAgNUG6H7A
```
plus a separate output containing the ciphertext.

**Comment by troyronda** [comment]
The extracted ciphertext serialization format should have additional thought for both compact and JSON modes. As a starting point:

- Compact mode: Each extracted ciphertext is appended to the end of the serialized "final" JWE (using dot seperation). These extracted cipher texts are ordered in the same manner as the nesting (from outermost to innermost).
- JSON mode: The extracted ciphertext are placed into a JSON array. These extracted cipher texts are ordered in the same manner as the nesting (from outmost to innermost). The array is appended to the "final" JWE object as the `detached_ciphertext` field.
