### ISSUE TITLE
RFC 0025: DIDComm Transport: Include a minimal set of requirements for a new DIDComm transport

### ISSUE THREAD

**Issue by mwherman2000** [hyperledger/aries-rfcs#343]
Reference: https://github.com/hyperledger/aries-rfcs/tree/master/features/0025-didcomm-transports

For example,
- is a one-way, request-response communication protocol sufficient?
- minimum message/payload lengths that must be supported?
- etc.

Context 

I'm wondering if it is worth investigating whether DIDComm can run over the DNS standard binary port 53 protocol? ...for an example of the traditional DNS request and response, checkout https://hyperonomy.com/2019/01/02/dns-domain-name-service-a-detailed-high-level-overview/
...so that the Trusted Digital Web Data Registry https://hyperonomy.com/2019/11/06/trusted-digital-web-whitepaper/() can be DIDComm-enabled.

**Comment by swcurran** [comment]
Discussed on the Aries WG Call on 20200108 and @kdenhartog volunteered to determine a response and update the 0025 RFC with a paragraph that addresses the question. Barring a rabbit hole being found unexpectedly, this should be less than an hour to think through and respond.

**Comment by TelegramSam** [comment]
Continue this issue here: https://github.com/decentralized-identity/didcomm-messaging/issues/27
