### ISSUE TITLE
Github Action to update index file fails when there is no index update to be made

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-rfcs#361]
I merged a change that did not impact the index.md file in the repo, and the action to update the index.md failed with an error.  It appears that the when there is no change to the index.md file, the job tries to do a commit anyway and fails.

Details from the failure below:

Run failed for update-rich-schema-context (dc41b7f)
Repository: hyperledger/aries-rfcs
Workflow: Index Generation
Duration: 34.0 seconds
Finished: 2019-12-20 23:56:05 UTC

[View results](https://github.com/hyperledger/aries-rfcs/commit/dc41b7f503124fae62d55d8890ee4d50d208b05d/checks?check_suite_id=369396948)

Jobs:
ca395085-040a-526b-2ce8-bdc85f692774 failed (1 annotation)

**Comment by TelegramSam** [comment]
We have a conflict between Github Actions generating the index and branch protection that has been enabled on the RFC repo.

This one needs some ideas and some additional work

**Comment by swcurran** [comment]
Suggest that we close this as "oh well" and periodically update the index.  I was going to suggest we turn off the GHA, but it serves a good reminder that the index needs to be updated.  Better would be to change the action to send an email to all of the Maintainers that the index needs to be updated since a merge was completed.

**Comment by TimoGlastra** [comment]
I think there are some other options besides removing the GHA:

1. Force the index to be updated before a PR can be merged. This is easy to check by running the current action and see if there is any diff.
2. Modify the GHA to open a PR with the updated index. This is comparable to the email method you suggest, but would eliminate the manual process of generating the index.
3. Modify the GHA to add the regenerating of the index commit to the PR instead of running after the PR has closed. This way the commit will be added to the PR branch, not the protected master branch.

option 3 would require the least effort of contributors, but would add a (maybe unwanted?) commit to the PR. It would also be easy to make the GHA comment on the PR stating the index is not up to date and the user could do `/generate-index` to add the commit. 

I'll be happy to take a shot at one of those.

**Comment by swcurran** [comment]
Thanks - good ideas. Would 2 and 3 handle DCO properly?

1 (and 3?) is a pain because if the ordering of the merge differs from the PR submission, the index update becomes stale, blocking the merge. That is unless the update occurs as part of the merge process (but again -- DCO?).

2 is probably the easiest on individuals, assuming the DCO can be dealt with.

**Comment by TimoGlastra** [comment]
DCO won't be a problem, we could signoff the commit on the github actions user.

However it seems something is up with the protection of the `autogenerated` branch. It doesn't show as protected, but the github actions user doesn't have the permission to push to it. While on my test-repo it has. 

I have a working version that automatically opens a PR to update the index, and will update the PR when new changes are commited. If the PR is merged the action will create a new PR once the index changes. But now I'm not sure anymore it'll work for the RFC repo.

Working version: https://github.com/TimoGlastra/actions-test/blob/master/.github/workflows/indexgenerate.yml

**Comment by swcurran** [comment]
Can it be worse than what we have now?  :-).  The current version just generates an error. As long as the worst yours does is the same, I'd say go for it.

**Comment by TimoGlastra** [comment]
Let's try it: #521

**Comment by swcurran** [comment]
Merged.  Waiting...

**Comment by TimoGlastra** [comment]
It had nothing to update in the Index....

#522 fixes an incorrect PR number and should trigger an update. 2 in 1 :)

**Comment by swcurran** [comment]
Well -- no worse than before :-)

The action failed -- https://github.com/hyperledger/aries-rfcs/actions/runs/196444326

Thoughts?

**Comment by TimoGlastra** [comment]
That's a bummer.

The github actions token doesn't have the permission to push, even to unprotected branches. This is probably a security setting. Without changing this it can't work. 

So I think we're back at:
> Suggest that we close this as "oh well" and periodically update the index.

**Comment by swcurran** [comment]
Thanks for trying... :-(
