### ISSUE TITLE
Need clarification: for 'change_sig' attribute in 0160-Connections Response message

### ISSUE THREAD

**Issue by naman1303** [hyperledger/aries-rfcs#362]
In the **Response Processing** section of **Connection Response** step, below is mentioned:

> When the invitee receives the response message, they will verify the **_change_sig_** provided.

But the attribute 'change_sig' is not mentioned anywhere else. 
Is it a typo (where it actually meant 'sig_data' or 'connection~sig')? 
Please correct it or add some detail to it otherwise.

**Comment by swcurran** [comment]
The specific reference is to [this section](https://github.com/hyperledger/aries-rfcs/tree/master/features/0160-connection-protocol#response-processing) of the 0160-Connections RFC.

@andrewwhitehead @tmarkovski - can either one of you take a read of that section, and perhaps the full Connection Response section?  Is it accurate with what has been implemented and is working?

Thanks

**Comment by swcurran** [comment]
Per the Aries WG call on 20200108, @tmarkovski volunteered to review the RFC and respond to this question.  Tomislav - I'm happy to do the RFC update if you want to summarize any needed changes.

**Comment by tmarkovski** [comment]
It should be `sig_data`. Submitted PR

**Comment by swcurran** [comment]
Thanks. Is that the only change, or does the rest of that section align
with what you have implemented?

**Comment by tmarkovski** [comment]
Rest of the section looks good.

**Comment by swcurran** [comment]
Thanks @tmarkovski - closing this issue as resolved. The associated PR has been merged.
