### ISSUE TITLE
RFC 0250: Identification and relationship between Rich Schema objects

### ISSUE THREAD

**Issue by ashcherbakov** [hyperledger/aries-rfcs#398]
@brentzundel @ken-ebert
RFC 0250 provides a great overview of Rich Schema feature.
However, there is a number of things that need to be defined (probably in a separate more technical RFC). By Rich Schema objects I mean all Rich Schema related objects (Context, Rich Schema, Mapping, Encoding, etc.)

- What is a (unique) ID of every Rich Schema object? How is it generated/obtained?
- What ID is used when referencing one Rich Schema object from another (for example, how encodings and schemas are referenced in a mapping). It would be great to define it for every relationship.
- It would be great to define cardinality for every relationship. For example, can Credential Definition use more than 1 Rich Schema in a Mapping object, or a Mapping object maps exactly 1 Schema's attributes to corresponding encodings? Does Credential Definition's Mapping map all attributes from a Schema, or it can map only a subset of attributes? 
- Are all Rich Schema objects immutable, or there any mutable ones? 
- What ID can be used to query (get) a Rich Schema object from a Data Registry (Ledger)?
- Should all Rich Schema objects be queried and obtained from the Ledger separately, or there needs to be a way to get a bunch of Rich Schema objects in one request. For example, a Verifier will need a number of Rich Schema objects (CredDef, Mapping, Schemas, Encodings) to do the verification. So, although getting each of this objects individually would be easier from the implementation point of view, it may be not so convenient from UX point of view. 
- Are we going to keep compatibility between existing CredDev/Schema objects and Rich Schema new ones? In other words, should it be possible to use existing CredDef and Schemas objects in a new workflow and, for example, Presentation Definitions? 
- A workflow/sequence diagram for a new Rich Schema based verifiable credentials would be useful. 
- Do we assume that all Rich Schema objects are required in all use cases? Are we going to define any fallback behaviour or defaults, so that the workflow and UX for simple cases (close to existing non-Rich schema one) becomes more simple? 
- Do we assume/require  any additional metadata for every Rich Schema object (such as name, version, issuer DID, etc.)? What is a general template for Rich Schema objects taking into account this metadata?

**Comment by andrewwhitehead** [comment]
My thoughts:

For identifying and linking to rich schema objects, I suggest that [DID URLs](https://w3c-ccg.github.io/did-resolution/) should be used. In the case of the Sovrin ledger, a resolver might map `did:sov:BzCbsNYhMrjHiqZDTUASHg/schema/recipeIngredient/1.0` to a ledger request (`GET_SCHEMA` or a new operation) including the origin DID, schema name, and version. A similar scheme could be devised for mappings and encodings, possibly sub-paths on the URL.

For specificity, the DID URL may be extended with a `;result-type=rich-schema` input parameter, although I don't think this is necessary in most situations:

`did:sov:BzCbsNYhMrjHiqZDTUASHg;result-type=rich-schema/schema/recipeIngredient/1.0`

The schema version might by extended by ledger-specific input parameters like a transaction sequence number (`;sov:seq-no=12568`) or by adopting the `version-id` input parameter to include either the sequence number or a hash of the transaction.

I don't think that contexts and schemas need to be stored independently when a schema definition includes a context and that can be referenced explicitly by a DID URL; the graph part of the schema could simply be made optional for schemas that only define a context.

Giving each schema a unique DID on the ledger seems to takes away the attribution that exists now and break the current relationship of each DID to a source NYM transaction, although I'm not sure on the specifics of how that would work.

An an example derived schema (context):

```json
{
    "@context": [
        "did:sov:BzCbsNYhMrjHiqZDTUASHg/schema/recipeIngredient/1.0",
        {
            "dct": "http://purl.org/dc/terms/",
            "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
	}
    ]
}
```

**Comment by brentzundel** [comment]
> * What is a (unique) ID of every Rich Schema object? How is it generated/obtained?

All Rich Schema objects are referred to by DIDs.
There are two types of Rich Schema objects. Control objects and content objects. 
Control objects are associated with keys and can change. The primary example of a control rich schema object is a cred def. Control objects could have an id-string that is randomly generated, or somehow based on the initial public key.
Content objects contain immutable data. The id-string of a content object should be based on the hash of the immutable data.

> * What ID is used when referencing one Rich Schema object from another (for example, how encodings and schemas are referenced in a mapping). It would be great to define it for every relationship.

The rich schema objects should refer to one another using their DIDs.

> * It would be great to define cardinality for every relationship. For example, can Credential Definition use more than 1 Rich Schema in a Mapping object, or a Mapping object maps exactly 1 Schema's attributes to corresponding encodings? Does Credential Definition's Mapping map all attributes from a Schema, or it can map only a subset of attributes?

Agreed. Somewhere there is a photo of a whiteboard that contains this information, but it really should be included as part of the overview RFC.
A cred def refers to a single mapping object
a mapping object refers to 1 or more schema objects. Each attribute in a schema may be included in the mapping one or more times (it is possible to encode a single attribute in multiple ways). A mapping may map only a subset of the attributes of a schema.

> * Are all Rich Schema objects immutable, or there any mutable ones?

most of them are immutable content objects. Any which contain keys would be control objects.

> * What ID can be used to query (get) a Rich Schema object from a Data Registry (Ledger)?

The object's DID will be the primary mechanism for requesting an object from the data registry.
In the future I can imagine queries based on property values such as name or type being possible.

> * Should all Rich Schema objects be queried and obtained from the Ledger separately, or there needs to be a way to get a bunch of Rich Schema objects in one request. For example, a Verifier will need a number of Rich Schema objects (CredDef, Mapping, Schemas, Encodings) to do the verification. So, although getting each of this objects individually would be easier from the implementation point of view, it may be not so convenient from UX point of view.

I think this definitely should be possible, but should be handled at a higher layer of the software. I don't see the benefits of batching requests at the request level.

> * Are we going to keep compatibility between existing CredDev/Schema objects and Rich Schema new ones? In other words, should it be possible to use existing CredDef and Schemas objects in a new workflow and, for example, Presentation Definitions?

I'm not sure. We've talked about making it possible to verify rich schema credentials with existing verification software and proof requests. I don't think it would be possible to use existing cred defs and schemas in rech schema credentials, but it may be possible to incorporate them into rich schema presentations.

> * A workflow/sequence diagram for a new Rich Schema based verifiable credentials would be useful.

I agree, this should be added to the overview RFC.

> * Do we assume that all Rich Schema objects are required in all use cases? Are we going to define any fallback behaviour or defaults, so that the workflow and UX for simple cases (close to existing non-Rich schema one) becomes more simple?

All of them are required for anonymous credentials. Simple credentials would probably only require cred defs and schemas.

> * Do we assume/require  any additional metadata for every Rich Schema object (such as name, version, issuer DID, etc.)? What is a general template for Rich Schema objects taking into account this metadata?

The general template for Rich Schema objects is a DID document. I think that a selection of additional metadata (such as name and version) may be useful for future query capabilities. Other metadata such as issuer DID only makes sense for control objects. Content objects do not require such information.

**Comment by ashcherbakov** [comment]
Thanks for all the comments! Your answers match our vision, so we will work on an RFC to put this all together. 
Can you please clarify what do you mean by ` Rich Schema objects is a DID document`? Does it mean just a JSON-LD object, or some specific format? As I understand, DID Document is JSON-LD serialized and has special fields related to DID (such as public keys, authentication, etc.).
Can you please point to some W3C up-to-date resources related to this?

**Comment by ashcherbakov** [comment]
As for mutability of Credential Definition as a result of key rotation, I think it's not obvious. 
If Issuer's key is rotated, then all credentials issued for this key will be invalidated. In some cases (if the key was compromised) it can be desirable. In some cases not (if we have millions of credentials already issued, or we pretty sure that credentials issued till some date are correct, and the key is compromised only after a date).
I think that we may declare Credential Definition as immutable object as well. If the Issuer needs to rotate the key, he or she can create a new Credential Definition.
The problem whether we should invalidate existing credentials can be solved on Presentation Definition level: we may say that credentials from this Credential Definition are not accepted anymore.
This may mean that we may need to make Presentation Definition mutable.

**Comment by ashcherbakov** [comment]
The following RFC is created to address most of this questions: https://github.com/hyperledger/aries-rfcs/pull/418
There is also a corresponding Indy HIPE: https://github.com/hyperledger/indy-hipe/pull/153

**Comment by TelegramSam** [comment]
This appears resolved and result captured. Closing.
