### ISSUE TITLE
RFCs 0036 and 0037 (and others?): need formal state names

### ISSUE THREAD

**Issue by dhh1128** [hyperledger/aries-rfcs#408]
I was in these RFCs, and noticed that although they have nice choreography diagrams, they don't provide formal names for their states. This is probably because they didn't build state machine matrices, which is fine (the matrices are just an optional diagram; the choreography diagrams are an experiment to see if the same content can be better represented the other way). Whatever diagram we do or do not use, we need formal names for the states, because problem reports need to report state in an interoperable way. This is the basis of DIDComm features like "I experienced an error while in <state 7>, and I'm now dropping back to <state 6>", and they are also [implied by RFC 0317 please_ack](https://github.com/hyperledger/aries-rfcs/tree/master/features/0317-please-ack#advanced-features-experimental). Today this is mostly tribal knowledge about future direction, not a feature we depend on. But I think this will become important as protocols become more complex, and as our standards for robustness and error handling go up.

So I recommend that we agree to assign formal state names in each place that they are lacking. If we do, I will then take an action item to submit PR(s) to do so.

@rajeshkalaria80, @dkulic

**Comment by TelegramSam** [comment]
I agree that formalized names make sense. @dhh1128 I think an example PR would make this pretty clear and promote any discussion we need to have.

**Comment by dhh1128** [comment]
Agreed. I will prepare an example that we can discuss on Wednesday's community call.

**Comment by dhh1128** [comment]
I have raised PR #412 as an example of what I'm thinking. I have also prepared a [slide deck](https://docs.google.com/presentation/d/17hk6QqLW5M9E4TBPZwXIUBu9eEinMNXReceyZTF4LpA/edit) to explore the issue in a community call.

**Comment by swcurran** [comment]
Closing this.  There is a new PR that is in the same vein for Present Proof (0037), but we can deal with this without having this issue open.
