### ISSUE TITLE
RFC 0015 inconsistency with RFC 0008 in ~thread decorator

### ISSUE THREAD

**Issue by smithbk** [hyperledger/aries-rfcs#422]
https://github.com/hyperledger/aries-rfcs/tree/5cc750f0fe18e3918401489066566f22474e25a8/features/0015-acks#explicit-acks uses fields named `myindex` and `lrec` but https://github.com/hyperledger/aries-rfcs/tree/64e5e55c123b2efaf38f4b0911a71a1c40a7f29d/concepts/0008-message-id-and-threading#threaded-messages uses `sender_order` and `received_orders` for these field names.
I think RFC 0008 is correct and RFC 0015 should be corrected.  Agree?

**Comment by swcurran** [comment]
Correct - thanks for that.  Please go ahead with a PR.  Perhaps add a change log and a mention there, but it is a typo in an example, not a version-worthy change. Very unlikely anyone will be affected by the change.

**Comment by smithbk** [comment]
See PR https://github.com/hyperledger/aries-rfcs/pull/458

**Comment by kdenhartog** [comment]
closing this. Merged in PR #459
