### ISSUE TITLE
Signature decorator inconsistency

### ISSUE THREAD

**Issue by gnarula** [hyperledger/aries-rfcs#423]
## RFCs

The example for `connection~sig` in connection-protocol in AIP has the signer vk in *signers* key:

https://github.com/hyperledger/aries-rfcs/blob/9b0aaa39df7e8bd434126c4b33c097aae78d65bf/features/0160-connection-protocol/README.md#L398-L403

The example for `connection~sig` in did-exchange has the signer vk in *signers* key:

https://github.com/hyperledger/aries-rfcs/blob/9b0aaa39df7e8bd434126c4b33c097aae78d65bf/features/0023-did-exchange/README.md#L403-L408

The signature-decorator spec, mentions the *signer* key (singular)

https://github.com/hyperledger/aries-rfcs/blob/23f8b38de84bec6154cec268280916aaf00fd17c/features/0234-signature-decorator/README.md#L45-L50

## Implementations

* ACA-Py
https://github.com/hyperledger/aries-cloudagent-python/blob/0b3cdc01df02de45831105ef828c5715bb6ac89a/aries_cloudagent/messaging/decorators/signature_decorator.py#L152-L155

Uses *signer*

* aries-framework-dotnet
https://github.com/hyperledger/aries-framework-dotnet/blob/b9568956caa2bd943f88d0e0e786179d806d997f/src/Hyperledger.Aries/Decorators/Signature/SignatureDecorator.cs#L25-L26

Uses *signer*

* aries-framework-go (didexchang)
https://github.com/hyperledger/aries-framework-go/blob/0a8e0df91f716da9d56e0fc7e08d3809aef17837/pkg/didcomm/protocol/didexchange/models.go#L66-L71

Users *signers*

* aries-framework-javascript
https://github.com/hyperledger/aries-framework-javascript/blob/80525cffbbbe82c5a8c13cda313dedf8d4ae335d/src/lib/decorators.ts#L22-L26

Uses *signer*

Besides the difference in the field name, RFC 0234 suggests values are supposed to be base64URL encoded. What should implementations of 0160 follow?

**Comment by swcurran** [comment]
Good stuff - thanks for reviewing and providing clear feedback. My suggestion:

1. Change connection to "signer" as a clarification - no new version. Update AIP to point to the clarified version.
2. Same with DID-Exchange, with notification to the aries-framework-javescript team.
3. Update the signature decorator RFC to change to "signer".

I'm not sure on the last question re: 0160 and base64URL - others?  @andrewwhitehead 

Thoughts @troyronda @llorllale @TelegramSam ?

**Comment by TimoGlastra** [comment]
I think the base64url issue has been resolved elsewhere, and created a PR to fix the `signer` / `signers` issue for completeness: https://github.com/hyperledger/aries-rfcs/pull/732
