### ISSUE TITLE
Update 0036 to remove "Indy-isms" in the credential proposal

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-rfcs#450]
In the 1.0 and 1.1 versions of this protocol, there are references to Indy items in the credential proposal message. Propose that a 2.0 version of the protocol be defined that changes the format of that message to match the style of the other messages in the protocol with an attachment, and the Indy-specific fields be removed from the message.

@sklump has taken a first cut of [that here](https://github.com/sklump/aries-rfcs/tree/issue-cred-2.0/features/0036-issue-credential#propose-credential). Note that Stephen's version of the RFC is not quite correct because it is treating the versioning at the message level vs. the protocol level. That will be changed prior to submission. 

~~Related, second issue - I would prefer not to have a separate RFC document for this change, even though it is a new major version, but am open to discussion on that.  Should the rule -- new major version, new RFC be strictly adhered to?~~ The answer to this is no. Further, in this case, the changes are larger than first thought, so we want to start a new RFC regardless.

**Comment by swcurran** [comment]
Based on the Aries Working Group discussion on this, the following things need to be done to 0036 and 0037:

- define how to add types to the attachments
- in defining the types, define a registry of those types for devs
- can the attachments be just JSON vs. base64-encoded JSON?
- should the "credential preview" be an attachment?
- should the presentation preview by an attachment?

@swcurran is to move this forward by creating a PR based on what @sklump started. That covers the "credential proposal" attachment.

**Comment by swcurran** [comment]
Regarding JSON. The Attachments RFC makes it very clear how a JSON attachment is to be implemented, so there should be nothing in the Credential Exchange RFCs that preclude the use of JSON vs. base64 encoded data. I suggest we add that as a clarification to the RFCs, but implementations should be reviewed and updated if necessary to make sure that they support both.

**Comment by swcurran** [comment]
Regards the attachment "type" and a registry of the type of the attachments.

Per the "attachments" RFC, the "id" should uniquely identify the attachment in the context of the message.  We've agreed (and spelled out in the 0036/0037 RFCs) that though the attachments are arrays, in these messages, they should not be used for bulk issuance of different credentials, but rather for different representations of the same credential (e.g. a ZKP and JWT version a credential containing the same claims). As such, I think the ID should used to determine both the handler and version of the attachment. This is partially done (sans the versioning) in the presentation RFC today and we should expand that to issue credential.

Given that, I think the RFC could contain (at least initially) a table that is the registry of the ID values and their meanings.

I'll put that into a proposal for the 2.0 Issue Credential and the 1.1 (or 2.0) Present Proof RFCs.

**Comment by TimoGlastra** [comment]
Closing as we now have the Issue Credential v2 proposal which removed all indy-isms.
