### ISSUE TITLE
RFC0434 - should request messages with no attachments be rejected?

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-rfcs#451]
@TelegramSam @swcurran 

Should we force senders to use the `invitation` message instead?

**Comment by swcurran** [comment]
They should be rejected. I don't see how they can be taken as `invitation`s as they lack the `protocol`.  So I would say they should be rejected.  This would be another case of an optional Problem Report, since there is a service endpoint that could be used for sending the ProbRep. Do you think we should add that to the RFC?

That would be my $0.02CDN.

**Comment by TelegramSam** [comment]
I think we indicate that it's required, which promotes rejection by receiving agent.

**Comment by llorllale** [comment]
@swcurran 

> I don't see how they can be taken as invitations as they lack the protocol

Interesting - both @TelegramSam and I think did-exchange can result from a `request` message. Should we add `protocols` to `request` as well?

> This would be another case of an optional Problem Report, since there is a service endpoint that could be used for sending the ProbRep. Do you think we should add that to the RFC?

We could add some verbiage qualified with a MAY.

**Comment by llorllale** [comment]
Related: #468

**Comment by swcurran** [comment]
So you are saying that a sender could send a `request` **WITH** a `protocols` item.  The responder can then choose to either respond with a message about the request or a DID-Exchange `request` message (or equivalent from another protocol - e.g. 0160 Connections).

That feels weird to me - offering both a connection-less and a connection-establish flow at once. I think that will be difficult for the responder to figure out - especially if that is a person.  Not against it, but it seems odd.

If we do want that, do we go back to a single protocol that just has `protocols` and `requests` as a single message?  I'm not a fan of adding `protocols` to this message but if done I would prefer we have just one message.

**Comment by TelegramSam** [comment]
on further thinking, I think did-exchange from a request message is not a great idea.

**Comment by llorllale** [comment]
@swcurran 

> So you are saying that a sender could send a request WITH a protocols item. The responder can then choose to either respond with a message from the requests or a DID-Exchange request message (or equivalent from another protocol - e.g. 0160 Connections).

No - my intention is to have the responder optionally respond with did-exchange/connections protocol *and then* proceed to send the request embedded in the OOB message.

> That feels weird to me - offering both a connection-less and a connection-establish flow at once. I think that will be difficult for the responder to figure out - especially if that is a person.

An alternative would be to include the array of attachments in the `invitation` message. This way the intention to create a permanent connection is clear *and also* the expectation that the responder replays the message back to the sender.

> If we do want that, do we go back to a single message that has optional protocols and requests? 

Maybe. This was previously discussed at length with @dhh1128 [here](https://github.com/hyperledger/aries-rfcs/pull/434#discussion_r385977662). I think the `invitation` could use attached requests *in addition to* `goal-code` for protocols and relationships that require the responder in this case to initiate the transaction.

**Comment by swcurran** [comment]
OK - given that context, particularly the idea of merging the connection and purpose, my preference is that we keep things as they are.  This precise issue was extensively discussed on the first pass and we agreed in the end (admittedly, begrudgingly for some) that we don't want to combine the connection and the (connection-less) `request`. If that behaviour is wanted, do one after the other.  The compromise was the `goal-code` and I don't see any reason to change that.

I thought this discussion was another use case (connection or reply). If it is connect and reply, I'd prefer to keep things as we have them.

**Comment by llorllale** [comment]
@swcurran 

Sorry - I'm not sure I understand your stance in your last comment. Are you OK with putting request attachments in the `invitation` message, or are you saying you're fine with the responder establish a new connection from a `request` message **and then** sending the attached request? Or something else?

**Comment by swcurran** [comment]
I view is that I don't want either. 

I don't want to combine a "establishing a connection + processing the first request" -- we discussed it extensively in the OOB PR and rejected that idea.  So I don't want requests in the invitation.

Similarly, I would discourage (ideally, not allow) responders to establish a new connection before sending the response to an `oob-request`.

My feeling is that both flows are too complex for users and too complex to test.  They are (again, my opinion) minor optimizations on what we have and not worth the complexity they bring.

**Comment by swcurran** [comment]
I'm sure my earlier comment was entirely unhelpful - "Not against it, but it seems odd.".  Obviously I'm now expressing a stronger opinion.  I should have thought about it more.  Apologizes for the flip-flopping.

**Comment by llorllale** [comment]
@swcurran @TelegramSam @dhh1128 

I've reviewed [this](https://github.com/hyperledger/aries-rfcs/pull/434#discussion_r385969767) thread in the original PR and must say I agree completely with @dhh1128 point. We can't assume the responder will know the context of the out-of-band message. The responder may be a device.

This is my scenario: 

* Alice owns two devices, device A and device B.
* A is a mediator.
* Alice needs to introduce B to A so that B registers a route on A.
* RFC 0211 requires B to start the mediation coordination protocol.
* Alice requires a didcomm channel between A and B.

The [Actions Menu draft](https://hackmd.io/jrWg2kw7QuWx9XS0R3_XPQ) looks DoA for this use case because it clearly states it's designed for user-facing interactions, not automated flows.

Of course, it is not *impossible* to accomplish this scenario without an out-of-band request message. The alternative would probably require more network chatter, which is not ideal. Especially considering this message is a near perfect fit.

Sam offers some alternatives [here](https://github.com/hyperledger/aries-rfcs/pull/434#discussion_r387741474). I could be swayed towards option 2. At minimum we need a way to inform the responder what their role is in the subsequent protocol after the connection is made (because the connection is made for a reason).

**Comment by swcurran** [comment]
@llorllale - could you complete your example?  You define the starting point, but not what messages happen to execute the scenario.  What OOB messages occur?  

Total aside to this discussion: Agree that Action Menus has that first line of being user-facing, but I suspect it could be used (likely as is) for device-to-device scenarios.  We need to look at that when it becomes a priority.

**Comment by llorllale** [comment]
@swcurran 

Flow:

1. Alice -> A: introduce proposal (I'm thinking goal/goal-code can be included here as currently defined)
2. A -> Alice: introduce response containing an out-of-band request
3. Alice -> B: forwards out-of-band request
4. A <-> B : didexchange
5. B -> A : mediate-request
6. A -> B: mediate-grant

**Comment by llorllale** [comment]
Closed - outofband no longer has `request` messages
