### ISSUE TITLE
Cleanup repo list

### ISSUE THREAD

**Issue by ryjones** [hyperledger/aries-rfcs#460]
The [proposal][0] is to delete, not archive, the following unused repos.

- aries-sdk
- aries-agent
- aries-sdk-python
- aries-sdk-go
- aries-sdk-dotnet
- aries-kms
- aries-vdri
- aries-core
- aries-kms-postgres
- aries-ams-sqlite
- aries-sdk-ios
- aries-vdri-peer
- indy-vdri-aries

[0]: https://chat.hyperledger.org/channel/aries-maintainers?msg=5S7aBBAzBqhT5nASc

**Comment by ryjones** [comment]
@swcurran

**Comment by ryjones** [comment]
> hub delete hyperledger/aries-sdk
hub delete hyperledger/aries-agent
hub delete hyperledger/aries-sdk-python
hub delete hyperledger/aries-sdk-go
hub delete hyperledger/aries-sdk-dotnet
hub delete hyperledger/aries-kms
hub delete hyperledger/aries-vdri
hub delete hyperledger/aries-core
hub delete hyperledger/aries-kms-postgres
hub delete hyperledger/aries-ams-sqlite
hub delete hyperledger/aries-sdk-ios
hub delete hyperledger/aries-vdri-peer
hub delete hyperledger/indy-vdri-aries

**Comment by swcurran** [comment]
@ryjones - got for it.

**Comment by ryjones** [comment]
I see some code in https://github.com/hyperledger/aries-sdk-python and https://github.com/hyperledger/aries-kms/ - all the others are gone. I just want one more confirmation to delete those two repos.

**Comment by kdenhartog** [comment]
@mac-arrap @mikelodder7 or @matt-raffel-kiva do you have any insights on kms?

@TelegramSam or @dbluhm do you have any insights on aries-sdk-python?

**Comment by TelegramSam** [comment]
Can we archive aries-sdk-python? Or does archiving it not meet the goal?

**Comment by swcurran** [comment]
Archiving is fine and let's remove the aries-kms repo.

@ryjones - please go ahead and then close this issue.

Thanks!

**Comment by ryjones** [comment]
done
