### ISSUE TITLE
RFC 0434: processing of oob-request attachments

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-rfcs#468]
We need to capture the algorithm that processes attachments in [`request` messages](https://github.com/hyperledger/aries-rfcs/blob/f0ec8ef7ca396caa56e34e0ab1a808f4d8889c96/features/0434-outofband/README.md#message-type-httpsdidcommorgoob-requestverrequest).

(note: interestingly, this attribute changed from a single object to an array when ported over from the [original notes](https://hackmd.io/mVupMtg9RqWWUhMvWkDXGQ#Providing-a-DIDComm-Request))

Open questions:

* What are the use cases we're trying to fulfill?
* Does the responder need to respect the order of the request attachments?
* Can any of this work be done in parallel?

----

@TelegramSam @swcurran @dbluhm

**Comment by swcurran** [comment]
Agree that the lack of documentation on what to do with the array is needed. I totally missed adding any guidance in the RFC for that.

I think there are two reasons for the array:

1. The attachments RFC calls for the data element to be an array, so keeping consistent with that is expected.
2. The sender could use the array to specify a set of possible protocols from which the receiver can choose - just as we do with the `protocols` element in the `invitation` event.

My preference is that we describe the requests in the same way we described the `protocols` - e.g. that could be multiple, the receiver can respond with any of them and the sender will order them in their preferred order (ignoring that it's theoretically possible the ordering might get lost). 

In most cases there will be just one, but by allowing an array, we can better handle community upgrades - new protocols being introduced and major version upgrades.  All the same reasoning we used for having `protocols` as an array.

**Comment by llorllale** [comment]
@swcurran 

> The attachments RFC calls for the data element to be an array, so keeping consistent with that is expected.

It can be either a single value or an array when [embedding](https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0017-attachments/README.md#embedding), which is what we've done here.

> The sender could use the array to specify a set of possible protocols from which the receiver can choose - just as we do with the protocols element in the invitation event.

This raises questions, such as do all these requests need to belong to the same protocol? Different versions of the same protocol? Some use cases would help understanding.

**Comment by swcurran** [comment]
My expectation is that the requests would offer different technical transactions for accomplishing a single business level transaction. That would support multiple protocols that accomplish the same thing, or multiple major versions of the same protocol, with a preference for the latest.

**Comment by llorllale** [comment]
closed - outofband no longer has `request` messages
