### ISSUE TITLE
Should "present-proof" ACK come from the agent framework or the controller?

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-rfcs#471]
We're having a bit of debate in the ACA-Py group about when the Ack from the verifier at the end of the "present-proof' should come?  Should the ack come:

1. Automatically from the agent-framework (e.g. ACA-Py or aries-framework-dotnet) as soon as the proof is cryptographic verification is completed successfully?  Note that this could include some additional automatic verification against the proof request.

Or

2. From the controller (business logic) after both the proof is verified as true AND the controller logic finds that the contents of the proof meets the business requirements of the proof?

My assumption has always been the latter - after the business process, but others think it should come after the cryptographic verification.  I think the first model works if proofs requests are constrained to only accept proofs from known issuers. However, as soon as proofs are allowed from an broad range of issuers (for example, the case of a company requesting proof of a university degree from applicants across the world) such that not all issuers are known in advance, and therefore the controller is responsible for finding out if the issuer can be trusted. If the business process failed, a "problem-report" would be returned to the prover with a reason for the rejection of the proof.

In the case of the ACK being sent automatically (1, above) and the controller not accepting the proof based on a business process, the verifier would have to connect back with the prover to restart a proof process with a (somehow achieved) new understanding between the parties about the previously sent proof.

What are the views of others in the community on these questions?

**Comment by TimoGlastra** [comment]
Closing as I think this has been fixed with the `~please_ack` decorator using the `RECEIPT` and `OUTCOME` values. Also the ack message from the present proof v2 protocol now mentions what successful means.

Please reopen if not resolved
