### ISSUE TITLE
didexchange signed attachments

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-rfcs#476]
I noticed the examples in the didexchange RFC are inlining the signing keys in the `request` and `response` messages as `did:key`s as per the attachments RFC, eg.:

```jsonc
{
  "@id": "5678876542345",
  "@type": "https://didcomm.org/didexchange/1.0/request",
  "~thread": { "pthid": "<id of invitation>" },
  "label": "Bob",
  "did": "B.did@B:A",
  "did_doc~attach": {
     "base64": "eyJ0eXAiOiJKV1Qi... (bytes omitted)",
     "jws": {
        "header": {
           "kid": "did:key:z6MkmjY8GnV5i9YTDtPETC2uUAW6ejw3nk5mXF5yci5ab7th"
        },
        "protected": "eyJhbGciOiJFZERTQSIsImlhdCI6MTU4Mzg4... (bytes omitted)",
        "signature": "3dZWsuru7QAVFUCtTd0s7uc1peYEijx4eyt5... (bytes omitted)"
      }
   }
}
```

Successful verification of this signature with the inlined key will tell me one thing: the attachment was signed by the controller of that inlined key.

My question is: how does this information assert the sender of this message's control over the DID they sent? Shouldn't `kid` allow references to keys in the embedded did doc?

**Comment by TelegramSam** [comment]
You are correct that the key needs to be verified against the DID Doc as it is now. I'm open for a DID Key ref, though this may be hard for indy-based codebases to do in the short term due to the way libindy handles things.
