### ISSUE TITLE
RFC0212: the "Noop" message

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-rfcs#501]
What is the purpose of the [`Noop`](https://github.com/hyperledger/aries-rfcs/tree/master/features/0212-pickup#noop) message?

cc: @TelegramSam

**Comment by swcurran** [comment]
Pretty sure it is to allow a request for triggering a pickup when there is no other reason to message the mediator.  I theory status could be used, but used when not even that is needed.

**Comment by TelegramSam** [comment]
That is one use. Frankly, any message could be used, but this was included to avoid complicating other protocols such as trust ping with no reply.

**Comment by llorllale** [comment]
@TelegramSam can you provide specific examples for the responses to this message?

**Comment by TimoGlastra** [comment]
One use case I see this being useful is a mediatee opening a websocket with a mediator. This will let the mediator know which agent/key just connected and can immediately forward messages when they arrive.

**Comment by TelegramSam** [comment]
@TimoGlastra That was the exact intended use. 
@llorllale there is no response to this message by design. This allows, for example, messages to be picked up one at a time over an http transport. Connect and send noop, wait for reply. If a response was also needed, we'd never get ahead.

**Comment by swcurran** [comment]
And to clarify slightly --- "there is no **DIDComm** response to this message by design, just the HTTP response from the request".

**Comment by llorllale** [comment]
@TelegramSam @swcurran @TimoGlastra thanks
