### ISSUE TITLE
RFC0212: `list-pickup` - how does the agent obtain the message IDs in the first place?

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-rfcs#504]
[`list-pickup`](https://github.com/hyperledger/aries-rfcs/tree/master/features/0212-pickup#message-query-with-message-id-list) requires message IDs as arguments.

How does the agent acquire this knowledge?

`batch` provides the messages with their IDs, but then again - the agent will already have the messages?

cc @swcurran @TelegramSam

**Comment by TimoGlastra** [comment]
The RFC mentions the use case of:

> Any message id in message_ids could be delivered via several ways to the recipient (Push notification or with an envoloped message).

So I guess it could be useful when receiving a push notification containing the ID. This way the specific message of the push notification can be retrieved

**Comment by llorllale** [comment]
@TimoGlastra thanks
