### ISSUE TITLE
DIDComm RecipientKeys are they Verification or Encryption keys

### ISSUE THREAD

**Issue by Baha-sk** [hyperledger/aries-rfcs#520]
As seen in the didComm example: https://github.com/hyperledger/aries-rfcs/blob/master/features/0067-didcomm-diddoc-conventions/README.md#service-conventions

`recipientKeys` are shown as verification keys. 

The DIDComm RFC does not mention what's the intended use of keys in `RecipientKeys`, are they used for encryption only, signature verification only or both?

The official definition of `recipientKeys` from [Aries-RFC 067](https://github.com/hyperledger/aries-rfcs/tree/master/features/0067-didcomm-diddoc-conventions) is the following:
>recipientKeys : This is an array of [did key references](https://w3c-ccg.github.io/did-spec/#public-keys) used to denote the default recipients of an endpoint. (note-1)
>
>> 1.  Notes
>>
>>The keys featured in this array must resolve to keys of the same type, for example a mix Ed25519VerificationKey2018 or RsaVerificationKey2018 in the same array is invalid.

I personally prefer to separate encryption and verification keys to increase security resilience, but the spec doesn't mention this anywhere. This issue is created to discuss a more detailed definition of the purpose of keys contained in `recipientKeys` (and probably `routingKeys` as well).

This issue is raised due to a related discussion in [did-core](https://github.com/w3c/did-core/issues/185#issuecomment-668786985)

**Comment by swcurran** [comment]
`recipientKeys` are definitely for encryption -- it's what the sender uses for encrypting the message intended for the recipient.  I'm not sure where they are also used for signing, but @llorllale mentioned they are used for signing.  `routingKeys` are only for encryption, so I think we are fine there.

**Comment by llorllale** [comment]
@swcurran 

Just below https://github.com/hyperledger/aries-rfcs/blob/master/features/0023-did-exchange/README.md#example-1

> The key used in the signed attachment must be verified against the invitation's recipientKeys for continuity.

There's some confusing text in that RFC... need to clear it up... eg.:

> This message is required in the flow, as it updates the provisional information presented in the invitation.

"Updates"?

**Comment by Baha-sk** [comment]
@llorllale the issue is our framework implementation already does signature validation with recipientKeys :(

changing the wording requires changing our code as well.
ref @sandrask 

If we remove this signature verification, then we can treat recipientKeys as encryption only keys.

**Comment by Baha-sk** [comment]
@swcurran, it seems recipientKeys need to have verification keys to verify the (original) invitation signer. The verification must use the recipientKey to ensure the signer is the original sender and avoid man-in-the-middle attacks (by only verifying the key found in the signed attachment as mentioned [here](https://github.com/hyperledger/aries-rfcs/blob/master/features/0023-did-exchange/README.md#example-1))

My proposal is to add a new list of keys in the didComm service so that we can have 1 list for encryption keys and the other for verification keys. The two list can defined as:
RecipientVerKeys
RecipientEncKeys

Or any other suitable names.

Regardless, both RFCs [0023](https://github.com/hyperledger/aries-rfcs/tree/master/features/0023-did-exchange) and [0067](https://github.com/hyperledger/aries-rfcs/tree/master/features/0067-didcomm-diddoc-conventions) need to be updated to clarify the use of public keys.

**Comment by llorllale** [comment]
@Baha-sk 

> My proposal is to add a new list of keys in the didComm service so that we can have 1 list for encryption keys and the other for verification keys. The two list can defined as:
RecipientVerKeys
RecipientEncKeys

We only need verification on oob invitations _only_. So I suggest we modify the OOB invitation to have a separate entry for the verification keys. Then make it clear in the didcomm service conventions that the `recipientKeys` are _only for encryption_.

**Comment by swcurran** [comment]
Don't we need verification keys throughout the relationship?  For example, to be able to sign attachments.  That's why I was thinking there would be additional places.  That said, I think @Baha-sk is right that it is on DID Exchange at the start and then when we rotate the keys, which we've not spent much time on yet...

**Comment by llorllale** [comment]
@swcurran 

> Don't we need verification keys throughout the relationship? For example, to be able to sign attachments. That's why I was thinking there would be additional places.

Yes, we do need them. The key's purpose should be declared via its verification relationship... for signing VCs we have `assertionMethod` and for signing VPs we use `authentication`.... The latter is a bit of a puzzle to me; I think it's because the Holder is implicitly authenticating themselves as such via the `proof` property.

**Comment by llorllale** [comment]
> > My proposal is to add a new list of keys in the didComm service so that we can have 1 list for encryption keys and the other for verification keys. The two list can defined as:
> > RecipientVerKeys
> > RecipientEncKeys
> 
> We only need verification on oob invitations _only_. So I suggest we modify the OOB invitation to have a separate entry for the verification keys. Then make it clear in the didcomm service conventions that the `recipientKeys` are _only for encryption_.

Need to consider implicit invitations in public DIDs... the `service` entries are constrained to `recipientKeys`, `routingKeys`... we want the `did-communication` service type to reference encryption keys only

**Comment by llorllale** [comment]
Additional considerations:

* size of the explicit invitation object (QR codes, query parameter)
* this verification is used only when verifying the signature on the `response`'s attachment with the keys in the `invitation` object

**Comment by llorllale** [comment]
@swcurran @dhh1128 @Baha-sk 

Path forward agreed to on today's B call:

* keep adding just one signature to the attachment in the `response`
* implicit invitations (public DIDs): invitee can use any verification key found in the public DID to verify the signature in the `response`. If the signature does not verify against any of the verification keys in the public DID -> reject (problem-report?)
  * TODO verification relationship
* explicit invitations: need a new field that specifies the verification key to use

**Comment by swcurran** [comment]
Sounds good.  Are you doing the 434 PR for the last bullet?  How about adding the "priority" field at the same time, as noted in the issue raised earlier today in #523
