### ISSUE TITLE
JSON property names in schemas and documents

### ISSUE THREAD

**Issue by pleerock** [hyperledger/aries-rfcs#524]
Is there any discussion / description / specification or why sneak_case was chosen instead of let's say camelCase for property names in JSON schemas? I would like to participate in a discussion, if there is! Thanks.

**Comment by kdenhartog** [comment]
Details on that can be found here: https://github.com/hyperledger/aries-rfcs/blob/e5eec60332fa3761714c114197d0a33d0ae1e5e2/concepts/0074-didcomm-best-practices/README.md#snake_case-and-variants

**Comment by pleerock** [comment]
Thank you! Did you have any public discussions around this design decision? If there is no, maybe it's a good place to start.

> We want to avoid a religious debate about these conventions, and we want to leave developers the freedom to choose their own styles. 

I find it really weird, aries is all about standardization and interoperability, but you left this fundamental part dynamic. Super weird.

> The community tries to use snake_case in JSON key names, even though camelCase is slightly more common.

I think camelCase if quite more common, and many big companies / big apis / libraries adopt camelCase (actually I don't know any popular library adopting snake_case for the json property names). Anyway, you admit its more common, but...

> However, it was felt that snake_case

you make your decision based on _feelings_

> because it didn't raise the questions about acronyms that camelCase does (is it "zeroOutRAMAlgorithm", "zeroOutRamAlgorithm", or "zeroOutRAMalgorithm"?)

and _questionable issues_ (camelCased is used everywhere, including variable names in programming, we all know how to handle these edge cases)

> The main rule to follow with respect to case is: Use the same convention as the rest of the code around you, and in JSON that's intended to be interoperable, use snake_case unless you have a good reason not to. Definitely use the same case conventions as the other keys in the same JSON schema.

or use camelCase unless you have a good reason not to. You kinda want to give a freedom to prevent religious battles, but at the same time you understand that you want interoperability. But community will have to use a snake_case because documentation and source code use snake_case, it will become a standard and people who don't want to use snake_case wouldn't actually have a choice otherwise they can miss interoperability. So, freedom that you gave is almost a fake.

**The reason why camelCase works better is because it's consistent with all other libraries community use and it stays natural with variable names in your code (because at the all property names are just mapped into variables), and you don't have to write separate transformation logic in your code. And the most important w3c DID spec use camelCase. And when I read your RFCs sometimes I see code with snake_case property names, and sometimes I see code with camelCase property names. Super weird.**

p.s. sorry for opening a religious topic, but if not me, somebody else will do it some day anyway.

**Comment by TimoGlastra** [comment]
I agree with you @pleerock. 

The lack of a strict standard, and the inconsistency in casing between property and protocol names is messy. Especially when properties from the DID spec are included in DIDComm messages.

But I think it would be better to have this conversation in the [DIDComm Messaging](https://github.com/decentralized-identity/didcomm-messaging) repo. DIDComm is being extracted from Aries into a 2.0 standard, which Aries will eventually support. As DIDComm is messaging based on DIDs it would make sense to use the same conventions as DIDs.

If DIDComm doesn't move to camelCase it wouldn't make sense to use camelCase in Aries, that would be even messier IMO.

---

> and it stays natural with variable names in your code

That depends on the language you're using. The Python convention is to use snake_case.

**Comment by pleerock** [comment]
> That depends on the language you're using. The Python convention is to use snake_case.

of course. I meant probably 90% percent of languages. But that is not my main point.

Thank you for your response, I'll create same issue in the DIDComm Messaging repo.
