### ISSUE TITLE
Features section folder organization?

### ISSUE THREAD

**Issue by kdenhartog** [hyperledger/aries-rfcs#53]
I noticed that in the features section we've got a bit of overlap around different classes of features. Some are protocols, where as some are modifications to generalized messaging (e.g. decorators or message threading). I think this may be confusing to someone who's looking at this repository as this grows. Would anyone mind (as well as have suggestions) if we grouped features together based on where they might fit?

The alternative to this is to allow the RFCs to exist as a flat structure, and then to create a GHPages site to organize logically similar features and concepts.

**Comment by swcurran** [comment]
What about changing the index.md to be readme.md and update the generator to improve the classification?  In making it the readme, add a stock header (e.g. header.md) that is inserted above the dynamic link lists and include in the header a link to the RFC process (e.g. rfcprocess.md).  We are already extracting the status, extracting a tag would seem to be a minor extension.

**Comment by kdenhartog** [comment]
I like where you're heading with this. This would keep it all self contained rather than needing a separate HTML site that would also need to be maintained and wouldn't require any sort of structural changes to the actual repository.

**Comment by dhh1128** [comment]
I don't mind the categorization idea, but I do want to preserve the flat structure. So I like the general direction of @swcurran 's idea.

**Comment by TelegramSam** [comment]
I've also thought about extracting the title from the RFC for the index.

**Comment by kdenhartog** [comment]
This isn't going anywhere and I don't find that the solution would be particular helpful now. I'm going to close this issue.
