### ISSUE TITLE
RFC0023: clarify signature in 'did_doc~attach'

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-rfcs#534]
The RFC merely states:

> The `did_doc~attach` contains the DID Doc associated with the DID as a signed attachment. If the DID method for the presented DID is not a peer method and the DID Doc is resolvable on a ledger, the `did_doc~attach` attribute is optional.

We should clarify what exactly is being signed. In particular, we would like to make this compatible with existing KMS interfaces where data is signed/verified by the remote KMS. Which would mean this signature should be done over a hash of the did doc's contents as opposed to the raw bytes.

So we should have a top-level `did_doc` attribute with the raw did doc bytes, and the attachment would have a hash of this doc.

**Comment by sklump** [comment]
Just a line here to note that the text states that
_The `did_doc~attach` contains the DID Doc associated with the DID as a signed attachment_
with example
```
{
...
  "did_doc~attach": {
     "base64": "eyJ0eXAiOiJKV1Qi... (bytes omitted)",
     "jws": {
        "header": {
           "kid": "did:key:z6MkmjY8GnV5i9YTDtPETC2uUAW6ejw3nk5mXF5yci5ab7th"
        },
        "protected": "eyJhbGciOiJFZERTQSIsImlhdCI6MTU4Mzg4... (bytes omitted)",
        "signature": "3dZWsuru7QAVFUCtTd0s7uc1peYEijx4eyt5... (bytes omitted)"
      }
   }
}
```

but this is not a signed attachment: it is the signed `"data"` component of a signed attachment; ref. RFC 17 example `report~attach` below:
```
{
  "@type": "https://didcomm.org/xhomebuy/1.0/home_insp",
  "inspection_date": "2020-03-25",
  "inspection_address": "123 Villa de Las Fuentes, Toledo, Spain",
  "comment": "Here's that report you asked for.",
  "report~attach": {
    "mime-type": "application/pdf",
    "filename": "Garcia-inspection-March-25.pdf",
    "data": {
      "base64": "eyJ0eXAiOiJKV1QiLA0KICJhbGciOiJIUzI1NiJ... (bytes omitted to shorten)",
      "jws": {
        // payload: ...,  <-- omitted: refer to base64 content when validating
        "header": {
          "kid": "did:key:z6MkmjY8GnV5i9YTDtPETC2uUAW6ejw3nk5mXF5yci5ab7th"
        },
        "protected": "eyJhbGciOiJFZERTQSIsImlhdCI6MTU4Mzg4... (bytes omitted)",
        "signature": "3dZWsuru7QAVFUCtTd0s7uc1peYEijx4eyt5... (bytes omitted)"
      }
    }
  }
}
```

Should the spec include a `"data"` key, or does the text need a fix?

**Comment by swcurran** [comment]
You are right -- the example in the code needs the extra information as outlined in RFC 0017.

@llorllale -- do you agree?  What have you done in your example?

**Comment by llorllale** [comment]
@sklump @swcurran agreed - the spec text needs a fix to align with RFC0017.

> What have you done in your example?

Implementing the last changes to RFC0023 is still on our TODO list.

**Comment by llorllale** [comment]
To be clear: the purpose of this ticket is to start a discussion around _what_ is being signed, with a mind towards remote KMS systems that may perform the signature on behalf of the agent, and to which the agent may not want to expose identifiers.

I believe a simple tweak in the text to compute the signature over a SHA256 hash of the raw bytes decoded from `base64` wouldn't be too hard to adopt, would it?

**Comment by swcurran** [comment]
I'm not the best on what should be signed.  I agree that a clarification about what it is to signed should be added, but I don't know the pros and cons of signing the (peer did) diddoc vs. the hash of the diddoc.

Of course, if the diddoc had to be repeated at the top level AND in the attachment for signing, that would be horrid.  Is that the concern?

**Comment by llorllale** [comment]
The concern is with the exposure of the did document's contents (including ID) to a remote KMS service. We'd rather limit exposure of identifiers (particularly pairwise ones).

**Comment by swcurran** [comment]
So you are passing the data to be signed to another service (a Remote KMS) and you don't want that service to see the data, just the hash that gets signed.  Is that the concern?

**Comment by llorllale** [comment]
@swcurran that's correct

**Comment by kdenhartog** [comment]
Seems like a hash would work better there in that case. Either would work though from what I can tell.

**Comment by swcurran** [comment]
We discussed this on the [Aries WG Call 2020.10.14](https://wiki.hyperledger.org/pages/viewpage.action?pageId=41583854).

We landed that RFC 0017 Attachments should be updated to allow for the signing of the hash of the attachment payload, probably (required) by using the base64 for the data, a bespoke (SHA256?) way to generated the hash.  If the hash item was put into the attachment, it would be the item signed, not the data.  We asked for volunteers to add that PR and I suggested that it be @kdenhartog do that because (a) he wasn't there and (b) (more importantly) I think Kyle would now how to handle the issues mentioned above (how to create the hash for signing).  Kyle, you game for that?   One note to add that will JSON Canonicalization was mentioned in the call,  and there were some on the call that were against using that.  I suspect Kyle knows that issue and can write the PR accordingly, and we can either just accept what Kyle proposes or debate the issue on the PR.

@llorllale -- once that is in place, some guidance would be added RFC 0023 to suggest that can be used for those concerned about the privacy implications of signing the DIDDoc vs. the hash.

**Comment by kdenhartog** [comment]
What was the opposition to canonicalization? My recommendation would be for JSON data the JCS algorithm is used to take arbitrary JSON in the attachment and post process to reproduce the hash then verify the signature of the hash. 

The secondary approach I'd suggest is to pass the attachment as base64url data with the signature of the hash and then the recipient has the bytes to produce the hash (sent as base64url attachment) and the signature to verify. The downside to this is that the data has to be passed as base64url data which comes with the bloat.

Using LD-Proofs is another potential option, but there's not been many libraries that have written LD Proof suites for hashing even though it's theoretically designed for that. Which then means that people will likely need to write that tooling for that. This is why I'd consider this option the least viable option.

**Comment by swcurran** [comment]
So are you volunteering to write the PR to RFC 0017? @kdenhartog 

Remember in RFC 0017 there is not a guarantee that the data is JSON, which is why it would seem reasonable to say that if you want a signature on the hash (vs. signing the data) that you should have to use either the base64 or the external link attachment variants, as you can avoid any discussion of cannibalization.  Given that if you want to sign the data you probably have to do that anyway, it's not much of a change.

Canonicalization is complicated, even with a library, so if we can avoid it, that's not a bad thing.

**Comment by kdenhartog** [comment]
Sure, that part makes sense to me. I was thinking this update was for only the inline part but from the sounds of it we want a generalized solution.

Here's what I'm thinking I'd update for it (let me know if you agree)

```


data: A JSON object that gives access to the actual content of the attachment. Contains the following subfields:

    jws: A JSON Web Signature over the hash of the content of the attachment. Optional.

    sha256: The hash of the content. Optional. Used as an integrity check if content is inlined. if content is only referenced, then including this field makes the content tamper-evident. This may be redundant, if the content is stored in an inherently immutable container like content-addressable storage. This may also be undesirable, if dynamic content at a specified link is beneficial. Including a hash without including a way to fetch the content via link is a form of proof of existence. When generating a hash of the content in a `json` property, the pre-image of the hash MUST be the UTF-8 encoded bytes output by the Json Canonicalization Algorithm as defined in [RFC 8785](https://tools.ietf.org/html/rfc8785). When the hash is of the base64 content, the pre-image of the hash MUST be the UTF-8 encoded byte representation of the base64 data.

    links: A list of zero or more locations at which the content may be fetched. Optional.

    base64: Base64-encoded data, when representing arbitrary content inline instead of via links. Optional.

    json: Directly embedded JSON data, when representing content inline instead of via links, and when the content is natively conveyable as JSON. Optional.

```

**Comment by swcurran** [comment]
However, we don't want to make the JWS only be over the hash.  The hash is an option, if included, but otherwise the signature is over the data -- whatever that is.

See also the two issues I raised.

**Comment by kdenhartog** [comment]
> However, we don't want to make the JWS only be over the hash

Not understanding why this is a requirement? Can you provide a bit more context?

**Comment by swcurran** [comment]
My interpretation of what you wrote above is that the JWS is *always* over the hash of the content. I think it should only be over the hash if the sha256 field is in the message.  Otherwise, it should be over the content of the data.

**Comment by kdenhartog** [comment]
Yeah that's what I was thinking. The reason I was going that direction was to reduce the bloat of the payload (not sure that's a problem now that we specify using the detached JWS in PR #558 ) and to make it properly abstracted for signing a payload from base64/json/links in a general fashion. It doesn't necessarily have to be done that way, but if we don't then we need to specify how to canonicalize each bytes individually such that the verifier can properly reconstruct the data and verify it.

**Comment by llorllale** [comment]
We must not rely on canonicalization - not all attachment data will be JSON, as @swcurran says.

Having the JWS payload be a hash is good - I like not having detached JWS anymore - means normal library calls to accomplish verification.

I am also weary of forcing DIDComm attachment JWS over hashes - I'd limit the scope of this task to just RFC0023 for now. It's the only protocol explicitly requiring signatures.

**Comment by llorllale** [comment]
DIDExchange is the only protocol requiring signatures.

The existing definition of `data.jws` is:

> A JSON Web Signature over the content of the attachment.

Therefore the DID docs would have to be included outside the attachments in a separate field like we had before (`did_doc`). We would be losing the generality of the attachments mechanism, but we would not be forced to lose privacy, which is far more important.

Or... we force all attachment signatures to be hashes.... this blanket sweep sounds equally forceful in my mind. What do others think?

**Comment by kdenhartog** [comment]
>We must not rely on canonicalization - not all attachment data will be JSON
I'm using canonicalization in a more general form to mean how to encode it to bytes deterministically so they can be signed and verified for any arbitrary type of data. If we don't do this then we're going to effectively just be defining a new way to generate bytes any time we want to hash/sign data.

**Comment by llorllale** [comment]
closed - didexchange has been modified such that the did doc is no longer signed
