### ISSUE TITLE
RFC 0453 - Unclear how to use DIF Credential Manifest in request-credential

### ISSUE THREAD

**Issue by awoie** [hyperledger/aries-rfcs#537]
Can someone (e.g., @troyronda @llorllale) please clarify the following questions on RFC 0453 (issue-credential-v2):

1. Do you intend to use the preview-credential with LDS/LD-Proof-based VCs as well? In that case there is a lot of room for interpretation.

2. How do you provide the W3C Verifiable Presentation in the request-credential message in case a presentation_definition was included in the DIF Credential Manifest in the credential-offer (if format = dif/credential-manifest@v1.0)? The current issue-credential v2 spec uses the DIF Credential Manifest to allow the issuer to tell the holder what information is required. I don't see how one could use the Credential Manifest for including the Verifiable Presentation in the request-credential message. Is this a typo in the issue-credential v2 spec?

**Comment by llorllale** [comment]
@awoie 

> Do you intend to use the preview-credential with LDS/LD-Proof-based VCs as well? In that case there is a lot of room for interpretation.

Yes. We haven't figured out all details w.r.t. how to make effective credential previews for the end user.

Unpacking question 2:

> How do you provide the W3C Verifiable Presentation in the request-credential message in case a presentation_definition was included in the DIF Credential Manifest in the credential-offer (if format = dif/credential-manifest@v1.0)? 

RFC0511 defines [this structure](https://github.com/hyperledger/aries-rfcs/tree/master/features/0511-dif-cred-manifest-attach#request-credential-attachment-format) where you can include the presentation submission (W3C Verifiable Presentation).

> The current issue-credential v2 spec uses the DIF Credential Manifest to allow the issuer to tell the holder what information is required. I don't see how one could use the Credential Manifest for including the Verifiable Presentation in the request-credential message. Is this a typo in the issue-credential v2 spec?

Just to be clear: RFC0453 "issue-credential v2" does not impose DIF's Credential Manifest format or any other attachment format.

RFC 0511 defines envelopes that contain presentation submissions, credential manifests, and other supporting attributes to enable the exchange.

**Comment by awoie** [comment]
Thanks @llorllale . Exactly, I was missing the link to 0511. We can close this issue.
