### ISSUE TITLE
RFC 0030: Connection Sync protocol merge algorithms

### ISSUE THREAD

**Issue by kdenhartog** [hyperledger/aries-rfcs#54]
Have we consider the use of a [CRDT](https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type) as a merge algorithm for the connection sync protocol? They have a few advantages for their use one of which is that they have "Strong eventual consistency" which means that merge conflicts are resolved by the data structure.

**Comment by dhh1128** [comment]
Yes. I started studying this type of data structure recently and I think we will be updating the protocol to use them. Stay tuned.

**Comment by kdenhartog** [comment]
Closing this issue. It's included in the Peer did method spec now.
