### ISSUE TITLE
Ed25519 signature decorator using SHA-256 instead of SHA-512

### ISSUE THREAD

**Issue by glcohen** [hyperledger/aries-rfcs#553]
[The signature decorator RFC](https://github.com/hyperledger/aries-rfcs/tree/master/features/0234-signature-decorator#aries-rfc-0234-signature-decorator) references [the ed25519Sha512_single scheme](https://github.com/hyperledger/aries-rfcs/tree/master/features/0234-signature-decorator#signature-schemes); however, the [linked document](https://github.com/hyperledger/aries-rfcs/blob/master/features/0234-signature-decorator/ed25519sha256_single.md) is called the ed25519**sha256**_single specification.

Given that Ed25519 signing [does in fact use SHA-512](https://ed25519.cr.yp.to/ed25519-20110926.pdf) I'd like to see the spec updated to `ed25519sha512_single`.

**Comment by llorllale** [comment]
@glcohen feel free to push a PR making the naming change. However, the community has largely agreed to move on to using [signed attachments](https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0017-attachments/README.md#signing-attachments).

**Comment by glcohen** [comment]
I should have noticed the status of the document. Thanks @llorllale I will ignore and move to using signed attachments.

**Comment by swcurran** [comment]
FYI - I pushed a PR to move this RFC into "retired" state - #554 .
