### ISSUE TITLE
RFC 0212 - A handshaking requirements

### ISSUE THREAD

**Issue by denizgunseli** [hyperledger/aries-rfcs#563]
[RFC 0212](https://github.com/hyperledger/aries-rfcs/tree/master/features/0212-pickup) mostly covers the batch message retrieve flows of an edge agents. Batch pickup protocol can be called with an parameter - batch_size and it returns batch messages accordingly. All the queued messages can be retrieved with calling status-request and retrieve the total unread message and than calling batch pickup.

**Scenario**
Let's assume that, this protocol is being used for an mobile edge agent and mobile edge agent retrieves all the unread messages with batch protocol. Each time the application opens, agent sends status request and than call batch pickup. Because of there is no stable endpoint for mobile edge agents, mobile agent uses return-route for reading response from same channel.

For a large amount of queued message, mobile edge agent face with a problem during the processing the messages it retrieved from the message_holder via batch-pickup protocol. Although there might be a message store infrastructure in the mobile agent, it might be common that users could close the application in the middle of an operation. Because of all the messages were sent to the edge agent they will not be stored no longer and it cause lost of messages which can not be processed.

**Suggestion**
There should be a handshaking mechanisms for delivered messages. 

In previous conversations about it, it said that it will be very, very close to IMAP by @dhh1128  [PR Conversation](https://github.com/hyperledger/aries-rfcs/pull/414) But in practical use, we are facing with this problem a lot and we lost a lots of data which should be delivered to mobile devices.

**Comment by dhh1128** [comment]
IMAP separates the retrieval of messages from the deletion of messages. Thus, it doesn't matter if the user closes the application in the middle of a retrieval, because retrieval doesn't change what would be retrieved next time. What I'm suggesting is that RFC 0212 should work the same way.

Instead of:

1. Mobile edge agent asks for messages 1-10 and begins retrieving them
2. Other side records that messages 1-10 have been fetched and can be deleted from the queue.
3. Other side begins transmitting messages 1-10
4. Mobile agent disconnects after message 7, so messages 8-10 are lost

We should do:

1. Mobile edge agent asks for messages 1-10 and begins retrieving them
2. Other side begins transmitting messages 1-10
3. Mobile agent disconnects after message 7.
4. Mobile agent reconnects.
5. Mobile agent notices that has fetched messages 1-7, so it tells the other side that those messages can be deleted.
6. Mobile agent asks for messages 8-10.
7. Messages 8-10 are retrieved.
8. Mobile agent tells other side to delete messages 8-10.

**Comment by TimoGlastra** [comment]
I started working on an updated version of this protocol a couple of months ago that does exactly this. It separates retrieval from deletion of messages. See https://hackmd.io/BFh1ZQN4SNWxLgybqzazkA

I never got around to fully write it out, but will update it to a full RFC. 

@denizgunseli @dhh1128 any remarks on the approach as specified in the Hackmd?

**Comment by denizgunseli** [comment]
@TimoGlastra , the "Messages Delete" part is the missing part of the protocol. Rest of them looks almost the same. So we can add this to protocol for solving this problem, right @TimoGlastra  and @dhh1128?

**Comment by TelegramSam** [comment]
Delete is not the only issue with 0212.

One problem that affects both 0212 and @TimoGlastra 's hackMD linked protocol: Both speak of message IDs, but there is some issue with that name and mental model. The ID of a DIDComm message is within the plaintext portion, encrypted during transit. This is fine for the mobile agent which is able to decrypt the message, but useless for the mediator, who cannot. The ID used for coordinating messages cannot be a Message ID, and the name used should reflect that. We should use another name, and define it's meaning, to clear that confusion.

In 0212, the retrieval by ID is a partial solution, and I should have argued against including it at the time. There is no way present to list the IDs of the messages waiting, and therefore no way to discover which messages should therefore be retrieved. I'm mostly in favor of removing that portion of 0212 until a full solution is proposed.

Thoughts on how to clean this up?

**Comment by TimoGlastra** [comment]
@TelegramSam Although the mediator can't decrypt the inner message, it is wrapped inside a `forward` message that it can decrypt, and that message will also contain an `@id`. So if the ID of the `forward` message were to be used it would in fact be a Message ID, just not the `@id` of the inner message.

But I get your point, `message_ids` can be confusing.

---

> I'm mostly in favor of removing that portion of 0212 until a full solution is proposed.

We could add a message to query message metadata. This will give you a list of message IDs with other useful data per message (message size, date received, recipient key, ...)

This would allow a mobile agent to introduce a feature that for example only downloads large messages on wifi (like the "download only headers for large messages" feature outlook has/had in their mail client)

**Comment by denizgunseli** [comment]
![Pickup Business Flow](https://user-images.githubusercontent.com/61782106/98564739-a1d4f080-22a4-11eb-9450-179e9c67c985.png)

To explain more clearly what I mean with Id, I attached the image above. Step-by-step business flow is explained below:

Step 0 ) Initial step. A message is created by cloud agent or any routing message is received by cloud agent to forward to related edge agent. In this step, received routing messages will be converted to route message and than will be packed. At the end of this step there will be a packed message to send to edge agent.
Step 1) If the target agent is an edge agent, message can not be sent so it is transfered to pickup protocol (after a number of retry). 
Step 2) Pickup protocol will create a record for storing this message within the wallet until the target agent requests it or becomes reachable by cloud agent. After storing the record it will have an unique id.
Step 3)  When the target edge agent becomes reachable or requests the message [with id or batch request] pickup protocol will send this pickup message to recipent.
Step 4) Edge agent will receive the message as encrypted.
Step 5) Edge agent will unpack the message and read pickup message within it.
Step 6-a) Edge agent will process the message like any regular encrypted messages they receive.
Step 6-b) Edge agent will create a pickup delete request with using the id of received pickup message
Step 7) Edge agent will pack the delete request
Step 8) Edge agent will send the packed message to the cloud agent
Step 9) Edge agent will unpack the message
Step 10) Id will be appeared after unpack and cloud agent will delete it from wallet with using this id (or mark it as delivered)


With this journey, message will be stored or routed as encrypted but both target and router will use same identifier for packed messages also with this functionality this feature will handle multiple time sending problems for both routing and undelivered message journeys.

**Comment by TimoGlastra** [comment]
I think this issue has been addressed with the addition of Pickup Protocol v2: https://github.com/hyperledger/aries-rfcs/tree/main/features/0685-pickup-v2

If there's other issues related to this topic please open a new issue.
