### ISSUE TITLE
Suggest: Port Cross Domain Messaging Indy HIPE into Aries RFC

### ISSUE THREAD

**Issue by troyronda** [hyperledger/aries-rfcs#58]
Indy [HIPE 0022](https://github.com/hyperledger/indy-hipe/tree/master/text/0022-cross-domain-messaging) (cross domain messaging) is referenced from the Aries RFCs.

References:
- https://github.com/hyperledger/aries-rfcs/blob/master/features/0025-didcomms-transports/README.md
- https://github.com/hyperledger/aries-rfcs/blob/master/features/0048-trust-ping/README.md

**Comment by swcurran** [comment]
PR submitted (https://github.com/hyperledger/aries-rfcs/pull/94) to migrate (with updates) the cross-domain messaging HIPE.

**Comment by kdenhartog** [comment]
Looks like this PR has been merged. I'm going to go ahead and close this issue. Please reopen it if there's additional things you'd like ported/updated in that RFC.
