### ISSUE TITLE
RFC0510: the details

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-rfcs#598]
Presentation-Exchange has a large surface area - we should agree on the subset we want to support for AIP 2.0.

My notes on this so far - to be discussed and add/remove from list:

* constraints.statuses: we don't have use cases for suspended nor revoked. Basically we only support constraints.statuses.active: required
* constraints.fields.predicate: we only support a value of preferred
* we don't yet support hashlinks (schema.uri)
* I'm not too sure what to do about limit_disclosure in the face of what the credential's proof type allows. This would imply a configuration being maintained by the agent indicating which proof types support this feature and which don't
* What level of support do we want to same_subject w.r.t. interop?
* We need to agree on supported values for proof_type
* we only support format of type ldp_vp, and within that for proof_type we only support JsonWebSignature2020, Ed25519Signature2018, BbsBlsSignatureProof2020, EcdsaSecp2556k1Signature2019

**Comment by llorllale** [comment]
@troyronda @TimoGlastra @swcurran

**Comment by TimoGlastra** [comment]
I'll check on the other points, but can comment on the signature related points

> * We need to agree on supported values for proof_type

We're initially adding support for Ed25519Signature2018 and BbsBlsSignatureProof2020, however it shouldn't be that much work to support more in the future.

We can create a JWS, but don't support the JsonWebSignature2020 proof type yet and only support EdDSA signatures (https://w3c-ccg.github.io/lds-jws2020/#jose-conformance). Do you support all algorithms listed in the spec? We would also need to add support for JWK representations of keys.

> * we only support format of type ldp_vp, and within that for proof_type we only support JsonWebSignature2020, Ed25519Signature2018, BbsBlsSignatureProof2020, EcdsaSecp2556k1Signature2019

We're also only adding support for ldp_vp at the moment.

**Comment by swcurran** [comment]
Note that we would REALLY like to support revocation soon.  We know that it's not ready yet, and not part of what Animo is doing but we are trying to do what we can to make that happen.  We may have to settle for the non-ZKP Revocation2020 approach (from DB), but would really like to see Mattr get their new approach done.

FYI -- first cut of PE support in Python nearing completion.  We'll see what it looks like soon.

**Comment by llorllale** [comment]
@TimoGlastra 

> Do you support all algorithms listed in the spec?

AFGO supports all but RSA: https://github.com/hyperledger/aries-framework-go/blob/f1c7f7aa39eca010c0c14cdb8ea7e0287db52368/pkg/doc/signature/suite/jsonwebsignature2020/suite.go#L6-L20

**Comment by llorllale** [comment]
@swcurran @TimoGlastra 

With regards to:

> FYI -- first cut of PE support in Python nearing completion. We'll see what it looks like soon.

I just saw Stephen's announcement that P-E has been implemented in ACAPy. Can resume this conversation on what subset of P-E to support?

**Comment by TimoGlastra** [comment]
Yes, we should definitely resume that conversation.

> * constraints.statuses: we don't have use cases for suspended nor revoked. Basically we only support constraints.statuses.active: required

No revocation yet, so only 'active' (at the moment we don't check yet). How do you check this? What if a credential includes a `credentialStatus` property, do you ignore it and assume it is still valid?

> * constraints.fields.predicate: we only support a value of preferred

Same. Not predicates yet. And with preferred you just mean, no predicates at all right?

> * we don't yet support hashlinks (schema.uri)

Same

> * I'm not too sure what to do about limit_disclosure in the face of what the credential's proof type allows. This would imply a configuration being maintained by the agent indicating which proof types support this feature and which don't

Agree. This is something internal, but I think it should work along the lines of:

- If `limit_disclosure` is `required`, but the signature suite doesn't allow selective disclosure, throw an error
- If `limit_disclosure` is `preferred` or not present use selective disclosure if the suites supports it

> * What level of support do we want to same_subject w.r.t. interop?

No supported ATM. What do you propose? Seems like you either support it or you don't. Or are there some in between steps?

> * We need to agree on supported values for proof_type


As mentioned earlier, we're working on Ed25519Signature2018 and BbsBlsSignatureProof2020. I'm not sure what the plans for supporting more proof types are after that. @swcurran?

As long as we have some overlap we should be good to go, ACA-Py just won't be able to issue or verify documents with a proof type of `JsonWebSignature2020` or `EcdsaSecp2556k1Signature2019`

> * we only support format of type ldp_vp, and within that for proof_type we only support JsonWebSignature2020, Ed25519Signature2018, BbsBlsSignatureProof2020, EcdsaSecp2556k1Signature2019

We also only support `ldp_vp` with `Ed25519Signature2018` and `BbsBlsSignatureProof2020`


---

An overview of what we don't support (yet):

- same_subject
- is_holder
- limit_disclosure -> working on this
- checking credentialStatus
- path_nested inside descriptor_map
- predicate

**Comment by llorllale** [comment]
@TimoGlastra 

* `constraints.statuses`: [AIP 2.0 draft](https://github.com/hyperledger/aries-rfcs/pull/579/files) only mentions AnonCreds-based revocation thus far, so we won't be able to interop on revocation use cases
* `constraints.fields.predicate`: right - no predicates because we don't know of an efficient mechanism to do this with JSONLD-based credentials
* `schema.uri`: ok - no hashlinks
* `same_subject`: seems like a suitable descriptor with `constraints.fields.filter` of `type: "string"` and a suitable `pattern` (such as a DID) can accomplish the same thing. I am inclined to skip this one for now.
* `proof_type`: AFGO is good with `Ed25519Signature2018` and `BbsBlsSignatureProof2020`

----

### Narrowing it down

Can we narrow down the scope to the following items as a first cut for interop for present-proof v2 with P-E and based on JSONLD credentials?

* support `Ed25519Signature2018` and `BbsBlsSignatureProof2020` proof types
* support `limit_disclosure: "preferred"`
* support `limit_disclosure: "required"` **if and only if** proof type is `BbsBlsSignatureProof2020`
* support `predicate: "preferred"` as defined in the spec
  * note: standards not there yet for holders to create predicate proofs on the fly based on JSONLD credentials
* support `constraints.fields.path`
* support `constraints.fields.filter`


Is anything missing from this ^ list?

**Comment by TimoGlastra** [comment]
I see `definitions` is written in plural everywhere (format name and json objects), while the spec always talks about `definition` (singular). As we're already updating the RFC with a subset, maybe we can make also make that change.

@llorllale are you OK with that change?

**Comment by llorllale** [comment]
@TimoGlastra agreed

**Comment by TimoGlastra** [comment]
Documenting additional requirements for updated RFC:
- Add `nonce` to 0510 (for inclusion in BBS+ derived proof)
- Add language whether `challenge` / `domain` are required (I think not?)
- Note that presentations are not required to include proofs. I think the tooling in ACA-Py doesn't handle presentations without proof very well yet, but it's a valid usage of VPs that would be good to communicate.

@llorllale let me know if you disagree with any of the above points

**Comment by troyronda** [comment]
Cross-link: https://github.com/decentralized-identity/waci-presentation-exchange/issues/6

**Comment by llorllale** [comment]
@TimoGlastra 

> Add language whether `challenge` / `domain` are required (I think not?)

They are not required but are good practice (should include `challenge` at minimum).

> Add `nonce` to 0510 (for inclusion in BBS+ derived proof)

What is the difference between this and `challenge`? And why does the BBS+ JSONLD context [include both](https://w3c-ccg.github.io/ldp-bbs2020/contexts/v1/) for `BlsBbsSignatureProof2020`? Can `challenge` in a proof request instead of `nonce`?

**Comment by TimoGlastra** [comment]
> What is the difference between this and `challenge`?

I'm not sure. The derive proof library we use takes a nonce as input.

> And why does the BBS+ JSONLD context [include both](https://w3c-ccg.github.io/ldp-bbs2020/contexts/v1/) for `BlsBbsSignatureProof2020`?

If the `BlsBbsSignature2020` proof contains a challenge, the derived credential can also contain a challenge. I think that's why it's included the `BlsBbsSignatureProof2020`?

> Can `challenge` in a proof request instead of `nonce`?

I guess we could use the challenge as a nonce. I don't know enough about the difference between the two to answer this question

**Comment by troyronda** [comment]
`nonce` is an input to the selective disclosure proof. https://w3c-ccg.github.io/ldp-bbs2020/#nonce
It is defined by the BBS2020 suite for that purpose.

> When a proof is derived it is often useful to prove to the audience of the proof the uniqueness or freshness of proof, the nonce attribute can be used to communicate this.

Implementations of BBS use this field as part of the derivation.
>A linked data document featuring a BBS+ proof of knowledge linked data proof MUST contain a nonce attribute.

`challenge` is defined by LD signatures . https://w3c-ccg.github.io/ld-proofs/
> A random or pseudo-random value used by some authentication protocols to mitigate replay attacks.

**Comment by TelegramSam** [comment]
merged associated PR.
