### ISSUE TITLE
Multiple format identifiers for attachment registries adds unnecessary complexity

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-rfcs#599]
Issue credential and Present proof v2 add a registry to each message for different attachment formats. Each message now uses different format identifiers and mime-types. 

Now looking at it from an implementation perspective this adds complexity without adding more information. Having a unique format identifier for each message provides no value over having the same identifier for each message as the expected content can be identified from the message + format identifier combination. 

What's the difference in context between the two tables below?

| `@type`                                   | format                      | mime-type                        |
| ----------------------------------------- | --------------------------- | -------------------------------- |
| `/issue-credential/v2/propose-credential` | `hlindy/cred-abstract@v2.0` | `application/indy-cred-abstract` |
| `/issue-credential/v2/request-credential` | `hlindy/cred-req@v2.0`      | `application/indy-cred-req`      |
| `/issue-credential/v2/issue-credential`   | `hlindy/cred@v2.0`          | `application/indy-cl-anoncred2`  |

| `@type`                                   | format             | mime-type          |
| ----------------------------------------- | ------------------ | ------------------ |
| `/issue-credential/v2/propose-credential` | `hlindy-cred@v2.0` | `application/json` |
| `/issue-credential/v2/request-credential` | `hlindy-cred@v2.0` | `application/json` |
| `/issue-credential/v2/issue-credential`   | `hlindy-cred@v2.0` | `application/json` |

Using a single format identifier (+ simpler mime-types) for all messages will require a lot less checks and still carry the same meaning.

I also used multiple format identifiers in #593, but now it's still possible to change all formats to use a single identifier.

Thoughts?

**Comment by sklump** [comment]
I agree 100% - thanks Timo

**Comment by sklump** [comment]
Similarly for RFC 454: all types should be something like `hlindy-pres@v2.0`.

**Comment by sklump** [comment]
Note that https://github.com/hyperledger/aries-rfcs/pull/607 incorporates the above, with hlindy@v2.0 and dif@cred-manifest@v1.0, dif@pres-exch@v1.0.
