### ISSUE TITLE
RFC 592 cred-abstract/proof-request removes functionality from RFC 36/37 cred-proposal/presentation-preview

### ISSUE THREAD

**Issue by sklump** [hyperledger/aries-rfcs#601]
RFC 36 credential proposal allowed for the holder to ask for attribute values and MIME types (e.g., I want an ID: here is my picture, it's a .BMP; please notarize this letter from the mayor; it's a .pdf). In RFC 592, neither indy cred request format nor indy cred abstract format allows for these features.

Similarly, RFC 37 presentation proposal allowed for the prover to propose attribute values to prove with MIME types for verifiers to interpret them (e.g., I can prove this is my face; it's a .JPG). In RFC 592, proof request cannot furnish this amenity either.

Will any users miss this functionality?

**Comment by sklump** [comment]
... in addition, using a proof request instead of an RFC 37 introduces non-revocation quibbles into the proposal, where the consensus last time around removed it from this phase on purpose _(although to be fair, I can't remember why exactly why, or if it's an important difference)_.

**Comment by TelegramSam** [comment]
Closed per WG Discussion 20210414.
