### ISSUE TITLE
RFC0023: clarify `did` vs `did_doc~attach` in requests and responses

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-rfcs#609]
(this is a partial response to an issue in AFGO: https://github.com/hyperledger/aries-framework-go/issues/2415)

(see my relevant PR #608)

I think the mechanics of resolving the sender's DID in request and response messages could be improved to minimize ambiguity.

For the purposes of this discussion, this is all the RFC says for `did_doc~attach`, for both `request` and `response`:

> The `did_doc~attach` contains the DID Doc associated with the DID as a signed attachment. If the DID method for the presented DID is not a peer method and the DID Doc is resolvable on a ledger, the `did_doc~attach` attribute is optional.

I think this needs to be clarified - what is a "peer method"? Is this a reference to `did:peer` or is it a concept (aka "ledger-less DID")?

I think this merits a concrete algorithm to be specified in the RFC. Here is my take:

1. Ensure `did` is present (see PR #608)
2. Validate the `did` method is supported by your implementation
3. Handle DID doc resolution depending on the DID method:
  a. If it's a "ledger-less" method, like `did:peer`, then resolve it against the `did_doc~attach` attribute
  b. Else resolve it against a common VDR
4. Validate `did` and the resulting DID document using the DID method rules
5. Additionally, ensure the DID document has a [did-communication service](https://github.com/hyperledger/aries-rfcs/blob/master/features/0067-didcomm-diddoc-conventions/README.md#service-conventions)

Note that because `did` is REQUIRED to be a DID and not a DID URL, some DID methods are not compatible because they inherently do not have service endpoints (unless you were to "patch" them with DID URLs), eg. `did:key`.

**Comment by llorllale** [comment]
Note: we should agree on `did:peer` compatibility

**Comment by swcurran** [comment]
@sklump -- can you please review this from an ACA-Py perspective.  How does this proposal reflect what we have implemented.

@llorllale -- agree on the `did:peer` comment. Right now, I think we just provide a DIDDoc at connection time and call that a "peer DID".  That should be formalized.  Again -- glad to have Stephen K and @andrewwhitehead weigh in on this.

**Comment by llorllale** [comment]
@swcurran @sklump I split the topic of `did:peer` out into #611

**Comment by TelegramSam** [comment]
@llorllale does anything remain on this Issue for AIP2?

**Comment by TelegramSam** [comment]
closed per discussion in WG 20210512 per merge of #658.
