### ISSUE TITLE
AIP 2.0: support for the did:peer method

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-rfcs#611]
(carrying on from [here](https://github.com/hyperledger/aries-rfcs/issues/609#issuecomment-797179978) and [here](https://github.com/hyperledger/aries-rfcs/pull/579#issuecomment-797180693))

One of the cornerstones of the DIDComm architecture has been establishing secure communication channels involving only the necessary parties and without the use of public registries. For this we have been using the `did:peer` method to exchange the cryptographic material and service endpoint needed for point-to-point communication.

Oddly enough, adoption of `did:peer` has not been formalized into an AIP profile yet, and it's time we do so.

AFGO has supported method 1 of `did:peer` in "static mode" for a long while now ("static mode" == no support for [RFC0030](https://github.com/hyperledger/aries-rfcs/blob/master/features/0030-sync-connection/README.md) yet). Edit: no support for [authorization](https://identity.foundation/peer-did-method-spec/#authorization)

Can we get agreement on officially adopting `did:peer` method 1 in "static mode" as a first step for AIP 2.0?

Note that formally adopting `did:peer` implies by extension the formalization of support for the did-core data model. For instance, some implementations are still sending keys in the now-nonexistent `publicKey` array. Edit: pushed PR to refactor `did:peer` - `publicKey` -> `verificationMethod`: https://github.com/decentralized-identity/peer-did-method-spec/pull/27

**Comment by dhh1128** [comment]
#627 attempts to provide a crisp definition of what peer DID features we need to support for AIP 2.

**Comment by TelegramSam** [comment]
related PR merged.
