### ISSUE TITLE
Question regarding requesting and presenting credentials

### ISSUE THREAD

**Issue by GuilhermeMenezes** [hyperledger/aries-rfcs#642]
Hello everyone, I hope I find you well,

I just wanted to ask if there is any way of requesting and presenting credentials without using Zero Knowledge Proof and if there are any code examples.

Kind regards,
Guilherme

**Comment by swcurran** [comment]
Work is happening on exchanging JSON-LD credentials with 25519 and BBS+ Signatures, the latter supporting selective disclosure.  Aries Framework Go has working code, while Aries Cloud Agent Python has a PR nearing merge that has the same functionality.  There are several RFCs related to this -- [0593](https://github.com/hyperledger/aries-rfcs/tree/master/features/0593-json-ld-cred-attach) describes how to use JSON-LD credentials with the Credential Exchange procotocls V2 (RFC 0453/0454) and RFC 0510 describes how to use DIF Presentation Exchange with JSON-LD credentials for presentations.

**Comment by swcurran** [comment]
Closing this issue as answered.  @GuilhermeMenezes -- please reopen if you want more details or the question is not answered.
