### ISSUE TITLE
Remove some of the "links" examples from Attachments RFC

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-rfcs#657]
In reviewing [RFC 0017 Attachments](https://github.com/hyperledger/aries-rfcs/tree/master/concepts/0017-attachments) I noticed that there are several examples of ways to process links that are not easily supported and I think should be removed.  Notably:

- Content in a previous DIDComm message.  This forces a change in the message retention policy of an Aries agent.
- Promise to supply data (`didcomm://fetch`). It is not at all clear what this means or why it would be used.

I also question what kind of resolver support is needed if the examples for IPFS, S3, BitTorrent and Indirect BitTorrent have to be supported.  Wouldn't all of those require additional supporting client software be embedded in all Aries Agents?

Assuming I'm interpreting this correctly, I think those examples should be removed beyond HTTP/HTTPS.

What do others think?

**Comment by TelegramSam** [comment]
merged associated PR
