### ISSUE TITLE
Update Example from RFC 0360

### ISSUE THREAD

**Issue by Matt-Spence** [hyperledger/aries-rfcs#664]
The example on transforming an Ed25519 public key to a did:key reference seems to use the wrong multicodec identifier for an ed25519 public key. [The W3C spec](https://w3c-ccg.github.io/did-method-key/) says to prepend the raw key bytes with the multicodec identifier for the key type, which according to [this](https://github.com/multiformats/multicodec/blob/master/table.csv) (line 85) is 0xed for Ed25519-pub. The example says "Multicodec: Prefix with the algorithm type. In this case, ED01 as the key type is ed25519.". The RFC should be updated to use the correct multicodec identifier.

**Comment by swcurran** [comment]
Resolved with #666
