### ISSUE TITLE
Goal Codes in 0023 DID Exchange

### ISSUE THREAD

**Issue by domwoe** [hyperledger/aries-rfcs#671]
Goal codes are currently not mentioned in RFC 0023, although they could be useful from my perspective in the scenario when a DID Exchange is not initiated by a particular out of band invitation, but by an ad hoc request to a public DID. The receiver could use this goal code to decide if the request should be accepted and which presentation request to send.

Should we allow  goal codes in the DID exchange request?

**Comment by swcurran** [comment]
Goal codes are used in OOB which is one way to trigger DID Exchange 0023, so that path is covered. The implicit invitation route to start a DID Exchange is possible -- is that where you would like to see goal codes used?

**Comment by domwoe** [comment]
My mental model is as follows:

If an entity creates a OOB invitation it wants to signal an intention to the receiver of the invitation. Therefore a goal code can be used and this is already in place.

However, if an entity has a public DID, the roles turn around. The entity sending the request to the public DIDs might want to signal an intention the receiver of the request and this is currently not covered.

**Comment by swcurran** [comment]
Can you do a quick PR for that?  Really nice if we can get it into AIP 2.0, which we hope to close next Wednesday.

**Comment by domwoe** [comment]
I'll try.

**Comment by domwoe** [comment]
Included with #672
