### ISSUE TITLE
Conventions for linked documents in VCs

### ISSUE THREAD

**Issue by TelegramSam** [hyperledger/aries-rfcs#686]
When you have data too large to place inside a VC itself, it makes sense to place a link to the data, along with a hash of the data to verify that it has not been tampered with.

It would be helpful to establish conventions for doing so, to enable good UX and credential processing.

There are two items needed: a URL and a hash.

For the hash portion, I suggest MultiHash.

For presenting both the URL and the hash, I see two options:

### Option 1: Split Attributes
Present URI and the integrity hash in separate attributes, linked by convention.

Example: 
```
document: http://example.com/doc/path.pdf
document_integrityhash: ASDFAGAQEWGAWEF
```

Upsides: Simple. 
Downsides: split attributes could confuse users if not displayed correctly

### Option 2: Combined Attribute
Combine the integrity hash with the URL, perhaps as a query parameter

Upsides: single attribute is simpler.
Downsides: potential collision in a combined format.

Example: 
```
document: http://example.com/doc/path.pdf?integrity_hash=ASDFAGAQEWGAWEF
```

### Questions

- Has this already been solved? 
- What am I not aware of?
- How are others handling this?

**Comment by swcurran** [comment]
The Hashlink spec is designed to handle this -- https://datatracker.ietf.org/doc/html/draft-sporny-hashlink

Could that be used?  Requires participants to understand hashlinks, but at least someone has already thought about it enough to write a spec. style document about it.

**Comment by talltree** [comment]
+1 to using hashlinks for this provided they meet the use case. This is one
reason hashlinks are supported in the W3C Decentralized Identifiers (DIDs)
1.0 spec <https://www.w3.org/TR/did-core/#did-parameters>.

=Drummond

**Comment by awoie** [comment]
+1 to hashlinks

**Comment by TimoGlastra** [comment]
We've worked on this recently (with implementation in AFJ). It uses hashlinks to link to an external object, and uses DIDComm attachments to carry over the attachments. This allows to inline the data in the
attachments or use links. This way you don't bind the VC to a specific URL. May need some tinkering for some use cases, but looks like this is what you are looking for.

https://github.com/hyperledger/aries-rfcs/pull/641

**Comment by TelegramSam** [comment]
Excellent, y'all. I did spend time googling, but term overloading made this fairly ungoogleable.

**Comment by swcurran** [comment]
I'm a bit shattered, I have to say.  Sam knows all -- I've always believed that. And yet...

**Comment by TelegramSam** [comment]
Closing, as the right solution exists as PR #641
