### ISSUE TITLE
Message using @ before attribute values

### ISSUE THREAD

**Issue by vongohren** [hyperledger/aries-rfcs#698]
Hi! Just wondering why your did com messages is using @type and @id when the spec does not?
https://github.com/hyperledger/aries-rfcs/blob/main/features/0434-outofband/README.md#invitation-httpsdidcommorgout-of-bandverinvitation this is the message.

But this is didcom spec: https://identity.foundation/didcomm-messaging/spec/#invitation-httpsdidcommorgout-of-bandverinvitation

I guess the spec trumphs these thoughts right?

**Comment by swcurran** [comment]
The DIDComm spec you are referencing is DIDComm V2 that is being defined at DIF.  Aries uses the agreed upon DIDComm V1 that is part of these RFCs, and the message types are defined in the [Message Type RFC](https://github.com/hyperledger/aries-rfcs/tree/main/concepts/0020-message-types) where `@type` and `@id` are defined.
