### ISSUE TITLE
RFC 0023: Request attribute label is not marked as optional

### ISSUE THREAD

**Issue by jakubkoci** [hyperledger/aries-rfcs#710]
Attribute label in [DID Exchange Request message](https://github.com/hyperledger/aries-rfcs/tree/b3a3942ef052039e73cd23d847f42947f8287da2/features/0023-did-exchange#request-message-attributes) it's not marked as optional, but the same attribute is optional in [OOB Invitation](https://github.com/hyperledger/aries-rfcs/tree/bed4989dd6517f7a9de3696800e57e4c6ef49231/features/0434-outofband#invitation-httpsdidcommorgout-of-bandverinvitation). 

It seems weird to me because it says one side is required to provide a label and the other is not. Also, a recipient should not rely on this attribute, so I think the label should not be mandatory at all.

**Comment by TelegramSam** [comment]
Discussed WG 20220316. Is inconsistent. Changes would have implications on AIP 2.0. A note should be added noting that inconsistency, and recommend using either an empty string or a set value ("Unspecified") in the value of the required label (that should be optional). Timo volunteered.
