### ISSUE TITLE
RFC 0023: add n-wise support

### ISSUE THREAD

**Issue by dhh1128** [hyperledger/aries-rfcs#72]
We need to have a way to describe how DIDs are exchanged when the relationship under construction is n-wise instead of pairwise. The following document, capturing an exploration with @Oskar-van-Deventer, may be a useful starting point: https://docs.google.com/document/d/1BjYdivGQ9GxIz9CJ2ymNvMA68uHZm8bFOTyCHDmziOU/edit

**Comment by TelegramSam** [comment]
Continue issue progress here: https://github.com/decentralized-identity/didcomm-messaging/issues/18
