### ISSUE TITLE
RFC 0025: rename "didcomms" --> "didcomm"

### ISSUE THREAD

**Issue by dhh1128** [hyperledger/aries-rfcs#73]
The rationale for doing this is described and may be debated in rocket.chat: https://chat.hyperledger.org/channel/aries?msg=haDnrASscA5S7HJC9

Here is an inline copy of the beginning of that thread:

[Daniel H]: In English, we have the phenomenon of count nouns and non-count nouns. A count noun is something that you count with integers: cars, shoes, phones, etc. We say, "I own 3 cars." A non-count noun is something that you quantify as a collective or mass: "My car is emitting a lot of smoke." "I bought 3.5 bushels of wheat."

Count nouns carry plural markers in English: I own 3 car*s*.

Non-count nouns do NOT carry plural markers in English. We would not say, "I saw 3 smokes coming out of my tailpipe when I started the car."

It is possible for a noun to be both a count noun and a non-count noun. "Water" is a great example. Normally, water is a non-count noun--we measure it in real units, as a collective. However, when a waiter takes our order at a restaurant, he may say, "Okay, so that's 3 waters, right?" When this happens, we're implying that we've packaged the non-count, collective noun in a discrete form.

When you turn nouns into adjectives, usually the non-count, non-plural version is more common. We talk about "water-borne illnesses" and "watercraft", not "waters-born illnesses" and "waterscraft".

So what about the word "communication"?

Well, "communication" is normally a non-count noun. We say things like "There's a lot of communication happening" (non-count collective) or "The internet backbone carries 3.9 terabytes of communication per second in the transatlantic cable" (units +real quantifying a collective but not discrete items).

We also use communication as a count noun, in the same way that my water example does. If each discrete communication event is counted, then we can say things like, "27 communications arrived on this radio channel in the past hour."

So, what would "didcomm" imply, and what would "didcomms" imply?

"Didcomm" means communication in bulk, uncounted. It is also the appropriate adjective form. "Didcomms" means individual, countable didcomm events.

Almost always, we want the non-plural, non-count sense.

As I said before, I really don't care how we talk informally--but in formal written artifacts, I suggest that we follow best practice grammar and use the form without the 's'.

**Comment by dhh1128** [comment]
@TelegramSam ^^

**Comment by kdenhartog** [comment]
I've started to adapt my language to support DIDComm in writing. Out of force of habit when speaking I'll probably still use the 's' because I like the sound better though.

**Comment by TelegramSam** [comment]
I support this. We'll see how quickly I can correct my verbal usage. :)

**Comment by dhh1128** [comment]
The discussion on Rocket.Chat more or less paralleled the one here. We'll use "didcomm" in formal written stuff, and not worry about the variation/style that people pick otherwise.
