### ISSUE TITLE
RFC 0510 and RFC 0454 use different format identifiers

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-rfcs#762]
0510 uses `dif/presentation-exchange/definition@v1.0` while 0454 uses `dif/presentation-exchange/definitions@v1.0` (notice the `s`). 

It seems ACA-Py implemented with the `s` (from RFC 0454). AFJ has a PR open which also uses the format with the `s`. Should we update 510 with a note?

**Comment by TimoGlastra** [comment]
AFGO also uses `dif/presentation-exchange/definitions`. So it's obvious which to go with I think

**Comment by swcurran** [comment]
Yes — please add a PR to add the “s”.  I think we should be safe in calling it a clarification, but we can discuss that on an Aries Working Group call.

**Comment by TelegramSam** [comment]
Discussed 20230322. Rodolfo will fix alongside the other issue's PR.

**Comment by rodolfomiranda** [comment]
fix in https://github.com/hyperledger/aries-rfcs/pull/777
