### ISSUE TITLE
RFC 0510 uses the same format identifier for different objects

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-rfcs#763]
RFC 0510 uses the `dif/presentation-exchange/definition@v1.0` format identifier for the proposal and the request message, but the actual payload is different between them. This makes that the format alone isn't enough to identify the format, but you need the message type + the format identifier.

I think this is a mistake as the formats were designed to be separate form the proof protocol.

Not sure what to do with it, but want to raise it here for awareness. Maybe a note should be added to the RFCs?

**Comment by TelegramSam** [comment]
Discussed 20230322. Instead of fixing the format identifier and introducing a breaking change, calling this out in the RFC would shine a light on the need to consider both the message type and the format identifier. Rodolfo volunteered.

**Comment by rodolfomiranda** [comment]
fix in https://github.com/hyperledger/aries-rfcs/pull/777
