### ISSUE TITLE
Process: Should updates be discussed in issues or PRs?

### ISSUE THREAD

**Issue by kdenhartog** [hyperledger/aries-rfcs#79]
@dhh1128 @TelegramSam @swcurran @llorllale On PR #70 there's active discussion going for an update. It appears to be going well in there, but this could lead to a PR hanging for awhile. Would we prefer updates to be discussed in Issues or PR comments?

**Comment by dhh1128** [comment]
I would prefer for substantive updates to an existing RFC to be issues, and to be discussed there, before they become PRs. However, there is nothing stopping someone from raising a PR without having a discussion first in an issue--and if they do, I suppose exploring the rationale in the PR is as good a place as any.

Regarding #70 specifically, I think we are stalled waiting for some other RFCs to be updated.

**Comment by llorllale** [comment]
@kdenhartog @dhh1128 I may have misjudged the mechanics of updating RFCs....

In my mind, I was merely "adding minor bits and pieces" to existing protocols and concepts. That's why I went straight for a PR.

**Comment by dhh1128** [comment]
@llorllale I think it's fine. The important thing was that you surfaced an interesting idea and we're talking about it. :-)

**Comment by kdenhartog** [comment]
Sounds good. I've marked the PR as "paused" until the other RFCs can get updated.
