### ISSUE TITLE
RFC 0028 - Enhance `request` message

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-rfcs#99]
**Problem**
The [`request`](https://github.com/hyperledger/aries-rfcs/tree/master/features/0028-introduce#request) message of the [Introduce](https://github.com/hyperledger/aries-rfcs/tree/master/features/0028-introduce) protocol assumes both introducees already know each other - they just haven't formed a "DIDComm" connection between them.

The above assumption leaves out a large swathe of real-life introductions where the two introducees have *no previous knowledge of each other*.

Furthermore, requests for introductions in these types of scenarios typically include prerequisites: 
* *My kitchen sink is clogged and leaking, can you recommend a good **plumber**?*
* *We're thinking of buying a house - can you introduce me to your **tax consultant**?*

**Proposal**
To address the first issue (no prior knowledge), let's explicitly make `name`  an optional attribute of `please_introduce_to`.

I'm open to ideas to address the second issue (prerequisites). The key thing is that the requestor needs to convey the requisites to the Introducer, narrowing down for the latter the space of potential introducees to provide. 

To me it seems like a good aproach would include the `request-presentations~attach` object from the [Present Proof](https://github.com/hyperledger/aries-rfcs/tree/master/features/0037-present-proof#request-presentation) Protocol in a semantically meaningful way for the Introducer to understand that the request for proof is not for them to fulfill - it is for them to relay that request to the potential candidate introducees on behalf of the original requestor.

**Comment by llorllale** [comment]
One potential consequence of this approach is that due to the fact that several prerequisites might be specified, a series of introductions might ensue if the Introducer does not know of a single party that satisfies all criteria, but knows several that, overall, satisfy them all.

**Comment by dhh1128** [comment]
@llorllale The docs on the protocol give the wrong impression if they suggest that the two parties know each other. The assumption I was going for was that the two parties know some shared context. It might be that Fred verbally told each of them that he had a nice friend he wanted to introduce, but it was never intended to be stronger than that. So we should definitely revise the RFC to make that clearer, as you suggest. I will come up with a revision and run it by you. Let's collaborate.

On the topic of prerequisites, I agree that this is a useful feature. I am pondering the best way to do it. I'll leave comments here as soon as I have some thoughts--or you can, if you beat me to it.

**Comment by llorllale** [comment]
@dhh1128 can we agree on this general outline of events?

1. Introducee requests the Introducer to introduce them to parties that collectively satisfy a set of criteria
2. Introducer does best effort to satisfy that request. It may find one party that matches all criteria or it may find N parties that each individually match a subset of the criteria
2.1. If Introducee cannot satisfy any of the criteria, it should inform the Introducee to make a decision.
2.2. If Introducee gives a positive response, the protocol's state can proceed to the next step
3. Introducee instantiates N rounds of the `introduce` protocol

**Comment by dhh1128** [comment]
@llorllale Generally, I like that. However, I think sometimes the introducer, not the introducee, begins the process. ("Alice, would you mind if I introduced you to my friend George?") It's not always the case that the introducee is the first mover, and has crisp criteria in mind. So we need a way to allow both variants.

**Comment by llorllale** [comment]
@dhh1128 yes - I am focusing on the flow initiated by the introducee as I feel the one started by the introducer is fairly complete

**Comment by llorllale** [comment]
@dhh1128 how can we move this forward. I have a sketch of the sequence of messages - I'm not sure if I should dump all those here (it's a bit long). And this issue is assigned to you, so I'm not sure if I can push a PR for this.

**Comment by dhh1128** [comment]
I am interested in this topic, but buried by other priorities. I like your thinking and would be excited if you moved the ball forward by raising a PR. I don't mind raising a PR myself, but if I'm the one that does it, it will probably be slow to happen. Up to you.

One other way, besides a PR, that we could move this forward would be to convene a conversation about it. Since we're the only two talking, it could just be between us. But we could also take it broader, if you feel the need for more input. If you keep it pairwise, I'll send you a DM on chat about how to book me.
